### ISSUE TITLE
Apply user-defined Ceil simplification rules over builtins

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1045]
We do not presently apply user-defined Ceil simplification rules (definedness rules) if the argument of Ceil is a builtin pattern.

---

- [x] Identify Ceil-builtin patterns by their symbols (#1023)
- [x] ~Improve matching on builtin Map and Set (#1028)~ (#1183)
- [ ] Apply axioms during Ceil simplification with [builtin arguments](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/Ceil.hs#L190)

**Comment by ttuegel** [comment]
I closed #1028 because the approach suggested there is too naive to work, but the following might work for matching abstract Map and Set patterns. Recall that matching is asymmetric: we want substitutions for variables in the **matching** pattern to make it equal to the **matched** pattern.

1. Match all the concrete keys in the matching pattern to the matched pattern. If any concrete key is missing, the patterns do not match.
1. If any abstract keys in the matching pattern occur exactly in the matched pattern, then match the corresponding values.
1. Match the remaining abstract keys (and their values) in the matching pattern to the remaining concrete keys in the matched pattern.
1. Match the remaining abstract keys (and their values) in the matching pattern to any remaining abstract keys in the matched pattern.
1. At this point, if any abstract keys in the matching pattern have not been matched, then the patterns do not match.
1. If any exactly-identical opaque terms appear in both patterns, match them.
1. If there is exactly one remaining opaque term in the matching pattern, match it with any unmatched keys or opaque terms in the matched pattern.
1. There must be no remaining terms in the matched pattern. Match all remaining opaque terms in the matching pattern with the empty Set or Map.

**Comment by ana-pantilie** [comment]
If you have a #Ceil rule which doesn't apply, open a new issue with that example
