### ISSUE TITLE
Kore.Step.Result.Results is hard to use

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1121]
The `Semigroup` and `Monoid` instances are challenging because they invite abuse (discarding remainders). With minor refactoring to `Kore.Step.Step`, we can eliminate any use of these instances.

See also: #1037

**Comment by ana-pantilie** [comment]
Let's also not import the same module 3 times just named differently: https://github.com/runtimeverification/haskell-backend/blob/5b558293cce9d8c5813560a645380863b12b1990/kore/src/Kore/Rewrite/Step.hs#L76 :D

**Comment by ana-pantilie** [comment]
New representation of `MultiOr` should have fixed the issues here.
