### ISSUE TITLE
Solve recursive predicates with Mu

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1258]
In the presence of the `hybrid` attribute, the frontend generates a `isKResult` function with a recursive predicate which diverges during evaluation. We should resolve this issue by translating the `isKResult` function to a sort-like symbol `KResult` defined with `\mu`, and implementing proper support for unification with `\mu`.

See also: #1253

**Comment by virgil-serbanuta** [comment]
Just curious: so we really want unification with mu or is matching going to be good enough?

**Comment by ttuegel** [comment]
This would definitely require unification with `\mu`. I'm not sure that we definitely want to go this way, but @yzhang90 and I were going to discuss the design. We can decide if this is the right way to go once we have some particular design in mind. There is a suitable work-around (#1253) so this should not be neede in the near-term.
