### ISSUE TITLE
Unsound to drop substitution when simplifying rules

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/haskell-backend#1369]
We're dropping this substitution when simplifying rules:
https://github.com/kframework/kore/blob/c32cb34e5da799e8b3218d7037bee47b1783b73e/kore/src/Kore/Step/Simplification/Rule.hs#L88

This is unsound, because the variables have implicit universal quantifiers. It currently sort of works because the substitution usually contains variables which were intended to be existential (although they are not).

**Comment by yzhang90** [comment]
Give you give some examples?

**Comment by virgil-serbanuta** [comment]
Ok, I just realized that it's just bad to drop the substitution, it's not necessarily unsound right now, but it has the potential of being unsound.

Anyway, here's the example:

Let's take this axiom, which looks similar to the ones containing `#as`:
```
f(x and g(y)) = h(x, y)
```
which simplifies to
```
f(g(y)) = h(g(y), y) and [x=g(y)]
```
and we drop `[x=C(y)]`.

We can split this into two axioms, `f(g(y)) = h(g(y), y)` and `x=g(y)`.

Assuming that the sort for `f`'s argument has more than one value, then `x=g(y)` is, obviously, `bottom`, which we should know, because we are working in a broken axiom system.

If the sort of `f`'s argument has one value, then this axiom tells us that `g` is a functional symbol, which may be ok to forget. 

However, in order to solve the `bottom` issue above, we will probably have existential quantifiers on top of axioms. If that's the case, then we can't just split `f(g(y)) = h(g(y), y) and [x=g(y)]` in two as above, and the `x=g(y)` part may provide useful information constraining y.

**Comment by xc93** [comment]
Just to point out that these two are not logically equivalent as axioms or patterns:
```
(A) f(x and g(y)) = h(x, y)
(B) f(g(y)) = h(g(y), y) and [x=g(y)]
```

I'll explain the reason intuitively. Do a case analysis on whether `x = g(y)`. If it is, they are equivalent. If not, they are not, because `(A)` becomes `f(bottom) = h(x,y)`, i.e., `bottom = h(x,y)`; and `(B)` becomes `bottom`. They are not equivalent.

**Comment by virgil-serbanuta** [comment]
Oops, you're right, I skipped a step when doing the transformation. `f(x and g(y)) = h(x, y)` is the same as
```
(f(g(y)) = h(g(y), y) and [x=g(y)])
or
(h(x, y)=bottom and not (x=g(y)))
```
right?
Still bad, but not `bottom`...

**Comment by ana-pantilie** [comment]
Should we still simplify semantic rules at start-up?

**Comment by ana-pantilie** [comment]
This code does not exist anymore, and it's also not relevant to equational rules (this is an observation regarding the example in the comment above).
