### ISSUE TITLE
Interface for testing proofs

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1377]
It would be nice to have an interface (Haskell API) for writing proof scripts as a form of unit tests for the prover. The interface should make it easy for an engineer to load a definition and a specification, select a proof goal, find and apply rewrite rules and claims, instantiate equality axioms, and substitute subexpressions. The API should look something like this, where I'm embedding all operations in a hypothetical `K` monad that tracks state as necessary and reports errors:

```.hs
runK :: FilePath {- vdefinition.kore -} -> K a -> IO a

loadDefn :: ModuleName -> K ()
loadSpec :: ModuleName -> K ()

nextGoal :: K ()
previousGoal :: K ()
thisGoal :: K Goal

lookupRewriteRule :: RuleName -> K RewriteRule
lookupClaim :: ClaimName -> K Claim

applyRewriteRule :: RewriteRule -> K ()
applyClaim :: Claim -> K ()

 -- QuasiQuotes bracket for parsing and verifying expressions
[termLike| ... |] :: String -> K TermLike

substitute :: TermLike -> TermLike -> K ()

lookupEqualityRule :: RuleName -> K EqualityRule
instantiateEqualityAt :: EqualityRule -> TermLike -> K TermLike
```

This is a sketch to illustrate the level of detail and style of interaction. I'm sure the eventual interface will vary.

**Comment by ana-pantilie** [comment]
Kore-rpc server should make this possible.
