### ISSUE TITLE
Property test failure on master - Quantifying both the term and the predicate

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/haskell-backend#1467]
✗ simplify returns simplified pattern failed at test/Test/SMT.hs:31:24
                  after 51 tests and 1 discard.
                
                     ┏━━ test/Test/SMT.hs ━━━
                  25 ┃ testPropertyWithSolver
                  26 ┃     :: GHC.HasCallStack
                  27 ┃     => String
                  28 ┃     -> PropertyT SMT ()
                  29 ┃     -> TestTree
                  30 ┃ testPropertyWithSolver str =
                  31 ┃     testProperty str . Hedgehog.property . Morph.hoist runSMT
                     ┃     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     ┃     │ ━━━ Exception (ErrorCall) ━━━
                     ┃     │ Quantifying both the term and the predicate probably means that there's
                     ┃     │ an error somewhere else.
                     ┃     │ variable=rCS:mapSort{}
                     ┃     │ patt=\and{mapSort{}}(
                     ┃     │     /* term: */
                     ┃     │     \rewrites{mapSort{}}(rCS:mapSort{}, \top{mapSort{}}()),
                     ┃     │ \and{mapSort{}}(
                     ┃     │     /* predicate: */
                     ┃     │     \equals{mapSort{}, mapSort{}}(rCS:mapSort{}, \top{mapSort{}}()),
                     ┃     │     /* substitution: */
                     ┃     │     \top{mapSort{}}()
                     ┃     │ ))
                     ┃     │ 
                     ┃     │ CallStack (from HasCallStack):
                     ┃     │   error, called at src/Kore/Step/Simplification/Exists.hs:413:6 in kore-0.0.1.0-B78NrLybCib9ax0S0rtwdq:Kore.Step.Simplification.Exists
                
                  This failure can be reproduced by running:
                  > recheck (Size 51) (Seed 6446712546662283920 11559944655714824159) simplify returns simplified pattern
                
              Use '--hedgehog-replay "Size 51 Seed 6446712546662283920 11559944655714824159"' to reproduce.

**Comment by ana-pantilie** [comment]
Re-open if this appears again.
