### ISSUE TITLE
Compute function call graph and memoize non-recursive functions

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/haskell-backend#1522]
Following @virgil-serbanuta's issue https://github.com/kframework/kore/issues/1520, I did some experiment:
To run 10 steps,
without `memo` attribute added to `#computeValidJumpDest`, the runtime is 2m9s.
After adding the `memo` attribute, the runtime goes down to 59s.

There seems a regression on enabling caching for all functions of constructor-like arguments.

**Comment by virgil-serbanuta** [comment]
We test for the memo attribute here:
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Function/Evaluator.hs#L146

**Comment by virgil-serbanuta** [comment]
Enabling memo for all symbols seems to make things much slower. Current guess: `asConcrete (Pattern.term result)` is slow.
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Function/Evaluator.hs#L162

**Comment by ttuegel** [comment]
I guess that we shouldn't enable the cache by default for recursive functions, as this will fill the cache with lots of entries that will never be retrieved because we cached the initial entry point.

**Comment by virgil-serbanuta** [comment]
When we have a recursive function like `computeValidJumpDest`, do we usually split it into a recursive function and a non-recursive function that calls the recursive one?

**Comment by ttuegel** [comment]
> When we have a recursive function like `computeValidJumpDest`, do we usually split it into a recursive function and a non-recursive function that calls the recursive one?

Some of the performance-sensitive ones have been split that way (worker-wrapper transform) so that they are tail-recursive with the LLVM backend. From past experience, I know that trying to memoize the inner loops of these functions does slow the Haskell backend down. I don't know if that's all that is going on here, but it certainly isn't helping.

**Comment by ttuegel** [comment]
We should try enabling concrete caching by default for functions that aren't recursive. We can decide which functions are recursive by looking at the rules when registering the evaluator.
