### ISSUE TITLE
Static call graph analysis

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1550]
It would might be useful for caching function calls to statically analyze the function call graph for identifying recursive functions. Usually, we do not want to cache recursive function calls. This analysis should be straightforward with `fgl`.

See also: #1522

**Comment by ttuegel** [comment]
Even if a function is recursive, there will be an "initial" call which isn't re-entrant. From that point, we may also safely cache the function. With the static call graph in hand, we can do a worker-wrapper transformation on-the-fly!

**Comment by ana-pantilie** [comment]
If profiles indicate this is a problem we'll open a new issue about this.
