### ISSUE TITLE
Warn when a branch is undefined

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1627]
See also: https://github.com/kframework/kore/issues/1614#issuecomment-593153133

> Reached bottom means that the proof succeeded on the current branch, i.e. if the previous configuration was This and the proof goal is Goal, then This → Goal holds. The backend checks this implication by checking the (un)satisfiability of ¬(This → Goal) = This ∧ ¬ Goal. It is possible that this pattern is unsatisfiable because This = \bottom, but usually it's just that the implication was proved on a branch. The backend doesn't really distinguish the two conditions, though, and we could do a better job of reporting that. kprove doesn't really allow us to return multiple patterns through the frontend, but would it be sufficient to report a warning when the current configuration itself reached \bottom? As you pointed out, that shouldn't happen.

**Comment by ttuegel** [comment]
Related to this issue: we should ensure that the right-hand side of each applied rule is defined.

**Comment by ana-pantilie** [comment]
We need to see if we're doing this or not.
