### ISSUE TITLE
Break up the code into smaller packages

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1734]
Breaking up the code into smaller packages will improve development time by reducing re-compilation. (Recall that GHC supports incremental re-compilation, but Stack will periodically reconfigure the target package, which invalidates the cache.) The code was once divided into two packages, but that division was rather arbitrary and there was a duplication between packages; for example, they did not use the same syntax tree type. Also, after the packages were combined, it was revealed that one package was mostly vestigial, anyway. The goal, therefore, is to divide the packages in a way that is _not_ arbitrary.

Proposal:

- `kore-base`, containing `Prelude.Kore` and the other utility modules that support the implementation, but aren't really related to the Kore language.
- `kore-syntax`, containing `Kore.Syntax`, `Kore.Parser`, and `Kore.Unparser`.
- `kore`, containing the remainder.

**Comment by ana-pantilie** [comment]
We need to work towards this. The code isn't mature enough to do this right now, we need to do multiple refactorings to facilitate such a change.
