### ISSUE TITLE
kore-repl ignores printing commands in input script

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#1824]
Currently I'm working on a proof using the kore-repl, here is an example (`kompile --backend haskell repl-example.k --main-module REPL-EXAMPLE --syntax-module REPL-EXAMPLE`):

```k
require "domains.k" 
 
module REPL-EXAMPLE 
    imports BOOL 
 
    configuration <k> $PGM:Pgm </k> 
 
    syntax Pgm ::= "a" | "b" | "c" 
 // ------------------------------ 
    rule <k> a => b ... </k> 
    rule <k> b => c ... </k> 
endmodule 
```

And the proof file `repl-example-spec.k`:

```k
requires "repl-example.k"

module REPL-EXAMPLE-SPEC
    imports REPL-EXAMPLE

    rule <k> a => c ... </k>
endmodule
```

I have the following repl script `repl-script`:

```
alias konfig     = config   | kast -i kore -o pretty /dev/stdin

stepf 1
konfig
```

And I run with:

```sh
kprove repl-example-spec.k --def-module REPL-EXAMPLE --haskell-backend-command "kore-repl --repl-script repl-script"
```

Which produces the following output:

```
Welcome to the Kore Repl! Use 'help' to get started.

Kore (1)>
```

Then if I manually type `konfig`, I get:

```
Welcome to the Kore Repl! Use 'help' to get started.

Kore (1)> konfig
Config at node 1 is:
<k>
  b ~> DotVar1
</k>
Kore (1)>
```

I would expect the repl to automatically do the `konfig` for me, because it's in the repl script that I load. Note that it _is_ doing the `stepf 1` command for me automatically at load time

I guess this means that the repl script needs to be read line-by-line _after_ the repl is initialized, rather than loaded before the repl is run?

The output I would expect would be more like this:

```
Welcome to the Kore Repl! Use 'help' to get started.

Kore (0)> alias konfig     = config   | kast -i kore -o pretty /dev/stdin
Kore (0)> stepf 1
Kore (1)> konfig
Config at node 1 is:
<k>
  b ~> DotVar1
</k>
Kore (1)>
```

**Comment by ana-pantilie** [comment]
Add a flag for this.

**Comment by ana-pantilie** [comment]
Kore-repl is a separate executable which allows one to interactively run a proof. This is the main file: https://github.com/runtimeverification/haskell-backend/blob/master/kore/app/repl/Main.hs

When run like `kprove repl-example-spec.k --def-module REPL-EXAMPLE --haskell-backend-command "kore-repl --repl-script repl-script"`, it will non-interactively load and run the script `repl-script`, and I believe it ignores any commands which don't modify state (`config` only outputs the current configuration) commands.

We'd like to add a flag to allow these stateless commands to be recorded, and also to record their output.

Relevant modules: https://github.com/runtimeverification/haskell-backend/tree/master/kore/src/Kore/Repl
