### ISSUE TITLE
Iteractive prover

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1828]
## Background

Kore provides two proving tools:

- `kore-exec --prove`, a non-interactive prover, and
- `kore-repl`, an interactive debugger for the non-interactive prover.

Despite the name, `kore-repl` is not an interactive prover _or_ a REPL. Nevertheless, in a testament to human ingenuity, many users have employed it as an awkward interactive prover.

## Goals

We will provide an interactive prover with the following capabilities:

- **Interactive**: The user will interactively step through a proof or ordinary execution. The user will not be bound to any particular proof strategy, and indeed the tool may not initially provide any strategy.
- **Dynamic**: The user may load or reload definitions, specifications, and programs at any time, without losing their place.
- **Persistent**: The user's place is always saved to disk so that they can stop and resume at any time. The user's workspace will be stored in such a way (SQLite?) that it can be transferred to any other machine. Persistence-to-disk enables working with proofs larger than available memory.

The tool will take K or Kore files as input and print expressions in the user's preferred format. Unlike `kore-repl`, printing K expressions will not require extra setup by the user. Therefore, the tool will not be called by `kprove`, but the user will invoke the tool directly.

**Comment by ehildenb** [comment]
I think the tool should still be run with `kprove --debugger` so that we are going through the same frontend that users are used to, but if it's not possible then it's OK.

But you will definitely need a K frontend around to handle pretty-printing and parsing and such, so I don't think it makes sense to have the `kore-interactive-debugger` depend on `K frontend`, which then depends on `kore`.

**Comment by ttuegel** [comment]
This thread is not about the interactive debugger. `kore-repl` is the interactive debugger. If we make an interactive prover, we should probably rename that tool. For clarity, let's say the interactive debugger is `kprove --debugger` and the interactive prover is `kprove --interactive`. There is no way to implement these tools without inverting the runtime dependency between the Kore tools and the K frontend. That doesn't mean we need to change the order of build dependencies: this repository will continue to be a submodule of the frontend repository. But, if using the Haskell backend, at runtime `kprove` should fork, `exec` the backend with the original command line, and exit. Neither the interactive debugger or the (hypothetical) interactive prover can do their job as a child process or without the original command line arguments.
