### ISSUE TITLE
Move function-like rule check to verification

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1874]
The [check](https://github.com/kframework/kore/blob/c160ec57e3c9c1c371493452f493f3323a7bf38c/kore/src/Kore/Step/Step.hs#L201) for function-like rewrite rules should be moved into the verification step so that we can provide source locations.

**Comment by ana-pantilie** [comment]
The new location of the function: https://github.com/runtimeverification/haskell-backend/blob/a9ba15843df8c8ea46437dd264294b88a3a3fb52/kore/src/Kore/Rewrite/Step.hs#L237
