### ISSUE TITLE
Validate predicate simplification rules

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1906]
The backend should validate that predicate simplification rules (`\ceil(_) => ...`) have a predicate on the right-hand side. The related internal errors during execution may be removed.

**Comment by ana-pantilie** [comment]
We'd want to generalise the Equation type, it would look something like:

```
Equation patternType =
Equation
{ left :: patternType
, right :: patternType
...
}
```

This is also related to https://github.com/runtimeverification/haskell-backend/issues/2640
