### ISSUE TITLE
Synthetic attribute instances should not allocate

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1963]
The instances for synthetic attributes should not allocate, whenever possible. In particular, this requires:

- [x] Do not derive `Synthetic` instances through `Generic`.
- [ ] Use constant values instead of constructors.

**Comment by ana-pantilie** [comment]
@jberthold do you think this is still relevant?

**Comment by jberthold** [comment]
IIUC the proposed second change is to replace all constructed `Attribute.Something { isSomething :: Bool }` by (pre-allocated) constants `itIsSomething = Attribute.Something True` or `isNotSomthing = Attribute.Something False`.
Neat idea, but not sure about the actual impact.
_If we have time_ we can try it (for all wrapped booleans, of which we seem to have many).
