### ISSUE TITLE
Backend does not implement `--boundary-cells`

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/haskell-backend#2116]
Bug report: 
[kwasm-bug-simple-arithmetic-spec.k.tar.gz](https://github.com/kframework/kore/files/5162021/kwasm-bug-simple-arithmetic-spec.k.tar.gz)

The command:
```
./kwasm prove  --backend haskell tests/proofs/simple-arithmetic-spec.k KWASM-LEMMAS --format-failures --boundary-cells=instrs --bug-report
```

The failing claim:
```
    rule <instrs> ITYPE:IValType . const X:Int ~>  ITYPE . const Y:Int  => . ... </instrs>
         <valstack> S:ValStack => < ITYPE > Y : < ITYPE > X : S </valstack>
      requires #inUnsignedRange(ITYPE, X)
       andBool #inUnsignedRange(ITYPE, Y)
```

The commit on which this was tested:
https://github.com/kframework/wasm-semantics/tree/coinductive-dotvar-expansion

It seems the cause is that among the issues is that the claim immediately uses itself expanding the `DotVar` on the `<instrs>` cell. It also expands the `DotVar`  to other things, like arbitrary instructions, from all I can gather:
```
#And
  {
    _DotVar2
  #Equals
    i32 . const Y0:Int ~> memory.grow ~> _DotVar5 ~> .
  }
```

This is not really unsound, but it is problematic. I would like it if I could specify specifically that the `DotVar` should never be expanded. I was under the impression that `--boundary-cells` should do this, but it isn't.

**Comment by ttuegel** [comment]
The backend doesn't support `--boundary-cells` because there is no concept of a "cell" in Kore. The backend will halt execution when the configurations on the left- and right-hand sides of the current claim unify, which suffices to detect many errors of this kind. We could discuss implementing something like `--boundary-cells` with frontend support.
