### ISSUE TITLE
Synchronize claim simplification code

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2144]
Claims are simplified separately in `Kore.Step.Simplification.Rule` and `Kore.Strategies.Goal`. The code in these places should be synchronized.

**Comment by ana-pantilie** [comment]
Is this blocked on https://github.com/runtimeverification/haskell-backend/issues/2184?

**Comment by ana-pantilie** [comment]
There's practically the same code in https://github.com/runtimeverification/haskell-backend/blob/2b8b29ae57458aba49429d650ca94d70cc109b76/kore/src/Kore/Reachability/Claim.hs#L898 and https://github.com/runtimeverification/haskell-backend/blob/2b8b29ae57458aba49429d650ca94d70cc109b76/kore/src/Kore/Rewrite/Rule/Simplify.hs#L123. Also, https://github.com/runtimeverification/haskell-backend/blob/2b8b29ae57458aba49429d650ca94d70cc109b76/kore/src/Kore/Rewrite/Rule/Simplify.hs#L153 should be removed.
