### ISSUE TITLE
Fix the names of symbol and pattern attributes

### ISSUE THREAD

**Issue by MirceaS** [runtimeverification/haskell-backend#2182]
We have to be more specific about the exact definition of the terms `symbol`, `pattern attributes` and `function` because the Frontend definitions vary in subtle ways.
This should be reflected in the code and documentation in order to avoid confusion.

**Comment by ttuegel** [comment]
There are three symbol attributes we care about here:

- `constructor`
- `single-valued` symbol (`function` symbol)
- `reducible` symbol (not in normal form)

In the frontend, `function` means `single-valued` _and_ `reducible`, but not in logic/set theory.

There are also irreducible constructor-like symbols:

- overloaded constructors (`inj` is a special case)
- constructors modulo assoc-comm-unit-nil (`concatMap`, `concatSet`, `concatList`).

**Comment by ttuegel** [comment]
I had a [conversation](https://runtimeverification.slack.com/archives/CMU9WTWTW/p1603295861033800) with @sskeirik yesterday where he reminded me that in logic terminology, "constructors" are divided into two classes:

- free constructors, what functional programmers call just "constructors" and what the we give the `constructor` attribute, and
- non-free constructors, constructor symbols modulo axioms like associativity, commutativity, etc., which we call "constructor-like".

I think it would help us to standardize our terminology this way.

**Comment by ana-pantilie** [comment]
We have a document which defines common terms we use in K: https://github.com/runtimeverification/haskell-backend/blob/master/docs/glossary.md

We should improve the document by:
1. mentioning attribute names used in K
2. adding a comment that `function-like = partial function` and `functional = total function`
3. add a comment that in the Haskell backend code we have a type which represents a "structured" pattern, called `Conditional` (`Pattern` is the type alias), it's essentially a tuple containing a `term`, a `predicate` and a `substitution`
4. define more precisely what `term` is, as opposed to a `pattern`
5. any other attributes/concepts which need to be documented?
