### ISSUE TITLE
Performance regression in KEVM proofs

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#2229]
[kevm-slow.tar.gz](https://github.com/kframework/kore/files/5452889/kevm-slow.tar.gz)

The submitted proof still passes, but it runs 4X slower roughly than it did prior to the function-encoding updates.

I'll look at the kore-repl output here and see if some lemmas I expect to be applying are not, but I think it's likely a good idea to also profile the backend in more detail on it as well.

**Comment by ehildenb** [comment]
I ran this proof through the repl, and found that there was not a "slow" step (where the proof noticeably slows down at some particular step), which leads me to believe this is a uniform slowdown through execution (and so will benefit more from profiling the backend than from adjusting the semantics/lemmas).

**Comment by ttuegel** [comment]
@andreiburdusa There are instructions for running Haskell profiling on the backend: https://github.com/kframework/kore/wiki/Profiling#haskell-profiling

**Comment by andreiburdusa** [comment]
Here is the html report generated with `profiteur`
[kore-exec-prof-html.zip](https://github.com/kframework/kore/files/5582686/kore-exec-prof-html.zip)

**Comment by ttuegel** [comment]
## Inverted call stack

Lifting `prove` out of `runSMT` indicates a laziness issue:

- `execute.withZ3`
  - `runSMT`
    - `generalBracket`
      - `runSMT.\`
        - `runSMT'`
          - `*>`
            - `prove`
  - `prove`

Lifting `simplifyTermLike` out of `evalSimplifier` indicates a laziness issue.

I don't think that these laziness issues, even taken together, cause the problem we see here, but it's good to make note of them.

## Cost centers

`initializeProver` accounts for 41% of runtime; this should be very fast.

- `simplify`
  - `observeAllT`
    - `>>=`
      - `>>=.\`
        - `substitutionSimplifier.wrapper.worker`
          - `makeAndEvaluateApplications`
        - `foldr` (very suspicious)
          - ...
            - `makeAndEvaluateApplications` (very suspicious that this appears on both sides of the call stack)
        - ...

**Comment by ttuegel** [comment]
As far as I can tell right now, this is a manifestation of #2120.
