### ISSUE TITLE
Audit uses of simplifyCondition

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2400]
I am auditing the uses of `simplifyCondition` to identify places where it might be used inappropriately.

- `Kore.Step.Simplification.Simplify`: OK, class defined here.
- `Kore.Step.Simplification.Condition`: OK, implemented here.
- `Kore.Step.Simplification.Data`: OK, implementation hooked into instance here.
- `Kore.Builtin.KEqual`: called within unification, might not be OK.
- `Kore.Equation.Application`: OK, used to requirements of equations.
- `Kore.Step.Step`: OK, used to simplify requirements of rewrite rules.
- `Kore.Step.RewriteStep`: OK, used to simplify requirements of rewrite rules.
- `Kore.Step.Substitution`: used to implement `mergePredicatesAndSubstitutions`; should probably be deprecated.
- `Kore.Step.Function.Evaluator`: essentially used to reimplement the `Pattern` simplifier; should not be used here.
- `Kore.Step.Rule.Combine`: OK, used to simplify requirements of merged rules.
- `Kore.Step.Simplification.Exists`: not OK, should be rewritten so that re-simplifying child patterns is not required.
- `Kore.Step.Simplification.OrPattern`: not OK, should not be used multiple times here.
- `Kore.Step.Simplification.Pattern`: OK, used to implement the `Pattern` simplifier.
- `Kore.Step.Simplification.TermLike`: not OK, the `TermLike` simplifier should not need to simplify conditions.
- `Kore.Unification.Procedure`: OK, used to simplify the result of solving `\in`.
- `Kore.Unification.UnifierT`: OK, implementation hooked into instance here.
- `Kore.Unification.SubstitutionSimplifier`: OK, used to simplify the result of solving `\and`.

**Comment by ttuegel** [comment]
Because the condition simplifier is used inappropriately in the term simplifier, many uses of the latter should be changed to use the pattern simplifier.

**Comment by ttuegel** [comment]
1. [`simplifyTermLike`](https://github.com/kframework/kore/blob/caeff6481218760d8f4975b6465049bf90c21b25/kore/src/Kore/Step/Simplification/Simplify.hs#L148) should go away. We can replace it with a `simplifyPattern` method.
2. `Pattern.simplify` may call `TermLike.simplify` directly.
3. Most calls to `simplifyTermLike` should become `simplifyPattern` instead.
4. Move `Condition.simplifyPredicate` to its own module and implement a `Predicate.simplify` similar to `TermLike.simplify`. It must not call `simplifyCondition`.
5. `TermLike.simplify` must also not call `simplifyCondition`.

**Comment by ttuegel** [comment]
Even after we remove `simplifyTermLike`, we will have to modify the particular simplifiers it delegates to, so that they return unsimplified predicates. All predicate simplification should be handled in the outer `Pattern` simplification loop.

**Comment by ana-pantilie** [comment]
Multiple term/predicate simplifiers call `simplifyCondition` in a less obvious way: they call `Simplify.makeEvaluateTermCeil` and `Simplify.makeEvaluateCeil` which actually call `simplifyCondition`, instead of the direct `Ceil` simplifier. I don't think this is ok, the loops in the term and condition simplifiers should be explicit and visible at the top.
