### ISSUE TITLE
Simplify simple integer formulas

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2430]
It would be useful if the backend could simplify these simple integer formulas:

```
X +Int A = X +Int B => A = B
X        = X +Int B => 0 = B
```

**Comment by ttuegel** [comment]
In general, it would be very useful if we had an internal representation for `+Int` that holds the concrete part and symbolic part separately, and that uses a `HashSet` to remove common terms during unification.

**Comment by ana-pantilie** [comment]
Switching to having user-defined simplification rules instead.
