### ISSUE TITLE
Measure performance of rule merger

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2482]
Use the current hacked rule-merger for KEVM/Firefly to compile merged rules into the semantics used for verifying the KEVM proof regression test-suite. Measure the performance impact for verification using different strategies and tunings of the rule merger (which currently has a few knobs which control how it decides which rules to merge). The results will determine whether it’s worth pursuing this effort further.

**Comment by ehildenb** [comment]
The rule merger is gone now.
