### ISSUE TITLE
Remove or document NoStrict modules

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2544]
We should remove `NoStrict` and `NoStrictData` from the modules where they appear because the need for these extensions may indicate a thunk leak. Where it does not indicate a problem, we should document the need for these extensions.

Follow up to #2491.

---

- [ ] `Kore.Attribute.Pattern.Simplified`
- [ ] `Kore.Internal.SideCondition.SideCondition`
- [ ] `Log.Entry`

**Comment by ana-pantilie** [comment]
The first two should be obsolete after https://github.com/kframework/kore/issues/2729.

**Comment by ana-pantilie** [comment]
@RaoulSchaffranek investigated making the `Log.Entry` module strict and it resulted in multiple tests having segmentation faults.
