### ISSUE TITLE
Investigate why we need to do matching in both directions

### ISSUE THREAD

**Issue by MirceaS** [runtimeverification/haskell-backend#2545]
At [this location](https://github.com/kframework/kore/blob/e0614507f2172e8d161fa8e8eddd844dba724eae/kore/src/Kore/Step/Simplification/Exists.hs#L251) we do matching in both ways, but this shouldn't be necessary if the input predicate is simplified.

**Comment by ana-pantilie** [comment]
Related to https://github.com/runtimeverification/haskell-backend/issues/2511
