### ISSUE TITLE
Remove Kore.Internal.OrPattern.toPattern

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2610]
The function `toPattern` should not exist. Start by removing it from the tests, then from `kore-repl`, and finally remove it from the main library. This is necessary for #2152.

**Comment by ttuegel** [comment]
Part of this will be completed in #2623 and part in #2570. The remaining part is to remove it from `Kore.Step.Simplification.Iff`. When there are multiple children under `\iff(_, _)`, we should expand it to `\and(\implies(_, _), \implies(_, _))`. The simplifiers for `\and` and `\implies` don't use `toPattern`, so this will take care of it.

**Comment by ana-pantilie** [comment]
@andreiburdusa points out that this is still used in the [equals simplifier](https://github.com/kframework/kore/blob/78ec7647e9b9eca9045544fe4a8c6c1fead93587/kore/src/Kore/Simplify/Equals.hs#L209) and the [floor simplifier](https://github.com/kframework/kore/blob/78ec7647e9b9eca9045544fe4a8c6c1fead93587/kore/src/Kore/Simplify/Floor.hs#L69).

**Comment by ana-pantilie** [comment]
(t1 /\ p1 /\ s1) \/ (t2 /\ p2 /\ s2) \/ (t3 /\ p3 /\ s3)
= (T /\ P /\ S)

T = ?
P = ?
S = ?

-----------

Only relevant for #Equals simplifier, because we don't actually use #Floor simplification in practice.

Other question: how do #Or and #Equals interact in ML?

**Comment by virgil-serbanuta** [comment]
I don't think that `T` can be a term, or, to be specific, I didn't figure out how to transform `1 or 2 or 3` to `T and P and S` where T is a term, P is a predicate and S is a substitution.

I don't know if `T = 1 or 2 or 3` may resemble a term well enough to be acceptable, but if it does, how about this for the general case?

`T = ((p1 and s1) implies t1) or ((p2 and s2) implies t2) or ((p3 and s3) implies t3)`
`P = (p1 and s1) or (p2 and s2) or (p3 and s3)`
`S = Top`

**Comment by ana-pantilie** [comment]
We can call `toPatterns` and match on whether there are multiple patterns or not at the call site. I'd like to run an experiment which tests whether we actually have multiple patterns in practice.

**Comment by ana-pantilie** [comment]
Thank you @virgil-serbanuta, you're probably right about that in theory, but it's not what we're looking for in practice. We might not actually need that much generality so I'm suggesting we do ^ to assess the situation.
