### ISSUE TITLE
Slow proof on Haskell backend

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#2669]
The attached proof takes 56s on the Java backend, but 4000s on the Haskell backend.

Can we get a profile of it to see what the bottleneck is? I suspect that the builtin Bytes type by the Haskell backend is really inefficient, given that this proof manipulates bytes directly and we know that `computeValidJumpDests` (another bytes manipulation algorithm) is also slow.

[kevm-bug-bytes00.tar.gz](https://github.com/kframework/kore/files/6632666/kevm-bug-bytes00.tar.gz)

This is on Kore commit: 4eb97338f

**Comment by JKTKops** [comment]
The proof takes 321 steps, so at Everett's recommendation I started looking at --depth 100.

A profile of the first 100 steps doesn't looks suspicious (there's no long calls to any particular functions deeper than `Log.>>=`) and it takes ~8 minutes which seems... slightly high (assuming 4x profiling overhead), but not necessarily unreasonable.

I'm currently logging --depth 150 and it's at >30m (edit: it just finished) so the issue manifests somewhere in these 50 steps. However I'm worried that this eventlog will be too big for hs-speedscope... do we have `traceEvents` that I could use to limit the size?

**Comment by ttuegel** [comment]
> assuming 4x profiling overhead

That assumption is low; I would assume at least 6x overhead, and probably more like 10x.

> it seems like 85% of runtime was spent under `Kore.Step.Simplification.Data simplifyTermLike`

Unfortunately, this isn't an interesting result: it only means that the backend spends most of its time simplifying patterns, which is expected.
