### ISSUE TITLE
Investigate optimisations related to Z3 usage

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2705]
### New description
Whoever picks up this issue should:

- [ ] measure if time spent in Z3 interaction/parsing/unparsing is relevant
- [ ] audit Z3 interaction code
- [ ] research alternatives and report

Relevant code:

https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/SMT.hs
https://github.com/runtimeverification/haskell-backend/tree/master/kore/src/SMT
https://github.com/runtimeverification/haskell-backend/tree/master/kore/src/Kore/Rewrite/SMT

### OUTDATED
To improve the stability of Z3 queries, we could send each query to a "fresh" solver, instead of using `push` and `pop`. We would keep a pool of multiple Z3 processes open. At start-up, we would initialize all of them. Whenever we need to make a query, we would pick a solver from the pool and send the query. After we receive the result, we start a _new thread_ to re-initialize the solver (using `reset`) and return it to the pool. That way, the pool is always filled with Z3 processes that are ready to receive queries, and each new query is sent to a solver with a clean slate. It would be more complicated to generate the solver transcript, but this is not an insurmountable difficulty. The benefit is a faster, more stable query interface.

**Comment by ana-pantilie** [comment]
How long does it take to `reset`?

@jberthold: As long as the backend is single-threaded, we would only need 2 Z3 processes.

@goodlyrottenapple: Maybe it would be better if we'd try to optimize the interface between the backend and the SMT solver. Maybe use C bindings? We need to actually measure where time is really being spent.

**Comment by ana-pantilie** [comment]
From another issue:
ttuegel
3 years ago

When the solver finds a formula satisfiable, we log the model by default. However, parsing the model takes some time. Having an option to disable this feature would improve performance by a few percent.

**Comment by alexd1971** [comment]
Communication with z3 is performed in `SMT.SimpleSMT` `command` function. I looked at profiling results in master branch which I did for two tests and I see that this communication takes little time.

**dstoken-burn-self-fail-rough**:
```
 3.0     -     -  SMT.SimpleSMT command (3359461)
 1.2     -     -    SMT.SimpleSMT recv (2288942)
 1.2     -     -    SMT.SimpleSMT send (2282766)
  .5     -     -    Kore.Debug traceNonErrorMonad (2285629)
  .5     -     -      Kore.Debug traceWhenEnabled (1068832)
```
**cat-file-addr-pass-rough**:
```
  .7     -     -  SMT.SimpleSMT command (120770)
  .3     -     -    SMT.SimpleSMT recv (81257)
  .3     -     -    SMT.SimpleSMT send (80236)
  .1     -     -    Kore.Debug traceNonErrorMonad (41562)
  .1     -     -      Kore.Debug traceWhenEnabled (39030)
```
Spawning new z3-process doesn't take a lot of time as well.

Regarding parsing/unparsing I figured out that it quite straightforward. The type SExpr is just wrapper over a text command representation. Parsing and unparsing is a part of send and recv  functions which in turn are parts of command function. Hence we can conclude that parsing and unparsing are very cheap.

Regarding `decidePredicate` and `translatePredicate` functions we have the following profiling results:

**dstoken-burn-self-fail-rough**:
```
12.6     -     -      Kore.Rewrite.SMT.Evaluator decidePredicate (140108)
 7.7     -     -        SMT withSolver (402533)
 4.0     -     -        Kore.Rewrite.SMT.Evaluator translatePredicate (264616)
  .8     -     -        Kore.Log.DebugEvaluateCondition whileDebugEvaluateCondition (139836)
  .8     -     -          Kore.Simplify.Simplify logWhile (139836)
   -     -     -        Kore.Rewrite.SMT.Translate evalTranslator (140108)
   -     -     -        Kore.Log.DebugEvaluateCondition debugEvaluateConditionResult (138819)
   -     -     -        SMT liftSMT (0)
   -     -     -        Kore.Rewrite.SMT.Translate liftA2 (0)
   -     -     -        Kore.Rewrite.SMT.Translate >>= (265662)
   -     -     -        Kore.Simplify.Simplify askMetadataTools (0)
   -     -     -        Kore.Simplify.Simplify return (0)
   -     -     -        Kore.Rewrite.SMT.Translate hoist (118836)
   -     -     -        Control.Monad.Counter return (0)
   -     -     -        Kore.Rewrite.SMT.Translate pure (0)
   -     -     -        Control.Monad.Counter >>= (0)
   -     -     -        Log logEntry (0)
   -     -     -          Kore.Log koreLogTransformer (0)
 ```
**cat-file-addr-pass-rough**:
```
 2.5     -     -      Kore.Rewrite.SMT.Evaluator decidePredicate (5045)
 1.6     -     -        Kore.Log.DebugEvaluateCondition whileDebugEvaluateCondition (4934)
 1.6     -     -          Kore.Simplify.Simplify logWhile (4112)
  .7     -     -        Kore.Rewrite.SMT.Evaluator translatePredicate (5365)
  .1     -     -        SMT withSolver (7640)
   -     -     -        Kore.Rewrite.SMT.Translate evalTranslator (4934)
   -     -     -        SMT liftSMT (0)
   -     -     -        Kore.Log.DebugEvaluateCondition debugEvaluateConditionResult (4520)
   -     -     -        Kore.Rewrite.SMT.Translate liftA2 (0)
   -     -     -        Kore.Rewrite.SMT.Translate >>= (5497)
   -     -     -        Kore.Rewrite.SMT.Translate hoist (2693)
   -     -     -        Kore.Simplify.Simplify askMetadataTools (0)
   -     -     -        Control.Monad.Counter return (0)
   -     -     -        Control.Monad.Counter >>= (0)
   -     -     -        Kore.Simplify.Simplify return (0)
```
So we can see that contribution of single invocation of `decidePredicate` and `translatePredicate` functions is negligible. And overall contribution depends on amount of invocations.

Thus for further performance improvement we need to cut down the amount of invocations but it is not obvious how to do and is not relevant to this issue.
