### ISSUE TITLE
Steps towards removing Mu and Nu

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2707]
After merging #2702, we can replace the class `Binding` with instances of `Substitute` defined over `Exists`, `Forall`, etc. We can also define `Substitute` instances over the non-binding constructors in `Kore.Syntax` to simplify the `Substitute` instance of `TermLike`.

**Comment by ana-pantilie** [comment]
We don't actually use Mu and Nu, we should look into completely removing the Binding module. The next step would be to remove the Mu and Nu nodes in our internal AST representation of Kore patterns (TermLike).
