### ISSUE TITLE
Use Implication for all rules and claims

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2711]
We use [`Implication`](https://github.com/kframework/kore/blob/6a50966ea3f2c685f029ccdddb922fab208d02f0/kore/src/Kore/Step/Implication.hs#L96) for some types of claims, but it should be used for all claims and rules, replacing `ClaimPattern`, `RulePattern`, and the like.

This is especially important because (I think) the `Substitute` instances for `ClaimPattern` and `RulePattern` could capture variables. I don't think we actually use that instance in practice for those types in any way that matters, but we should get substitution right.

**Comment by ana-pantilie** [comment]
Looks like this is closely related to https://github.com/kframework/kore/issues/2192.
