### ISSUE TITLE
Kore.Builtin mixes concerns

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2716]
The module hierarchy under `Kore.Builtin` mixes concerns between validation, simplification, and unification. It would be best to separate these behaviors.

There is an argument to be made that, for each built-in type, these workflows belong together. But, I think that each of the workflows happens in a different context, and we should not mix or confuse them.

**Comment by ana-pantilie** [comment]
We might end up dealing with this in #3309, because we need to remove the old unification algorithm as part of our clean-up there.
