### ISSUE TITLE
Log command in REPL does not properly toggle settings

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/haskell-backend#2734]
The `log` command in `kore-repl` behaves unexpectedly:

- the logType field is required, meaning it must be specified every time you want to adjust which logs are printed
- the logEntries field is required, meaning you must repeat the logs you want printed every time you change a different setting (stderr or file? standard format or oneline? severity threshold...)
- the optional fields use a default value if one is not provided. For example, this means that if you do not specify a severity and the current setting is Info, it will be _reset_ to Warning. If you do not specify a timestamp setting, they will be enabled even if the current setting is disabled.

These issues could be fixed by (1) separating each component of the `log` command into its own command, e.g. `enable-log-timestamps` (2) creating a much more general `set-option` command, or (3) making `GeneralLogOptions` hold `Maybe` things, and modify `generalLogOptionTransformer` to only modify using the fields that are present.

Option (2) seems like overkill.

Personally, I think it makes sense for all of these controls to be part of the `log` command (keeping them all together). Option 1 would lead to having 5 separated but closely related commands floating around. In practice, I think it's easier to do
```
log stderr
log [DebugTransition]
log oneline
```
compared to
```
log-type stderr
log-entries [DebugTransition]
log-format oneline
```

This is just my opinion. I'm opening this issue so we can discuss before taking any action if any.

**Comment by ana-pantilie** [comment]
@JKTKops suggests we also rename `GeneralLogOptions`
