### ISSUE TITLE
Current AC matching algorithm is ad-hoc and incomplete

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2739]
Our current Map and Set matching algorithm is incomplete.

We should consider replacing the current way we do Map and Set matching with some traditional AC matching algorithm. This needs investigation as I don't know if implementing such an algorithm is compatible with our current representation of Maps and Sets, so this might end up to be a significant undertaking.

See https://runtimeverification.slack.com/archives/CC360GUTG/p1625220446338900

**Comment by ana-pantilie** [comment]
See also: https://runtimeverification.slack.com/archives/CTXRMGL58/p1625731908004900

**Comment by ana-pantilie** [comment]
See also: https://runtimeverification.slack.com/archives/CTXRMGL58/p1625754556006400

**Comment by ana-pantilie** [comment]
@jberthold please add what you found here.

**Comment by jberthold** [comment]
> We should consider replacing the current way we do Map and Set matching with some traditional AC matching algorithm

I consulted several papers about AC (and other non-free) matching algorithms, most prominently [Boudet(1993)[(https://link.springer.com/article/10.1007/BF00881905) (which is about _unification_, not matching) and [Eker(2003)](https://link.springer.com/chapter/10.1007/3-540-44881-0_3).
The techniques presented in these papers (based on diophantine equations) apply directly to ASTs with AC symbols (and other, free, symbols). In contrast, our [`NormalizedAC`](https://github.com/runtimeverification/haskell-backend/blob/ac1164589c6c8e2cadb308ca785c526f8d82b785/kore/src/Kore/Internal/NormalizedAc.hs) data holds information derived from an AC term, so the algorithms won't be applicable without substantial changes.
The question whether
> implementing such an algorithm is compatible with our current representation of Maps and Sets
already hinted in that direction.

The AC matching on `NormalizedAC` should still be refactored to cover more cases and be more maintainable but implementing an algorithm from literature would mean to _remove_ the derived normalised representation, which will touch many parts of the code.

**Comment by jberthold** [comment]
Another issue is that the AC matching algorithm in use picks one arbitrary match out of potentially many.
This is somewhat inherent to the use case: The matching code is used for simplifications and conceptually returns a single result. Some code fragments in the simplifier exists to cater for simplifications having multiple results (see [`runSimplifier` vs `runSimplifierBranch`](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Simplify/Simplify.hs#L165..L181)) but `runSimplifierBranch is _unused_, the simplification code currently _relies_ on obtaining a single result. 

One could try to discard results ASAP by way of relevant side conditions, but this still does not guarantee a single result.
We could modify the code to generally handle simplifications with potentially several results, maybe treating those like rewrites (i.e., proceed with several results in an `OrPattern`) but it would drastically widen the state space to explore and substantially change the code.
