### ISSUE TITLE
Axiom Not Used When Simplifying Side Condition

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/haskell-backend#2785]
When working on a proof in evm-semantics, we noticed this strange behavior around a `#hashedLocation` term that appears in a side condition. The requires clause for the appropriate rule can be inferred from the requires clause of the claim, but the term appears unsimplified in the configuration.

Here's a minimized version.
`test.k`:
```k
module TEST
  imports INT

  syntax Int ::= lookup(Hash) [function, no-evaluators]

  // We use this so that the proof takes a step
  syntax KItem ::= makeLookup(Int)
  rule makeLookup(B) => lookup(#hash(B))

  // -------------------------------------------
  syntax IntList ::= List{Int, ""}

  syntax Bool ::= #rangeUInt(Int) [function, no-evaluators]

  syntax Hash ::= #hash(Int)
                | #hashedLocation( IntList ) [function]

  rule #hashedLocation(       .IntList) => #hash(0)
  rule #hashedLocation(OFFSET .IntList) => #hash(OFFSET)
    requires #rangeUInt(OFFSET)

endmodule
```
`test-spec.k`:
```k
module TEST-SPEC
  imports TEST

  claim <k> makeLookup(B) => 1 ... </k>
    requires lookup(#hashedLocation(B .IntList)) ==Int 1
     andBool #rangeUInt(B)
endmodule
```

As long as the `#hashedLocation` in the `requires` clause of the claim is simplified to `#hash(B)`, the claim will become
```
claim <k> lookup(#hash(B)) => 1 ... </k>
  requires lookup(#hash(B)) ==Int 1
```
which obviously holds.

However, if we run the proof, we'll get a failing output:
```
$ versions
K commit b592f5d634d12da34c231b235aa66978f1798116
Kore commit 726faa4c269a70f0ad8d2045561beebb9350a829
$ kompile test.k --backend haskell
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
$ kprove test-spec.k --backend haskell
kore-exec: [479535] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid. Location: /home/max/scratch/evm-semantics/axiom-requires/test-spec.k:4:9-6:27
  #Ceil ( lookup ( #hash ( B ) ) )
#And
  #Not ( {
    1
  #Equals
    lookup ( #hash ( B ) )
  } )
#And
  <k>
    lookup ( #hash ( B ) ) ~> _DotVar1 ~> .
  </k>
#And
  {
    1
  #Equals
    lookup ( #hashedLocation ( B  .IntList ) )
  }
#And
  {
    true
  #Equals
    #rangeUInt ( B )
  }
```
Notice the unsimplified `#hashedLocation` in the 4th component of the MultiAnd.

Doing any of the following make the proof pass:
- deleting the first `#hashedLocation` rule, which isn't used in the claim
- marking the second `#hashedLocation` rule as `[simplification]`
- deleting the `requires` clause of the second `#hashedLocation` rule

My understanding is that none of these workarounds are acceptable in KEVM, so this is blocking at least one proof.

My first guess would be that we don't construct the evaluator correctly, but I'm not very familiar with that part of the code.

**Comment by calin1304** [comment]
I encountered this bug when working on `evm-semantics/tests/specs/mcd/flopper-cage-pass-spec.k`.

At `<pc>5842</pc>` there's a `JUMPI` for which the jump condition looks like:

```
    <k>
      JUMPI 5952 bool2Word ( #lookup ( ACCT_ID_STORAGE , keccak ( #buf ( 32 , CALLER_ID ) ++ b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ) ) ==Int 1 ) ~> #pc [ JUMPI ] ~> #execute ~> CONTINUATION ~> .
    </k>
```

and with the following side condition:

```
#And
  {
    1
  #Equals
    #lookup ( ACCT_ID_STORAGE , #hashedLocation ( "Solidity" , 0 , CALLER_ID  .IntList ) )
  }
```

The prover doesn't simplify the `JUMPI` condition so it starts going on both branches and on the one where the jump was not taken it gets stuck.

The tests passes after marking the second `#hashedLocation` rule with `[simplification]`.

**Comment by ana-pantilie** [comment]
This is blocked on https://github.com/kframework/kore/issues/2321. We need this to address the performance issue uncovered by our fix.
