### ISSUE TITLE
kore-repl: internalize commands from the K-printing kscript

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/haskell-backend#2797]
Motivation
----------

The basic  `kscript` that may be used for debugging is more or less standard between definitions.
It is inconvenient for users to create this for each definition. More importantly, new users would likely not be aware of this, and it increases the barriers to using K.

Example K Code
--------------

The K Front end should generate a  `kscript` based on the following template, and place it in the definition directory.
`krun` or `kprove` with the `--debugger` option should add the correct flags to the `kore-exec` invocation.

```
alias kclaim      = claim    | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias kclaim-n x  = claim x  | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias kaxiom x    = axiom x  | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias ktry x      = try x    | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias ktryf x     = tryf x   | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias krule       = rule     | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias krule-n x   = rule x   | kast -i kore -o pretty -d $definitiondir /dev/stdin
alias konfig      = config   | kprint $definitiondir /dev/stdin false
alias konfig-n x  = config x | kprint $definitiondir /dev/stdin false
alias kconfig     = konfig
alias kconfig-n x = konfig-n x
```

Possible Issues
----------------

One issue with the above template is that `$definitiondir` is an absolute path. This may hamper the ability to package the definition.
There are two possible workarounds for this:

1. Change `kore-exec` to interpret `kscript` relative to the script's path.
2. The frontend could export a variable `K_DEFINITION_DIR` that `kast` and `kprint` use.

Provide a small, complete, and self-contained example of what you would like to be able to say in K.
Try to make it so that your example would `kompile` correctly if this feature were implemented.

Testing Approach
----------------

1. An automated test that checks for the existance of the kscript.
2. A manual test where the user invokes `kprove --debugger`

**Comment by ana-pantilie** [comment]
@ehildenb `kore-repl` can't really automatically know the path to the definition directory, right?

**Comment by ana-pantilie** [comment]
> This is actually better, because it can use the generated temporary kompiled definition as the one used for pretty-printing/parsing in these commands.

Sorry, I misread this. So, my question above should actually be: is it possible to use `kast` with the `definition.kore` file?

**Comment by ehildenb** [comment]
No, but it's possible to use `kore-print` directly with some of the files in the `*-kompiled` directory, which is what we should focus on using.

We can see here: https://github.com/kframework/k/blob/master/k-distribution/src/main/scripts/bin/kore-print#L209

It needs `syntaxDefinition.kore`, so we can do:

- Make sure that with `kprove` this file is generated and copied into the temporary directory (it currently isn't).
- `kprovex` shouldn't need any change, because it invokes the Haskell backend on the actual `*-kompiled` directory to use, instead of generating a new one. So `syntaxDefinition.kore` should already be there (I've confirmed this).

So what I would do is have `kore-repl` look at the same directory that `definition.kore` is in, and if `syntaxDefinition.kore` is present, automatically generate the needed `alias konfig = config | kore-print --directory PATH/UP/TO/KOMPILED_DIR --output pretty /dev/stdin`

**Comment by ehildenb** [comment]
I want to re-emphasize that we should use `kore-print` instead of `kast`, because `kore-print` is much faster and simpler.

**Comment by ana-pantilie** [comment]
This needs https://github.com/kframework/kore/issues/2824 to be done first.

**Comment by ana-pantilie** [comment]
https://github.com/runtimeverification/haskell-backend/blob/5ed0f376a753eb2c6a1b5340c9ffbd4500cb3f54/kore/app/repl/Main.hs#L92 this will contain the path to the `definition.kore`. We need to also compute the path to the `-kompiled` directory (which should be one level above) and pass it to the inner repl (maybe add a field for it in https://github.com/runtimeverification/haskell-backend/blob/5ed0f376a753eb2c6a1b5340c9ffbd4500cb3f54/kore/src/Kore/Repl.hs#L214).

Next step would be to add a new repl command (see https://github.com/runtimeverification/haskell-backend/blob/5ed0f376a753eb2c6a1b5340c9ffbd4500cb3f54/kore/src/Kore/Repl/Interpreter.hs#L271) called `konfig` which extracts the configuration (similar to `config`) but also calls `kore-print`.
