### ISSUE TITLE
`Predicate.mapVariables` should have its own implementation

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2802]
We shouldn't transform to and from `TermLike` in [Predicate.mapVariables](https://github.com/kframework/kore/blob/5da531b27cce7d9a7160e0cf2a69399544a30c64/kore/src/Kore/Internal/Predicate.hs#L1221).

**Comment by ehildenb** [comment]
Do we know how much time this function `mapVariables` is taking in the first place on a normal profile? Is it a big cost-center?

**Comment by ana-pantilie** [comment]
New version doesn't show good performance, and since we don't want to modify `TermLike` anymore fixing this issue is no longer necessary.
