### ISSUE TITLE
Add --execute-to-branch option

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#2848]
Edit: disregard description below, see https://github.com/kframework/kore/issues/2848#issuecomment-940610272 and the next comment.

------------
Given an execution, I'd like to make it easy to log (states + path conditions):

- The entry points (initial states)
- The exist points (final states, proven or unproven)
- The branch points (state before branch, each state after branch)
- Enough information to reconstruct the branching graph from these log entries.

Maybe the infrastructure for this already exists, but I'd like to make it easy to do something like `--log-branch-points`, because this functionality can be used to easily summarize the control-flow of an existing program, and to construct lemmas of each basic-block of execution (so we can step through them more quickly the next execution).

**Comment by ana-pantilie** [comment]
Why not use `kore-repl` for this?

**Comment by ehildenb** [comment]
I want it to be done automatically (no interaction) so I can start a run overnight, and have the summaries in the morning.

**Comment by ehildenb** [comment]
But I guess I may be able to do it using a kscript...

**Comment by ehildenb** [comment]
I'm making a `pyk` script that automates this workflow, by hacking together a bunch of commands to `kprove`. Once I have a working prototype, we can discuss how the backend can make the solution I have a little cleaner.

**Comment by ana-pantilie** [comment]
I think we discussed about something similar, thanks for reminding me! We'll definitely take a look at this, I think it should be do-able.

**Comment by ana-pantilie** [comment]
Test first what happens with `--breadth-limit`.
