### ISSUE TITLE
Try to reproduce issue with looping unit tests

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2907]
When running `make test` inside `kore/kore` sometimes the unit tests take a very long time, it looks like they're looping. We should try to reproduce this locally and think about how we can debug this behavior.

**Comment by JKTKops** [comment]
I mentioned this issue in the training meeting today and Everett suggests we bump this one.

**Comment by ana-pantilie** [comment]
I don't think we've ever seen this in the integration tests, so my suspicion is that it's some property test which generates a weird enough pattern which the backend can't handle. I wouldn't bump the priority on this unless we start seeing this behavior in practice as well.
