### ISSUE TITLE
Investigate output file handling

### ISSUE THREAD

**Issue by dopamane** [runtimeverification/haskell-backend#2929]
@ehildenb asks [on slack](https://runtimeverification.slack.com/archives/CC360GUTG/p1638391345213700):

Hey guys! So I'm trying to debug what I think is an infinite loop in my K rules on a definition. To do this, I've stepped in the kore-repl to the point where I think this loop is happening, then turned on Equation logging:
```
log oneline [DebugAttemptEquation,DebugApplyEquation] file equations.log enable-log-timestamps
```
But the file `equations.log` was not being filled after I then did a `step`. So I figured I did something wrong, and `Ctrl-C` ed the process, then the file was populated! So I guess it doesn't flush the output to the file automatically, or doesn't write to the file incrementally? I guess this is difficult for debugging this loop that I'm looking at, because I'd like to watch the log grow dynamically to know that it's making progress/working, rather than having to wait a while, then only find out after doing `Ctrl-C` that nothing/something happened.

**Comment by ehildenb** [comment]
This can be reproduced by using this bug example: https://github.com/kframework/kore/issues/2928

And turning on the logging before taking the first step. Then wait a few minutes (log file does not populate), then Ctrl+C, then it will populate all at once. It would be nice to see incremental output, or at least have a way to turn it on.

**Comment by dopamane** [comment]
I am not able to open a repl for bug example #2928. It runs, but no REPL terminal output; CPU and Mem usage is high. 

Steps taken:
1. `wget` kore-exec.tar.gz from issue discussion
2. `tar -xvf kore-exec.tar.gz`
3. Run 
    ```
    kore-repl vdefinition.kore --output result.kore --module TEST --smt-timeout 40 --smt-reset-interval 100 --smt z3 --log-level warning --enable-log-timestamps --prove spec.kore --spec-module TEST-SPEC --graph-search breadth-first
    ```
