### ISSUE TITLE
Rule unification should fail fast

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#2934]
Currently, the algorithm for deciding which semantic rules apply to a given term looks something like:

```
currentTerm :: ConstrainedTerm
rulePriorityMap :: Int -> [Rule]

ruleApplications = []
for priority in priorities:
    for rule in rulePriorityMap[priority]:
         newRHS = applyRule(rule, currentTerm)
         if newRHS is not None:
             ruleApplications.append((rule, newRHS)
```

This is _slow_ because we are checking every rule in every priority bucket for full unification, and unification is inherently slow.

We can add a new more specific check in front that allows unification to fail much faster:

```

currentTerm :: ConstrainedTerm
rulePriorityMap :: Int -> [Rule]

ruleApplications = []
for priority in priorities:
    for rule in rulePriorityMap[priority]:
         if someFasterCheck(rule, currentTerm):
              newRHS = applyRule(rule, currentTerm)
              if newRHS is not None:
                  ruleApplications.append((rule, newRHS)
```

Notice we inject the call to `someFasterCheck`, which should be a very quick check which has the properties:

- If unification will succeed, this function _must not_ fail (soundness, we won't throw away rules that should definitely be considered).
- If unification will fail, this function _should_ fail, but it's OK if it doesn't (completeness, it's OK to not throw away rules that may not end up applying).

Some ideas for how to implement `someFasterCheck` (all of these ideas are related to the idea of "do some smaller unification problems that need to pass for overall unification to pass"):

- We can look at the `mainCell` field in the module attributes, and attempt _only_ unification of that main cell between the rule and the term. Note that usually the `<k>` cell is the `mainCell`, but it's not always true. Also note that we really don't need to even call the constraint simplifier for this check, we can just see if the terms structurally unify, and if they do, then allow that rule to go to full unification. In particular, in KEVM, this check alone would narrow down the number of rules to consider to exactly 1 in all cases except the `JUMPI` instruction, where it will be exactly 2.
- Re-use the existing work the LLVM backend already does building decision trees to decide the points in the term which we should try unification at for this spot-check. The LLVM backend already has a pretty advanced algorithm for deciding how to tackle the matching problem, which I think we can re-use directly. Basically we would need a way to extract (from the generated decision trees), the points in the term that should be inspected for this unification spot-check. @dwightguth is it possible to extract this information?

**Comment by ehildenb** [comment]
Some data supporting that we should be failing unification fast:

```
 rule                                                    | avg time succeeding unification | avg time failing unification | total time succeeding unification | total time failing unification
---------------------------------------------------------+---------------------------------+------------------------------+-----------------------------------+--------------------------------
 ...hmarks/storagevar00-spec.k:8:5-121:74                | 0.0                             | 142765.45259938837           | 0                                 | 46684303   
 ...hmarks/requires01-a0le0-spec.k:8:5-125:24            | 0.0                             | 148891.00628930816           | 0                                 | 47347340   
 ...hmarks/storagevar01-spec.k:8:5-123:39                | 0.0                             | 150991.6175637394            | 0                                 | 53300041   
 ...hmarks/storagevar02-overflow-spec.k:8:5-124:86       | 0.0                             | 151673.6485013624            | 0                                 | 55664229   
 ...evm/include/kframework/evm.md:285:18-289:47          | 12614.386024096386              | 3456.373861810391            | 26174851                          | 32265250   
 ...hmarks/storagevar02-nooverflow-spec.k:8:5-126:75     | 0.0                             | 161246.47411444143           | 0                                 | 59177456   
 ...hmarks/address00-spec.k:8:5-128:31                   | 0.0                             | 147853.59472422063           | 0                                 | 61654949   
 ...hmarks/overflow00-overflow-spec.k:8:5-128:36         | 0.0                             | 142154.08492569003           | 0                                 | 66954574   
 ...hmarks/requires01-a0gt0-spec.k:8:5-125:23            | 0.0                             | 148074.68112798265           | 0                                 | 68262428   
 ...hmarks/overflow00-nooverflow-spec.k:8:5-128:45       | 0.0                             | 147020.83014861995           | 0                                 | 69246811   
 ...hmarks/staticarray00-spec.k:8:5-130:33               | 0.0                             | 155477.22990353697           | 0                                 | 96706837   
 ...hmarks/encodepacked-keccak01-spec.k:8:5-128:33       | 0.0                             | 147722.68452380953           | 0                                 | 99269644   
 ...hmarks/staticloop00-a0lt10-spec.k:8:5-128:34         | 0.0                             | 146946.38612716764           | 0                                 | 127108624  
 ...hmarks/bytes00-spec.k:8:5-129:60                     | 0.0                             | 205833.7389937107            | 0                                 | 130910258  
 ...hmarks/keccak00-spec.k:8:5-129:60                    | 0.0                             | 249018.18360655737           | 0                                 | 151901092  
 ...hmarks/ecrecover00-siginvalid-spec.k:8:5-132:113     | 0.0                             | 174393.38348416288           | 0                                 | 154163751  
 ...hmarks/ecrecover00-sigvalid-spec.k:8:5-133:121       | 0.0                             | 186089.90592662277           | 0                                 | 197813570  
 ...hmarks/encode-keccak00-spec.k:8:5-129:33             | 0.0                             | 154079.9248861912            | 0                                 | 203077341  
 ...evm/include/kframework/optimizations.md:156:6-184:72 | 12913.454545454546              | 26722.977244830516           | 568192                            | 283023052  
 ...evm/include/kframework/evm.md:1464:10-1471:35        | 0.0                             | 35081.410391001606           | 0                                 | 327484966  
```

**Comment by ehildenb** [comment]
We can see that we have 3.5% productivity across all proofs:

```
tests/specs/benchmarks/address00-spec.k.debuglog: 0.03514112303555183
tests/specs/benchmarks/bytes00-spec.k.debuglog: 0.03305237835673554
tests/specs/benchmarks/ecrecover00-siginvalid-spec.k.debuglog: 0.04073187902259931
tests/specs/benchmarks/ecrecover00-sigvalid-spec.k.debuglog: 0.03739455412855404
tests/specs/benchmarks/encode-keccak00-spec.k.debuglog: 0.03791223915935558
tests/specs/benchmarks/encodepacked-keccak01-spec.k.debuglog: 0.03697000114692867
tests/specs/benchmarks/functional-spec.k.debuglog: 0.19013968208390652
tests/specs/benchmarks/keccak00-spec.k.debuglog: 0.02789910198197088
tests/specs/benchmarks/overflow00-nooverflow-spec.k.debuglog: 0.03729055294927188
tests/specs/benchmarks/overflow00-overflow-spec.k.debuglog: 0.03802008790603039
tests/specs/benchmarks/requires01-a0gt0-spec.k.debuglog: 0.035950523092690825
tests/specs/benchmarks/requires01-a0le0-spec.k.debuglog: 0.03775557818040818
tests/specs/benchmarks/staticarray00-spec.k.debuglog: 0.03456929288549166
tests/specs/benchmarks/staticloop00-a0lt10-spec.k.debuglog: 0.03844880825733282
tests/specs/benchmarks/storagevar00-spec.k.debuglog: 0.03847457771518947
tests/specs/benchmarks/storagevar01-spec.k.debuglog: 0.038089055177230026
tests/specs/benchmarks/storagevar02-nooverflow-spec.k.debuglog: 0.037320559208026245
tests/specs/benchmarks/storagevar02-overflow-spec.k.debuglog: 0.04001687252469518
tests/specs/benchmarks/storagevar03-spec.k.debuglog: 0.03866269469495609
tests/specs/bihu/forwardToHotWallet-failure-1-spec.k.debuglog: 0.0332272129018061
tests/specs/bihu/forwardToHotWallet-failure-2-spec.k.debuglog: 0.02926938571904685
tests/specs/bihu/forwardToHotWallet-failure-3-spec.k.debuglog: 0.029352185839779853
tests/specs/bihu/forwardToHotWallet-failure-4-spec.k.debuglog: 0.022502984775869563
tests/specs/bihu/functional-spec.k.debuglog: 0.33457755137888634
tests/specs/examples/erc721-spec.md.debuglog: 0.01570474381908012
tests/specs/examples/solidity-code-spec.md.debuglog: 0.07530411637926611
tests/specs/examples/sum-to-n-spec.k.debuglog: 0.102094757550697
tests/specs/functional/infinite-gas-spec.k.debuglog: 0.18410169543660315
tests/specs/functional/lemmas-no-smt-spec.k.debuglog: 0.12901495436851682
tests/specs/functional/lemmas-spec.k.debuglog: 0.22215164874310506
tests/specs/functional/merkle-spec.k.debuglog: 0.24225151364526504
tests/specs/functional/storageRoot-spec.k.debuglog: 0.15198969984345578
tests/specs/mcd/cat-file-addr-pass-rough-spec.k.debuglog: 0.04242295063834519
tests/specs/mcd/dai-symbol-pass-spec.k.debuglog: 0.043185186612000014
tests/specs/mcd/dsvalue-peek-pass-rough-spec.k.debuglog: 0.02072121138485729
tests/specs/mcd/end-subuu-pass-spec.k.debuglog: 0.03942582965437056
tests/specs/mcd/vat-mului-pass-spec.k.debuglog: 0.028473942081710227
tests/specs/mcd/vat-subui-fail-rough-spec.k.debuglog: 0.04198008062266203
tests/specs/mcd/vat-subui-pass-spec.k.debuglog: 0.034812431760900396
total: 0.03485713429590203
```

Where productivity means "total time succeeding to apply a rule / total time trying to apply rules".

**Comment by radumereuta** [comment]
We should have a log entry saying `unification failed` so we can better measure where time is being spent.
We might be able to statically detect if a rule preserves definedness. If it's functional on the RHS we don't need to do certain verification steps.
@ehildenb @dwightguth please add more to this issue.

**Comment by ehildenb** [comment]
It seems that we think that the unproductive time is broken into two different categories:

- Time spent failing to unify with the LHS of a rule.
- Time spent re-checking definedness conditions after applying a rule.

We can, as discussed above, speed up failing to unify with rules.

As far as re-checking definedness, we definitely should not have to do this after every rewrite step. Many rules should preserve definedness. That is, if the state before the rule applies is defined, and the rule has teh property that it preserves definedness, then we should have that the constructed RHS is defined without having to re-check this.

I think it should be pretty simple to prove that rules which only have constructors and functional symbols on the RHS have this "preserves definedness" property statically (at definition load time). Then for those rules, we don't need to trigger definedness checks after applynig those rules.

**Comment by dwightguth** [comment]
There actually already is a log entry for when unification fails, it is called DebugUnifyBottom. I am not sure if it is correctly including the rule location though, and if unification branches, it will be logged once per branch. But I wanted to make you aware of it.

As far as definedness goes, with respect to top level rules, we already are asserting that the substitution from unification is function-like, which should be the same as it being functional if the rule has no set variables, since element variables do not match bottom . So if the rule rhs is functional, and the substitution is functional, then the substituted configuration ought to be functional as well, which should mean that we don't need to check definedness.

Who knows though, maybe simply skipping definedness on functional patterns might be sufficient that the performance no longer is an issue.

**Comment by ana-pantilie** [comment]
Ok, thank you Everett and Dwight for the explanation. I opened https://github.com/runtimeverification/haskell-backend/issues/3126 to track this.

**Comment by ana-pantilie** [comment]
Jost has determined that this change doesn't have much impact.
