### ISSUE TITLE
Add identity `Pattern` simplifier

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2946]
We should add an identity `Pattern` simplifier (which doesn't do any actual simplification) attempt to replace the old `Pattern` simplifier with this new one in the code. By running the tests, we can identify any places which don't actually need to call the simplifier, or any places where we only need a small subset of the simplifier's cases implemented.

**Comment by andreiburdusa** [comment]
Replacing the [`Pattern` simplifier in `Kore.Rewrite.Function.Evaluator`](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Rewrite/Function/Evaluator.hs#L274) with the identity simplifier would break the following unit tests:
- [Merges substitutions with reevaluation ones](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Rewrite/Function/Integration.hs#L347)
- [2 * 1 = 2 : Nat](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Rewrite/Function/Integration.hs#L1036)
- [2! = 2 : Nat](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Rewrite/Function/Integration.hs#L1039)

Replacing the [`Pattern` simplifier in `Kore.Simplify.Rule`](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/Rule.hs#L141) with the identity simplifier would break
- [simplifies \and (#as) patterns](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Simplify/Rule.hs#L25)

Replacing the [`Pattern` simplifier in `Kore.Simplify.Simplify`](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/Simplify.hs#L312) with the identity simplifier would not break any unit tests

Replacing the [`Pattern` simplifier in `Kore.Simplify.SubstitutionSimplifier`](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/SubstitutionSimplifier.hs#L372) would break
- [x = f(x)](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Unification/UnifierT.hs#L73)
- [Non-ctor circular dependency](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Unification/UnifierT.hs#L285)
- [length 2, with And (unification, simplification)](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Simplify/SubstitutionSimplifier.hs#L193)
- [simplification generates substitution (unification, simplification)](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/test/Test/Kore/Simplify/SubstitutionSimplifier.hs#L58)

**Comment by JKTKops** [comment]
I have been investigating `2 * 1 = 2 : Nat`. I'm not sure where to go from here so I'll probably switch to `2! = 2` for the rest of the day. I have more detailed notes but here is the summary:

With the identity pattern simplifier, the simplification gets stuck at `S(0*1) = S(0)` (abbreviating `Succ` as `S`). This is an intermediate result. Notably, we get through almost the entire simplification; all steps should look like `2 * 1` => `1 + 1 * 1` => `S(1 * 1)` => `S(1 + 0 * 1)` => `S(S(0 * 1))` which is where we get stuck.

I took a look at the similar `1 * 2 = 2` simplification test. This one passes, meaning that for some reason `0 * 1` is an issue but `0 * 2` is not. My suspicion is that it has to do with the nesting depth. This is strengthened by the fact that the existing test for `0 * 1 = 0` passes.

I watched some intermediate values with `trace` and I can see roughly how the simplification is proceeding. I'm struggling to track down where the nested function evaluations are actually happening for the `1 * 2 = 2` test. I want to look at the `2!` test to see if I have an insight from there.

That said, I'm not sure I understand the aim of the issue. It seems to me like the pattern simplifier is quite simple, and just combines a TermLike simplifier (which is not simple) and the condition simplifier (which I haven't looked at). That checks out with my recollection from the summer that a pattern is a term and a condition. Are we trying to simplify the pattern simplifier or the TermLike simplifier here?

**Comment by ana-pantilie** [comment]
@andreiburdusa @JKTKops 

For each experiment, I want to see the following:

1. Remove the `Pattern` simplifier in some spot inside the code, first _without_ checking for the `simplifierx` flag.
2. Identify what the surrounding code does, i.e. is it the function evaluator, is it some ML connective simplifier, is it the condition simplifier etc. The more you understand this surrounding code, the better chances you have to figure out what needs to be done there.
3. Run the unit tests, note the failures.
4. For each unit test, understand _what_ is being tested (look at the input, the environment, which procedure is being called, what is expected).
5. Run the integration tests, note the failures.
6. For each integration test, try to get an idea of why exactly the execution is getting stuck, what isn't getting simplified anymore.
7. With the info from 2, 4 and 6, you can figure out what feature is missing, if any, and you can figure out if any of the unit tests is actually testing something unreasonable (something that will probably not appear in practice).
8. Fix what needs to be fixed.
9. Run KEVM, KWASM and any other set of tests from downstream projects (like Virgil's proofs). Note any failures, do 7 and 8 again.
10. Move changes to be enabled only when `simplifierx` is switched on.
11. Performance analysis: run downstream test suites with `simplifierx` turned on and off, measuring time performance. For each test I want to see the time spent with `simplifierx` and the time spent without, what improvement we get, a comparison of total test suite time etc.

**Comment by andreiburdusa** [comment]
Using the identity simplifier in [`simplifyPatternScatter`](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/Simplify.hs#L312):
- One place where `simplifyPatternScatter` is used is [`simplify opaques` in `AssociativeCommutative`](https://github.com/kframework/kore/blob/38083e7520a7773b0b6f028a4d05642b162ee17e/kore/src/Kore/Builtin/AssociativeCommutative.hs#L977). The documentation above says `Currently allows at most one opaque term in the two arguments taken together`. This is probably one reason why no test fails, and I think we should think if we want to allow more opaque terms in the future.
- The other place where `simplifyPatternScatter` is used is [`simplificationMakeAnd`](https://github.com/kframework/kore/blob/38083e7520a7773b0b6f028a4d05642b162ee17e/kore/src/Kore/Simplify/SubstitutionSimplifier.hs#L157) to create a `MakeAnd` that is eventually used in [`simplifyAnds'` in `deduplicateSubstitution`](https://github.com/kframework/kore/blob/38083e7520a7773b0b6f028a4d05642b162ee17e/kore/src/Kore/Simplify/SubstitutionSimplifier.hs#L219). When this `simplifyAnds'` is used, below, we have this comment: `-- Substitutions de-duplicated by simplification.`. The fact that there was no test broken suggests to me that no substitution was duplicated, and we need to think if we expect any in the future.
- All our unit and integration tests pass
- All the KEVM tests pass. I used @ehildenb 's [script](https://runtimeverification.slack.com/archives/C022YGTV4JK/p1643119447011600) for comparing performance but the output only contained aprox 25 proofs
```
andrei@q:~/evm-semantics$ ./compare.py logs/AFTER/profile/prove-haskell logs/BEFORE/profile/prove-haskell
 Test                                               | AFTER-prove-haskell time | BEFORE-prove-haskell time | (AFTER-prove-haskell/BEFORE-prove-haskell) time 
----------------------------------------------------+--------------------------+---------------------------+-------------------------------------------------
 specs/functional/lemmas-no-smt-spec.k              | 32.71                    | 48.31                     | 0.6770854895466777                              
 specs/functional/merkle-spec.k                     | 32.51                    | 46.62                     | 0.6973401973401974                              
 specs/functional/infinite-gas-spec.k               | 35.17                    | 49.42                     | 0.7116552003237556                              
 specs/functional/lemmas-spec.k                     | 44.1                     | 57.25                     | 0.7703056768558952                              
 specs/functional/storageRoot-spec.k                | 56.77                    | 73.27                     | 0.774805513852873                               
 specs/mcd/vat-subui-pass-rough-spec.k              | 346.27                   | 401.6                     | 0.8622260956175298                              
 specs/mcd/vat-subui-pass-spec.k                    | 357.34                   | 406.8                     | 0.8784169124877088                              
 erc20/hkg/approve-spec.k                           | 179.66                   | 199.26                    | 0.901636053397571                               
 erc20/hkg/totalSupply-spec.k                       | 57.22                    | 62.58                     | 0.9143496324704379                              
 specs/bihu/forwardToHotWallet-failure-2-spec.k     | 289.15                   | 315.54                    | 0.9163655954871014                              
 specs/mcd/dstoken-approve-fail-rough-spec.k        | 487.26                   | 521.74                    | 0.9339134434775942                              
 erc20/ds/transfer-failure-1-c-spec.k               | 384.47                   | 410.57                    | 0.9364298414399495                              
 specs/examples/sum-to-n-spec.k                     | 39.94                    | 42.56                     | 0.93843984962406                                
 erc20/hkg/balanceOf-spec.k                         | 109.04                   | 114.05                    | 0.9560718982902237                              
 specs/bihu/forwardToHotWallet-failure-4-spec.k     | 519.28                   | 541.02                    | 0.95981664263798                                
 erc20/hkg/allowance-spec.k                         | 140.42                   | 145.65                    | 0.9640920013731547                              
 erc20/hkg/transferFrom-success-1-spec.k            | 793.43                   | 821.64                    | 0.9656662285185725                              
 specs/benchmarks/staticarray00-spec.k              | 205.03                   | 197.95                    | 1.0357666077292247                              
 specs/benchmarks/ecrecover00-sigvalid-spec.k       | 398.05                   | 384.05                    | 1.0364535867725557                              
 erc20/ds/transfer-failure-2-b-spec.k               | 283.43                   | 272.12                    | 1.0415625459356166                              
 specs/mcd/cat-file-addr-pass-rough-spec.k          | 247.44                   | 235.83                    | 1.0492303778145273                              
 specs/benchmarks/ecrecoverloop02-sigs-valid-spec.k | 1901.26                  | 1804.28                   | 1.053749972288115                               
 specs/benchmarks/address00-spec.k                  | 140.13                   | 131.97                    | 1.0618322345987725                              
 specs/mcd/dsvalue-read-pass-summarize-spec.k       | 399.69                   | 375.07                    | 1.0656410803316714                              
 specs/benchmarks/storagevar00-spec.k               | 118.31                   | 106.2                     | 1.114030131826742                               
 TOTAL                                              | 7598.080000000001        | 7765.349999999999         | 0.9784594384026478
```

**Comment by andreiburdusa** [comment]
I redid the profiling, this time limiting it to 4 processes at the time (`-j4`) and building (`make build-provex`) in advance.
The script was set to ignore differences less than 3.5% and all proofs that run faster than 2s.
```
$ ./compare.py logs/AFTER/profile/prove-haskell logs/BEFORE/profile/prove-haskell
 Test                                           | AFTER-prove-haskell time | BEFORE-prove-haskell time | (AFTER-prove-haskell/BEFORE-prove-haskell) time 
------------------------------------------------+--------------------------+---------------------------+-------------------------------------------------
 specs/mcd/end-subuu-pass-spec.k                | 143.89                   | 149.37                    | 0.9633125795005689                              
 specs/bihu/forwardToHotWallet-failure-2-spec.k | 245.08                   | 253.78                    | 0.9657183387185752                              
 TOTAL                                          | 388.97                   | 403.15                    | 0.9648269874736451  
```

**Comment by ana-pantilie** [comment]
@andreiburdusa Thanks for double checking. Could you make sure that the proofs pass on all downstream test suites?

**Comment by andreiburdusa** [comment]
The `evm-semantics` proofs pass (`loops-spec.k`, `memory-spec.k`, `functions-spec.k`, `wrc20-spec.k`, `locals-spec.k`, `simple-arithmetic-spec.k`). I'm also discussing with Virgil to see how his proofs are affected.

**Comment by andreiburdusa** [comment]
Virgil confirmed the changes in [`simplifyPatternScatter`](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/Simplify.hs#L312) don't affect his proofs.

**Comment by andreiburdusa** [comment]
Also, here's the performance comparison from the first pull request https://github.com/kframework/kore/pull/2953
```
$ ./compare.py logs/AFTER/profile/prove-haskell logs/BEFORE/profile/prove-haskell
 Test                                           | AFTER-prove-haskell time | BEFORE-prove-haskell time | (AFTER-prove-haskell/BEFORE-prove-haskell) time 
------------------------------------------------+--------------------------+---------------------------+-------------------------------------------------
 specs/benchmarks/keccak00-spec.k               | 203.13                   | 211.84                    | 0.9588840634441087                              
 specs/mcd/dsvalue-read-pass-summarize-spec.k   | 292.9                    | 304.75                    | 0.9611156685808039                              
 specs/mcd/end-subuu-pass-spec.k                | 143.64                   | 149.37                    | 0.9616388833099014                              
 erc20/ds/transfer-success-1-spec.k             | 922.36                   | 956.15                    | 0.9646603566386027                              
 specs/bihu/forwardToHotWallet-failure-2-spec.k | 245.18                   | 253.78                    | 0.9661123808022697                              
 TOTAL                                          | 1807.21                  | 1875.89                   | 0.9633880451412395      
```

**Comment by andreiburdusa** [comment]
It looks like there are three cases when replacing the [Pattern simplifier in Kore.Simplify.SubstitutionSimplifier](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/SubstitutionSimplifier.hs#L372) breaks tests:
- the predicate `⌈f(x)⌉ ∧ (x = f(x))` isn't simplified to `x = f(x)`
- the singleton list containing `x = (y ∧ a) ∧ y = (x ∧ b)` isn't simplified to the empty list
- the substitution `x = σ(a, b) ∧ y = a` isn't simplified to `x = σ(a ∧ y, b)`

**Comment by ana-pantilie** [comment]
Strategy:
1. identify unit test failures
2. try integration tests
3. try KEVM if integration tests pass
4. if there are no real world failures, then the unit tests need to be adjusted
5. if there are real world failures, then replace the id simplifier with something a little more complicated
6. we need to develop a good understanding of what the simplifier handles and how

**Comment by andreiburdusa** [comment]
> It looks like there are three cases when replacing the [Pattern simplifier in Kore.Simplify.SubstitutionSimplifier](https://github.com/kframework/kore/blob/2c10cb2f9af9e73a34ecca324a19d4eee0ffe657/kore/src/Kore/Simplify/SubstitutionSimplifier.hs#L372) breaks tests:
> 
>     * the predicate `⌈f(x)⌉ ∧ (x = f(x))` isn't simplified to `x = f(x)`, where `f` is a function symbol
> 
>     * the singleton list containing `x = (y ∧ a) ∧ y = (x ∧ b)` isn't simplified to the empty list
> 
>     * the substitution  `x = σ(a ∧ y, b)` isn't simplified to `x = σ(a, b) ∧ y = a`

The integration tests pass, but there are some problems with the evm tests. The log produced by the profiling script contains these lines
```
124 3000.00s 0.00s 0.00s 3904KB timeout 3000 kevm prove tests/specs/benchmarks/ecrecoverloop02-sig1-invalid-spec.k --backend haskell --format-failures --directory tests/specs/benchmarks/verification/haskell
...
124 3000.00s 0.00s 0.00s 3796KB timeout 3000 kevm prove tests/specs/benchmarks/ecrecoverloop02-sigs-valid-spec.k --backend haskell --format-failures --directory tests/specs/benchmarks/verification/haskell
...
124 3000.00s 0.00s 0.00s 3864KB timeout 3000 kevm prove tests/specs/benchmarks/ecrecoverloop02-sig0-invalid-spec.k --backend haskell --format-failures --directory tests/specs/benchmarks/verification/haskell
...
124 3000.00s 0.00s 0.00s 3864KB timeout 3000 kevm prove tests/specs/examples/erc721-spec.md --backend haskell --format-failures --directory tests/specs/examples/erc721-spec/haskell
```
Which most likely mean the test timed out. I tried running the first one manually, and indeed it takes a lot of time.

**Comment by ana-pantilie** [comment]
Check if performance is better on other tests.

If new code is simpler, only 4 are timing out, Everett suggests we merge.
