### ISSUE TITLE
Implement new function evaluation algorithm

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2947]
We already know that the way we currently do function evaluation is very slow (see https://github.com/kframework/kore/issues/2474). We now have the opportunity to completely rewrite this algorithm without worrying about the old code, and we have a pretty good idea how to do it. Note that this doesn't mean rewriting the code in `Kore.Equation.Application`, I think that can be used as is.

The main ideas here: use a map of `Equation`s instead of a map of evaluators, statically apply hooks, look into parallelizing the algorithm.

**Comment by ana-pantilie** [comment]
@ehildenb An equation with a requires and an ensures clause is encoded in kore as `\\implies(requires, \\equals(lhsTerm, \\and(rhsTerm, ensures)). When applied, it will add the new condition (from the ensures) to the configuration. Do you think that this isn't sound? 

Now that I think about it, we already evaluate functions in a certain order, so if a specific evaluation adds a new condition, then the previous ones, which could have depended on this new condition, would not have actually been fully evaluated. I guess this is one of the cases where we currently depend on re-evaluating terms until they stabilize. I wonder if it would be possible to do better.

**Comment by ana-pantilie** [comment]
I guess that finding a fast way to sort conditions would be useful here as well.

**Comment by ehildenb** [comment]
Hmmm, I guess I'm just curious what exactly `equals(lhsTerm, and(rhsTerm, ensures))` means if `ensures` is `Bottom`. Does it mean that `lhsTerm` is undefined as well? I guess that is OK....

**Comment by virgil-serbanuta** [comment]
If
* the equation is encoded as `axiom \implies(REQUIRES, \equals(LEFT, \and(RIGHT, ENSURES)))` 
* `ensures` is `\bottom`
* `requires` is `\top`
you get `axiom \equals(LHS, \bottom)`, right? And `\equals(LHS, \bottom)` is not bottom itself, it just needs the LHS to be bottom.

**Comment by ana-pantilie** [comment]
@JKTKops The main idea is that this procedure should take a `TermLike`, a `SideCondition` and evaluate the function symbol applications inside it. This evaluation is done by attempting `Equation`s, see `Kore.Equation.Application`. Basically the procedure will traverse the `TermLike` and apply `Equations`. This can be the first part. The second part would be to write a big case statement which takes a function symbol, identifies if it's hooked, checks which hook it is and evaluates it by just calling the hook's evaluator.

Recall that since we're dealing with functions, the result of evaluating functions is singular (deterministic), so it shouldn't split the configuration.

Right now, `MonadSimplify` has a map of equation identifiers to equation evaluators. We'll need to add a similar map, but it will be from equation identifiers to equations themselves. I believe it will be good to take a look at how this map is built, and what other preprocessing we do to the equations before constructing this map, because we most likely will need to do the same with this new map. I think `Kore.Simplify.Simplify` and `Kore.Simplify.Data` should be useful here.

Let me know if you have any other questions!

**Comment by ana-pantilie** [comment]
My linked PR implements function application as discussed and creates a new Pattern simplifier: `simplifyPatternX`. This just applies the function evaluation procedure.

As a first experiment, when `--simplifierx` is turned on, the Pattern simplifier is replaced with this new `simplifyPatternX`. Running the integration tests, `test/assume/test-spec.k` fails with the following output:
```
+  #Ceil ( <k>
+    #assume false ~> .
+  </k> )
+#And
+  #Ceil ( <k>
+    #assume false ~> .
+  </k> )
+#And
+  #Ceil ( <k>
+    #assume false ~> .
+  </k> )
+#And
+  <k>
+    #assume false ~> .
+  </k>
+#And
+  {
+    _DotVar0
+  #Equals
+    <generatedCounter>
+      _DotVar1
+    </generatedCounter>
+  }
```
Note that this definition doesn't include any functions, only the `#assume` constructor and a rewrite rule associated with it. 

The rule doesn't apply anymore, but that's because execution doesn't get to that phase anymore. I believe the proof is getting stuck during the `CheckImplication` phase, which is before `ApplyAxioms`.

Features needed for this to pass: `#Ceil` simplification (specifically, `#Ceil(constructor) = #Top`), `#And` idempotency, `false` simplifies to `#Bottom`.

There's also the question of what we're going to do with `CheckImplication`. Currently, this procedure constructs an `\\in` pattern: `\\in(leftTerm, rightTerm)` and calls the `Pattern` simplifier on it. We might want to just call the unification procedure here? Also, the procedure calls the `Not` and the `Exists` simplifiers directly. Going forward, I'd like to keep the simplifier interface clean and abstraction-preserving, and not allow such leaky calls.

**Comment by ana-pantilie** [comment]
I'm going to continue by actually replacing the current function evaluator, effectively integrating the new function evaluator into the old term simplifier. For this I will need to add hook evaluation as well.

**Comment by ana-pantilie** [comment]
Another experiment:
1. call new function evaluator
2. call old pattern simplifier

**Comment by ana-pantilie** [comment]
Everett: get performance numbers on all tests in KEVM

**Comment by ana-pantilie** [comment]
Look into generating static call stack.

Why is `hashWithSalt` being called? Where is it called? What tools do we need to figure this out.

**Comment by ana-pantilie** [comment]
Still look into replacing the old function evaluator in-place.

**Comment by ana-pantilie** [comment]
I've been investigating the hashWithSalt issue, and I've made some progress regarding my own understanding of the profiles, but I still haven't been able to find any direct link between the code in the new function evaluator and the increase in time/time spent in hashWithSalt , although I do have an idea on what might be going on!
First of all, the big gaps I was initially seeing in the profiles (the direct parent of hashWithSalt in one important case was directly TermLike.simplify ) have been mostly filled by switching profiling-detail to all-functions in cabal.project. This option is toplevel-functions on master, which only adds top level functions as cost centres in the profile. I initially tried to add SCC annotations for some functions inside TermLike.simply to not clutter the profile but that didn't work. Anyway, I think having it set to toplevel-functions as default is good for spotting the general area in which there's an issue, and for more deep analysis locally switching to all-functions is good enough.

What I found is that this high cost of hashWithSalt from TermLike.simplify seems to be coming from replaceTerm. What this function does is, indeed, hash and compare TermLike hashes in an effort to do some simplification using the table cached in the SideCondition. There is, however, no information in the profile about how adding the new function evaluator influences this.

That is not the only place hashWithSalt takes a lot of time, but from comparing the feature profile vs the master profile I found a large discrepancy between the two cost centres.

Another observation is that attemptEquation has basically disappeared from the feature profile, while on master it's the biggest cost centre. Both the old simplifier and the new function evaluator call attemptEquation
And the last big observation is that total allocation is actually lower on the feature branch.

So, after digging through these lower-level details, I've been thinking about the higher level impact of my change. What's happening now is that, we're evaluating the term first, before simplifying the condition and applying resulting substitutions to the term. Which probably means, that it can't really evaluate that much of the term, because it has less information! But here come the two caching mechanisms for the results of function evaluations, which both use hashing to store and lookup results, especially when it fails to apply equations. So maybe, what's happening is that these caching mechanisms only work correctly if the term is evaluated using all available information, an invariant I have broken by putting the function evaluator in front of the rest of the Pattern simplifier.

If this is indeed the case, then this code isn't correct, and the only way to fix it is to disable all the caching mechanisms or to integrate the new function evaluator into the old term simplifier.

**Comment by ana-pantilie** [comment]
Experiments related to:
```
newPatternSimplifier = evaluateFunctionsInTerm >>= oldPatternSimplifierLoop
```

1. Tested `dsvalue...` spec with cache from `MonadSimplify` disabled, test is still not finishing
2. Tested `dsvalue...` spec with cache from `MonadSimplify` and cache from `SideCondition` disabled, test is still not finishing
3. Disabling third cache (the `Simplified` attribute) will be quite time consuming so first I will try something else
