### ISSUE TITLE
Add regression tests from all downstream projects

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2974]
Currently, our test suite only has tests from KEVM and KWASM. The backend is also used by KElrond and MKR-MCD-SPEC, and we should select some tests from those projects which finish in reasonable time to add to our test suite.

This will also help with testing simplifier experiments.

**Comment by JKTKops** [comment]
I've tracked down how to add regression tests, but the KElrond test suite does not have an (obvious) way to get per-test profiling information the way KEVM does. I've asked Virgil if he knows a set of tests that might be a good choice and he said he can take a look tomorrow. (I could also start a test run manually using a modified Makefile that times each test, but Everett says the KElrond suite takes 3 hours to run and that would go until the end of my workday anyway).

Everett said we should not worry about getting tests from MKR.

**Comment by ana-pantilie** [comment]
> Everett said we should not worry about getting tests from MKR.

Why? @JKTKops @ehildenb

**Comment by ehildenb** [comment]
The current symbolic execution proofs for MKR are actually based on KEVM (via refinement proofs), so it's better to focus on passing the specs in `tests/specs/mcd/...` in the KEVM repository than looking at MKR right now.

The only other features of the MKR semantics independent of this are using the LLVM backend.

**Comment by JKTKops** [comment]
After making some progress we've realized that `bazel` (the build tool used by `elrond-multisig`) uses the version of the Haskell Backend in the global K package and won't use the version of `kore-exec` on the path. This is currently blocked until we have a way to extract just the kore files and `kore-exec` command from that project.

The current idea is to use `--bug-report` to generate the files we need for regression testing. Virgil plans on adding support for that to the elrond project in a few days.
