### ISSUE TITLE
New #Ceil simplifier

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2976]
Ceil simplification is currently really complicated and hard to reason about. Also, it's pretty slow as well. I might be misreading things, but I remember seeing on profiles that we're doing double the work: simplifying the term and then simplifying the #Ceil of the term, which includes simplifying the term again. Even if this is not accurate, we don't always need to simplify the argument of the #Ceil in order to evaluate the #Ceil itself. There's also the issue that the #Ceil simplification modules have always introduced some form of cyclic dependency between it and the rest of the simplifier.

I propose that, similar to the function evaluator, we create a new #Ceil evaluator procedure. This will be called by the new `Pattern` simplifier, as part of a new `Condition` (or `Predicate`) simplifier. What it should do is traverse the predicate top-down and try to apply `#Ceil` simplification rules (like https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#implementation-of-maps), or check if the argument is defined and simplify directly to #Top, etc. We need to think about which cases can be simplified and which can't.

**Comment by JKTKops** [comment]
I thought there were more examples in this paper (I must be remembering them from somewhere else) but perhaps it's still useful. The paper is Grigore's paper [here](https://arxiv.org/pdf/1705.06312.pdf). `\ceil` patterns are introduced on page 21 and discussed briefly. Another relevant section is also that on functional patterns (beginning page 27). Whenever we have a pattern like ⌈σ(x1,...,xn)⌉, where σ is functional, we can conclude immediately that the pattern is ⊤ without inspecting the application any further.

**Comment by ana-pantilie** [comment]
I think `⌈σ(x1,...,xn)⌉` with `σ` functional can be simplified directly to `⌈x1⌉∧...∧⌈xn⌉` without having to evaluate `σ(x1,...,xn)` first, right? @virgil-serbanuta @JKTKops

**Comment by virgil-serbanuta** [comment]
Yes, that's correct.
