### ISSUE TITLE
Script for performance testing a new test suite

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2993]
@ehildenb provided a test suite of 130 proofs here: https://runtimeverification.slack.com/archives/CC360GUTG/p1645750056420389

~~We should write a script for performance testing it, similar to the KEVM performance test script.~~

See the comment below; the suite has been uploaded to a sharable Google Drive folder, along with a readme and a script to run all the tests in the folder. The original bug reports reference the filepath where they sent logs, which is not present in the reports themselves; I used the following `sed` script to disable logging and delete the reference to that path: `sed -Ei '/(--log(-entries)? )|(\.debug\.log)/,+1d' kore-exec.sh`.

For completeness, the readme is inlined here.

-------------------------

# KEVM Bugs

This folder contains a set of 130 proofs from the evm-semantics repository to be run on the Haskell backend.
The term 'bug report' is used judiciously; they are compact representations of each proof that do not
require having access to evm-semantics to run, which allow the Haskell Backend team to focus on the behavior
of the Haskell Backend on the proof.

All of these proofs currently achieve the expected behavior. Some of them do not pass, and that is expected.

The goal is to optimize the performance of these proofs. Everett wants them to all run in <1s each.

## Format of Each Proof

Each proof comes nicely packaged in a folder containing:
  1) A script called 'kore-exec.sh' which will run the Haskell Backend on the proof
  2) vdefinition.kore and spec.kore, which contain the specification of the proof and the language it is over in K's internal Kore language
  3) result.kore, which contains the output of the proof, again in K's internal Kore language
  4) a log file, which lists all of the transition steps taken by the proof. This can be used to judge how long the proofs are.

## Setting up the Haskell Backend

The [Haskell Backend repository](https://github.com/runtimeverification/haskell-backend) has setup instructions. The K Framework Frontend
should not be required to run these proofs. The `kore-exec.sh` scripts will use whichever version of `kore-exec` appears first on your `PATH`.

## Running the Whole Suite

The `run-all.sh` script in the root of this folder will enter each bug report folder, run the script with the given additional options,
and exit the folder. The script is very simple:

```sh
for dir in */
do
    cd $dir
    ./kore-exec.sh "$@"
    cd ../
done
```

## Running Proofs with Profiling Scripts

The `kore-exec.sh` scripts will pass any command line arguments through to `kore-exec`. As such, if you have a Haskell profiling build of `kore-exec`, you can pass command line arguments for profiling to it and it should Just Work.

The proofs have some setup already for
logging, but disable logging in general as it should not be necessary. Add `--log <FILE> --log-entries [ENTRIES]` to get a log of
the selected entries to the selected file. `kore-exec --help` should provide a list and short description of available entries.
This can be useful for determining what is happening in the backend itself as the proof progresses.

Because of how the bug report scripts are formatted, the easiest way to change the `kore-exec` command itself for profiling is to put a different command with that name first on your path, such as a script containing `timeout 30 kore-exec "$@"`.

**Comment by ana-pantilie** [comment]
Add instructions on how to run these, and what should happen: optimize performance, output shouldn't change. Move tests to Google Drive so that they can have access to them.

**Comment by JKTKops** [comment]
The bug reports have been uploaded to [a google drive folder](https://drive.google.com/drive/u/1/folders/1RjTHTD6-I3B8kCEeOi4V41Ch6sF_NVyB) which requires access. I included a simple script that runs all the proofs (without doing individual-level profiling) as well as a README describing the contents and linking to the instructions for setting up the Haskell backend. I am happy to include anything else that is missing or otherwise needed.

Because of how the bug report scripts are formatted, the easiest way to change the `kore-exec` command itself for profiling is to put a different command with that name first on your path, such as a script containing `timeout 30 kore-exec "$@"`.

**Comment by ehildenb** [comment]
I've added the bug reports for KEVM on commit 9855ffbd to the google drive as well.

**Comment by ehildenb** [comment]
More tests: https://drive.google.com/file/d/1iu6PoELlApktAKHbR2cGTWZqvsZzSx7Z/view?usp=sharing
