### ISSUE TITLE
Add option to keep substitution constraints during execution/simplification

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3029]
Sometimes during execution we get constraints that look like `X ==K P(Y)` (for `P` some functional pattern), and the backend replaces every occurrence of `X` with `P(Y)` instead, then discards the constraint.

First I wonder if this actually makes sense to do, because we will almost always be making the term size larger by doing this. I would think we would want to do the opposite, that is to replace every occurrence of `P(Y)` with `X` to reduce term size. Is it strictly necessary for the backend to behave as it does @ana-pantilie?

Either way, we should keep the constraint around, either by storing it separately or simply not discarding it (so it stays in the constraints attached to the term). This could be on option `--keep-substitutions` which keeps the substitution in the constraint for inspecting in the final state.

This would address this problem we have with the summarizer (which has no general work-around, as far as I know): https://github.com/runtimeverification/erc20-verification/issues/297

Another use came up, which is that we are actually discarding some constraints that are needed for checking the final configuration in a proof we're doing, because we do it by iteratively running the prover and each time it outputs the final configuration, it's discarded this constraint. An example from @lisandrasilva is https://github.com/runtimeverification/erc20-verification/blob/ed04c1d5b3ce00adb341d66532b277a2daab8eb8/tests/summarize/evm-specs/vat-slip-pass-rough-spec.k#L49 . Here, at the beginning of the proof, we have `#lookup(...) ==Int Gem`, which gets substituted into the configuration and then discarded. So in the final steps of the summarizer (which happen several `kprovex` calls later), we no longer know the definition of `Gem`. It goes to check that the storage cell is `ACCT_ID_STORAGE [ Key <- Gem +Int WAD ]` and cannot, because it does not know the definition of `Gem` anymore.

**Comment by virgil-serbanuta** [comment]
I agree with not discarding the constraint (though I don't know the tradeoffs involved), but it probably makes sense to do the replacement.

A simple example is the following: Let's say that you have a simplification rule `f(g(X)) => 0`, and you have `f(Y)` somewhere in your term/predicate. If you know that `Y = g(X)`, but you don't replace it everywhere, then it may be hard to apply the simplification rule (though probably it's not impossible).

I think I actually used this in the Elrond proofs (though the only way to be fully sure would be to disable it and see if the proofs still work), and I would be somewhat surprised if other people didn't do the same.

Some proofs worked in a surprising way which may imply that the Haskell backend does even more, e.g. when it sees `term1 = term2` it will replace `term1` by `term2` (i.e. `term1` does not have to be a variable), though I didn't have time to actually see if that's the case. Maybe @ana-pantilie can say if that's plausible or not.

**Comment by ehildenb** [comment]
For https://github.com/runtimeverification/erc20-verification/issues/297 it's important that we also do not actually substitute the constraint back into the original configuration, which is slightly different than just keeping those constraints around. I think both are useful options, but the one which does not do the back-substitution into the configuration might be called `--no-substitute-constraints` or something.
