### ISSUE TITLE
Log better explanation of why the claim is stuck

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3033]
`WarnStuckClaimState` currently does have two distinct cases, but I believe the messages displayed to the user are too vague and don't contain enough information.

**Comment by ehildenb** [comment]
If would be great to make sure this is printed to the command-line too. Most people aren't turning on logging options.

**Comment by ehildenb** [comment]
![Screenshot from 2022-04-14 11-28-48](https://user-images.githubusercontent.com/12721972/163389124-50390b42-390d-42d0-b2c0-d4be90d9b2ab.png)

Output example from Pyk that is useful (for the structural matching failure)

**Comment by ana-pantilie** [comment]
Make it clear if unification failed, and execution is stuck.

If unification didn't fail, output substitution and print out failing implication.

Future work: which constraints make the implication fail?

**Comment by ana-pantilie** [comment]
If unification succeeds, just print out condition implication as remaining proof obligation.

As much clarity as possible between unification issue or implication issue.

**Comment by radumereuta** [comment]
Please come up with some versions and ask for feedback from K users (maybe on the #k channel on slack).
I'm sure you will get plenty of opinions.

**Comment by radumereuta** [comment]
Just make a better error message:
- this failed because of unification!
- this failed because implication check!
An incremental change for now should be fine for now.
