### ISSUE TITLE
Apply simplification rules to \\equals

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3040]
Right now simplification rules only apply on terms with symbol applications at the top or with \\ceil at the top. We need to extend this feature to other ML connectives as well, starting with \\equals which is currently blocking the c semantics.

**Comment by radumereuta** [comment]
@dwightguth please provide a trace for this issue using this documentation:
https://github.com/runtimeverification/haskell-backend/wiki/Debugging#function-evaluation

**Comment by dwightguth** [comment]
[smoke.tar.gz](https://github.com/runtimeverification/haskell-backend/files/8633071/smoke.tar.gz)

**Comment by dwightguth** [comment]
[smoke.tar.gz](https://github.com/runtimeverification/haskell-backend/files/8633126/smoke.tar.gz)

**Comment by dwightguth** [comment]
As I said on slack, nothing is reported in the log. This should allow you to reproduce the issue, however.
