### ISSUE TITLE
--execute-to-branch requires --prove

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3048]
When you pass `kore-exec --execute-to-branch` without passing `--prove`, it reports an error. It would be nice if this just worked, as it would replace a rather cumbersome and inefficient test harness that I have for testing symbolic execution in the C semantics, and save me a lot of time and effort.

**Comment by JKTKops** [comment]
Everett gives an example that should reproduce this:
```
module MY-MODULE
   imports INT
   configuration <k> $PGM:Foo </k>
   
   syntax Foo ::= "a" | "b" | "c" | "d"
   
   rule <k> a => b ... </k>
   rule <k> b => c ... </k>
   rule <k> b => d ... </k>
endmodule
```

`test.foo`:
```
a
```

```bash
$ export KORE_EXEC_OPTS="--prove --execute-to-branch"
$ kompile my-module.k --backend haskell
$ krun test.foo
```

@dwightguth does this reproduce your issue? If not, please give a minimal example.

**Comment by dwightguth** [comment]
As I said, the error occurs when you pass --execute-to-branch but not --prove. So no, that example does not reproduce my issue. But I am reasonably confident that /any/ invocation of kore-exec with those flags will reproduce the error.

**Comment by dwightguth** [comment]
I can confirm this is an option validation issue. So here's an example, although surely you could have figured this out without it:

```
module TEST
  imports BOOL
endmodule
```

**Comment by JKTKops** [comment]
Try the branch from #3055 when you get a chance.
