### ISSUE TITLE
Evaluate laziness of logging

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3087]
As part of my profiling efforts with the new unification algorithm, I discovered that an abnormal amount of time was being spent in `traverseVariables`, seemingly as a result of constructing arguments to log entries that the log was suppressing. This is wasted work, obviously. It happens because we enabled strictness globally in our package config, and so we end up fully evaluating the arguments to log entries, even if those log entries are completely ignored.

I have made modifications in my PR to a few log entries that I noticed as having contributed to a sizable percentage of the time spent in `unifyRule`, but we almost certainly should do a more thorough evaluation of all our log entries, as I have no doubt there are other cases where we are needlessly traversing large terms that are about to be discarded.

**Comment by jberthold** [comment]
All logging-related data structures and helper functions in `Kore.Log.*` are now lazy.
Call sites have been checked to not introduce any strictness exclusively for logging.
