### ISSUE TITLE
Fix axiom simplifier lookup mechanism for \equals and \ceil

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3098]
Right now, there is a bug in the way we look up axioms to use to simplify \ceil and \equals terms. In particular, if the simplification rule we wrote has a \equals or a \ceil on the lhs whose child is something for which `matchAxiomIdentifier` returns Nothing, then configurations which would match these rules will skip applying any axioms, even though such an axiom could apply. I have extended the supported cases somewhat in #3097 , but a full fix still ought to be performed.

**Comment by virgil-serbanuta** [comment]
Re: "Why do the Equals/Ceil etc. constructors of AxiomIdentifier have arguments?" - When this was implemented, we thought that at least one of the following is/will be true:
1. there are/will be semantics in which a large number of the symbols have `ceil` simplification rules
2. a significant number of configurations (will) have unsimplified `ceil`s in the predicate

If any of the above is true, it may be worth to identify quickly whether there are `ceil` simplification rules which can be applied, and which such rules should be applied. The arguments help both with splitting the set of simplification rules in smaller chunks, and with discarding some of the cases where the rule may not apply. In principle, this could probably also help the backend to skip transforming a predicate in a term before attempting to apply axioms.

I don't know if that actually matters, i.e. I don't know how much faster is it to do a map lookup instead to have matching fail for a number (say, 10-20) of axioms, or how much total time would be consumed by failing to match, or other stuff like that.

Probably some similar reasoning can be applied to `Equals`, though I'm less familiar with that.

If the optimizations mentioned above are worth the trouble, it would probably be possible to limit the AxiomIdentifier to 2 levels or something like that, and to generate identifiers for all ML constructs.
