### ISSUE TITLE
Improve compilation time of the Haskell backend

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3103]

**Comment by radumereuta** [comment]
Documenting some things we talked about:
- adding option -j6 dropped the compilation time from 3m15 to 2m12 on my AMD5950x
- executables are built in series, we could investigate if there is a way to parallelize that.
- we could also ask the Serokell guys if they have ideas about how to improve compile performance. It's not in the initial list of tasks, but maybe they have some pointers.
- installing, configuring, and running make on the haskell backend. Any solution we find should strive to maintain that.
