### ISSUE TITLE
rule for #Ceil(@Set1 @Set2) not working

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/haskell-backend#3107]
I'm trying to define a rule for `#Ceil(Set1 Set2)` operation using `intersectSet`. It doesn't seem to apply.
Example:
```
...
module CEIL-SET
    imports CEIL-SET-SYNTAX

    configuration <k> $PGM:Test </k>

    rule <k> eval ( S ) => evalResult ( S ) </k>

    rule #Ceil(@S1:Set @S2:Set) => {intersectSet(@S1, @S2) #Equals .Set} #And #Ceil(@S1) #And #Ceil(@S2)
      [anywhere, simplification]

endmodule

module CEIL-SET-SPEC
    imports CEIL-SET

    claim <k> eval ( S1:Set S2:Set ) => . </k> requires intersectSet(S1, S2) ==K .Set

endmodule
```

Expected result:
```
  <k>
    evalResult ( S1
    S2 ) ~> .
  </k>
```

Actual result:
```
kore-exec: [173001] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The configuration's term doesn't unify with the destination's term and the configuration cannot be rewritten further. Location: /home/user/k/k-distribution/tests/regression-new/ceil-set/ceil-set-spec.k:8:11-9:45
  #Ceil ( S1
  S2 )
#And
  <k>
    evalResult ( S1
    S2 ) ~> .
  </k>
```

Full working example here: https://github.com/runtimeverification/k/pull/2670

Also it looks like side condition for `requires intersectSet(S1, S2) ==K .Set` is not created.

Is there a better way to define `#Ceil(Set1 Set2)`, that wouldn't involve `intersectSet` ?

**Comment by denis-bogdanas** [comment]
Haskell version: `9c8b14f`

**Comment by ana-pantilie** [comment]
I have investigated this issue and the problem is that this simplification rule doesn't apply because we don't support that kind of matching. Now, unless you have a good reason not to, I'd suggest writing the #Ceil rule for Set concat similarly to how it's written for Map concat:

```
    rule #Ceil(@S:Set SetItem(@K:KItem)) => {(@K in @S) #Equals false} #And #Ceil(@K) #And #Ceil(@S)
        [anywhere, simplification]
```

I have checked, and this gets applied successfully by the Haskell backend.

**Comment by denis-bogdanas** [comment]
Problem is some operations require generalized set concatenation.
we have this rule in domains.md:
```
rule S1:Set |Set S2:Set => S1 (S2 -Set S1)
```

Apply this to:
```
SET:Set |Set SetItem(X)
```
ans we get:
```
#Ceil ( SET ( SetItem ( X:MyId ) -Set SET ) )
#And
  <k>
    ... SET  ( SetItem ( X:MyId ) -Set SET ) ...
  </k>
```
