### ISSUE TITLE
Serokell: specialization of SMT

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3110]
We attempted to solve the problem of specialization and inlining by changing the abstract monad MonadSimplify simplifier to SimplifierT SMT. This could not be done easily because of the application architecture.
The base monad is determined dynamically:
```
execute options metadataTools lemmas worker =
  case solver of
    Z3 -> withZ3
    None -> withoutSMT
```
For the purposes of the investigation we simply removed the support for NoSMT. A proper solution would be to use a concrete base monad (e.g. ReaderT r IO) but a dynamically determined payload (e.g. Maybe SMT, where NoSMT would be represented by Nothing).

**Comment by gromakovsky** [comment]
I believe it was resolved by https://github.com/runtimeverification/haskell-backend/pull/3156 and can be closed now.
