### ISSUE TITLE
kore-exec should output a count of unexplored leaves when it terminates

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3119]
When a proof fails, `kore-exec` will output a counterexample (or more than one, with `--max-counterexamples`). However, the output of counterexamples does not provide information about how many branches/leaves remained unexplored and might therefore yield additional counterexamples.

This can be found out in debugger mode by calling `leafs`. 
The CLI could output this information when `kore-exec` terminates. 

Needs #3143

**Comment by ana-pantilie** [comment]
@jberthold Let's timebox this: let me know at the end of your day tomorrow what your progress has been and we'll decide what to do with it.

**Comment by jberthold** [comment]
Status: This feature required modifications to how the execution graph is explored (`leavesM` in `Kore.Rewrite.Strategy`) and instigated a rewrite of the graph traversal functionality that `leavesM` provides. Code is in #3163 (closed for archiving), and will be cleaned up so it can be merged and used for `kore-exec`.
