### ISSUE TITLE
Detect if equational rules are unsupported

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3170]
See https://github.com/runtimeverification/k/issues/2750#issuecomment-1196618502

Right now we support equational rules where the LHS has a function(al) symbol, `\\equals` or `\\ceil` at the top. The backend should abort execution if it detects anything else in this spot and provide an appropriate error message containing the source location of the rule.

**Comment by ana-pantilie** [comment]
We might want to add this to https://github.com/runtimeverification/haskell-backend/blob/e39ec77530f3c032d56c50a4d298f02c3ea28b18/kore/src/Kore/Equation/Sentence.hs#L107, but we need to see what we do with the error where this is called. I think this issue requires a bit of investigation.

**Comment by alexd1971** [comment]
@ana-pantilie , if I correctly understand, the `matchEquation` function already contains needed checks in `match` subfuntion: https://github.com/runtimeverification/haskell-backend/blob/6fdf45369016855995d7bf5529186fb72b9bfda0/kore/src/Kore/Equation/Sentence.hs#L119-L234
Or it's not that we're expecting?

**Comment by ana-pantilie** [comment]
@alexd1971 In that function, you need to check if the top level connective supports simplification rules or not. If it doesn't then you should actually throw an exception.
