### ISSUE TITLE
[Simplification request] Top-level existential elimination

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3193]
Simplification
--------------

Existential quantification in top-level positive constraints can be eliminated and the bound variables can be replaced with some fresh variables.

Example: ```#Exists X. { P(X) } => P(X0)```, for some `X0` fresh.

I am assuming that this is a sound simplification when doing matching-logic proofs since it is sound when doing first-order logic proofs, and matching logic captures first-order logic.

This simplification cannot be applied under negation.

**Comment by ana-pantilie** [comment]
https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Variables/Fresh.hs for refreshing variables
