### ISSUE TITLE
Provide more information when crashing on ErrorDecidePredicateUnknown

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3196]
We should tell the user where the predicate comes from and in what procedure we were when trying to evaluate the predicate.

Also mention in the error message:
- `--smt-retry-limit <n>`, which retries `unknown` queries `n` times, each time with a larger timeout; default `n=1`

**Comment by goodlyrottenapple** [comment]
I'm not sure what is meant by "where the predicate comes from", do we mean the kore/k file location. Is this information stored anywhere or would we need to modify things such that this information gets carried around?

Also, there is only one place where this error is thrown, namely `Kore.Rewrite.SMT.Evaluator`'s `decidePredicate`

**Comment by ana-pantilie** [comment]
> would we need to modify things such that this information gets carried around?

Most likely, yes. `decidePredicate` gets called in many situations, and those callsites should provide more context for those calls. I think we could wrap them in https://github.com/runtimeverification/haskell-backend/blob/a1959233e210f960d49a91ebe7fcec76da14ebe3/kore/src/Log.hs#L206?

Also, see https://github.com/runtimeverification/haskell-backend/pull/3238#pullrequestreview-1098941587

**Comment by goodlyrottenapple** [comment]
fixed by  #3252
