### ISSUE TITLE
Continue when error is thrown when attempting simplification rules

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3197]
If, for some reason, we don't know if a simplification rule applies or not, just emit a warning and continue execution. Specifically, when checking the requires of a simplification rule, if ErrorDecidePredicateUnknown is thrown, don't crash.

**Comment by ana-pantilie** [comment]
@jberthold please add some links to the code which you think is useful here

**Comment by jberthold** [comment]
The key insight here is that `decidePredicate` will only ever return `Just False` or `Nothing`, never `Just True`.
https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Rewrite/SMT/Evaluator.hs#L164-L169
`decidePredicate` is only called by `evalPredicate`, which is only called by `evalConditional`, in the same module.

`evalPredicate` can in fact return `Just True` when the predicate only contains a `Top`, https://github.com/runtimeverification/haskell-backend/blob/be7e56172bd02d32b31d91c20fc7ba1a47766fc0/kore/src/Kore/Rewrite/SMT/Evaluator.hs#L99

Call sites for `evalConditional`: 
* Simplifier: `simplifyClaimRule`, to filter things that are known to be false: https://github.com/runtimeverification/haskell-backend/blob/be7e56172bd02d32b31d91c20fc7ba1a47766fc0/kore/src/Kore/Rewrite/Rule/Simplify.hs#L140-L143 
* `checkRequires`, to filter by known false requirements: https://github.com/runtimeverification/haskell-backend/blob/be7e56172bd02d32b31d91c20fc7ba1a47766fc0/kore/src/Kore/Equation/Application.hs#L382-L390 
For both callers, tolerating `Unknown` results and returning `Nothing` seems fine (solver timeouts might cause additional work downstream for re-checking).
* `Search`: https://github.com/runtimeverification/haskell-backend/blob/be7e56172bd02d32b31d91c20fc7ba1a47766fc0/kore/src/Kore/Rewrite/Search.hs#L151-L161
In this code, different conditions are returned depending on the result. The difference between an `Unknown` and  a `Just True` result is minor, though.
