### ISSUE TITLE
Measure performance of check implication

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3224]
Follows up on #3208

The current implementation(s) (both for JSON-RPC and for the prover) of the implication check rely mostly on the SMT solver.
Explore if the algorithm could be simpler/faster by breaking up the constrained terms involved into their components and applying targeted simplifications first.

A couple of example ideas (for implication `(t(X) /\ P(X)) => (t'(X) /\ P'(X, Y))`:
* If you have `P(X)` contains `p(X)`, and `P'(X)` contains `p(X)`, you can remove it from `P'(X)`, to get a minimized consequent directly
* If we _have_ that `t'(X)` matches `t(X)` with substitution `\alpha`, then we can construct `(alpha(P(X) => P'(X, Y)))`, and simplify _that_ term, and maybe get the satisfying assignment directly

**Comment by ana-pantilie** [comment]
We'll put this on hold until we fix ceil simplification which seems to be the main bottleneck at the moment.

@jberthold can you please add the graphs which measure this?

**Comment by ehildenb** [comment]
We did this profile, and found out that ceil simplification is where time is being spent, so we're focusing on that before reprofiling.
