### ISSUE TITLE
Remove dependence of `stack build` on `git`

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3226]
Someone recently filed an issue on the k frontend repository who appears to be trying to get a kframework package into the main package manager of FreeBSD. I think we should try to encourage this since it will help K become more widely used.

Their issue amounts to the fact that most linux distros deliberately forbid downloading from the internet when building packages. However, we have dependencies on two github repos in our stack.yaml.

If it doesn't prove to be a substantial amount of work, I think we should try and determine how easily we can replace those dependencies with dependencies on code in hackage, either by upstreaming the code changes we made, creating new packages for repos in hackage, inlining the code into the main repo, or some combination thereof. This will be necessary if we are ever going to get distro-maintained kframework packages.

**Comment by ana-pantilie** [comment]
We need to remove two dependences in order to do this:
1. SQLite logs
2. kore-prof should be rewritten to not depend on the external packages

We need to wait for co-log (at least) to be properly released for GHC 9.

**Comment by ana-pantilie** [comment]
We need to remove two dependences in order to do this:
1. SQLite logs
2. kore-prof should be rewritten to not depend on the external packages

We need to wait for co-log (at least) to be properly released for GHC 9.

**Comment by ana-pantilie** [comment]
@treeowl please take a look at removing the code which depends on https://github.com/ttuegel/pipes-sqlite-simple.git. I think there's a `--sqlite` or something option which enables a database of logs to be outputted.
