### ISSUE TITLE
Flaky nix shell check in CI

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/haskell-backend#3236]
The CI Nix shell check action often errors out with

```
error: derivation '/nix/store/58xgc5mhip4f2bfc5fpb7smm7b4fzl9y-hoogle-local-0.1.drv' requires non-existent output 'doc' from input derivation '/nix/store/027ci16pwznr0krbh62ik4rhm4l8lf7j-pipes-aeson-lib-pipes-aeson-0.4.1.8-haddock.drv'
```
This is most likely due to https://github.com/NixOS/nix/issues/6572
The options to fix are:
* separate this step in the run into its own action and run via an older version of nix
* downgrade nix for the whole action (tho this may not be feasible if this behaviour occurs in nix >2.4) 
* or drop the shell check entirely

**Comment by jberthold** [comment]
Suggestion: 
* leave `nix-shell` check commented
* make `nix develop` support `fourmolu` and integration tests
* remove old-style `nix-*` commands completely and update the `README.md`

**Comment by ana-pantilie** [comment]
@goodlyrottenapple found that the third bullet point (`remove old-style nix-* commands completely and update the README.md, except for nix-build test.nix`) is not possible to do currently.

https://github.com/runtimeverification/haskell-backend/pull/3245 fixes the rest.
