### ISSUE TITLE
Remove `Target` type from the code

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3242]
Uses of type `Target` and friends are:
* one unnecessary internal use in Rewrite/Axiom/EvaluationStrategy.hs (pending removal by Serokell at the time of writing)
* one unused export in Rewrite/Step.hs
  Rewrite/Step.hs:315:toConfigurationVariablesCondition ::
* unused exported function in Internal/OrPattern.hs
  Internal/OrPattern.hs248:targetBinder ::

**Comment by ana-pantilie** [comment]
Remove Target and see what breaks.
