### ISSUE TITLE
Rewrite kore pattern generators for the property tests

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3244]
Test runs sometimes won't terminate, or get killed (in CI, due to consuming too much memory).
Preliminary investigation points to [test_simplifiesToSimplified](https://github.com/runtimeverification/haskell-backend/blob/master/kore/test/Test/Kore/Simplify/IntegrationProperty.hs#L70).

**Comment by jberthold** [comment]
In `test_simplifiesToSimplified`, the simplifier run sometimes appears to get into a loop .
 A [test case has been extracted in a new branch](./compare/3244-examine-hanging-test) but it is very large. Some manual shrinking could still reduce it.

**Comment by jberthold** [comment]
The problem appears to be related to the simplification of terms that involve maps and `Or`. This is a minimised example:
``` 
constructed =
    fromPredicateSorted (mkSort "subOtherSort") $
        makeInPredicate
            ( T.mkNot $ 
                T.mkIff
                    ( T.mkOr
                        (elementMap <something> <something-else>)
                        unitMap
                    )
                    (concatMap
                        ( T.mkOr (opaqueMap "cf") unitMap)
                        ( T.mkOr unitMap (opaque "functional00"))
                    )
            )
            (topTerm "mapSort")
```

**Comment by ana-pantilie** [comment]
We need to rewrite the generators for the property tests, so that it doesn't generate these very general examples we are not interested in supported.

For example, inside collections only generate terms which contain symbol applications.

We need to come up with a specification which details what kind of patterns we want to support.

**Comment by ana-pantilie** [comment]
I think we should just restrict the `TermLike` generator to only generate terms which contain only function/functional/constructor symbol applications or builtins.

That should fix the issues we're seeing with these property tests.

I don't think we see other kinds of terms in practice, let me know if you think this is too restrictive.
