### ISSUE TITLE
Add more details to kore-syntax.md

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/haskell-backend#3249]
### Add more details to kore-syntax.md
This document is a technical specification of kore's grammar. We need to make it more user friendly by adding text which describes what the kore constructs mean. We should also provide examples.

### OUTDATED:

According to the file `definition.kore`:
```
hooked-symbol Lbl'Unds'Map'Unds'{}(SortMap{}, SortMap{}) : SortMap{}
```
But, in the following `krun` output, `Lbl'Unds'Map'Unds'` has 4 arguments:
```
Lbl'-LT-'generatedTop'-GT-'{}(
     Lbl'-LT-'T'-GT-'{}(
          Lbl'-LT-'k'-GT-'{}(dotk{}()),
          Lbl'-LT-'env'-GT-'{}(
              \left-assoc{}(Lbl'Unds'Map'Unds'{}(
                   Lbl'UndsPipe'-'-GT-Unds'{}(inj{SortId{}, SortKItem{}}(\dv{SortId{}}("a")),inj{SortInt{}, SortKItem{}}(\dv{SortInt{}}("5"))),
                   Lbl'UndsPipe'-'-GT-Unds'{}(inj{SortId{}, SortKItem{}}(\dv{SortId{}}("z")),inj{SortInt{}, SortKItem{}}(\dv{SortInt{}}("2"))),
                   Lbl'UndsPipe'-'-GT-Unds'{}(inj{SortId{}, SortKItem{}}(\dv{SortId{}}("y")),inj{SortInt{}, SortKItem{}}(\dv{SortInt{}}("9"))),
                   Lbl'UndsPipe'-'-GT-Unds'{}(inj{SortId{}, SortKItem{}}(\dv{SortId{}}("x")),inj{SortInt{}, SortKItem{}}(\dv{SortInt{}}("5"))))))),
     Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
```

**Comment by ehildenb** [comment]
@amelieled we need more detailed reproduction steps. Can you include the commands run, and ideally a minimized input file which can be run directly with some specific commands to determine the issue. Otherwise we're just guessing about how to reproduce (and thus just guessing about how to fix).

**Comment by dwightguth** [comment]
This is actually fine. See the documentation for \left-assoc

**Comment by ana-pantilie** [comment]
@amelieled @ehildenb This is not a bug, it's a binary symbol which is preceeded by `left-assoc`. This means that the list of arguments will be threaded to the symbol application in a left associative way.

**Comment by amelieled** [comment]
Same in this case?
```
Lbl'-LT-'generatedTop'-GT-'{}(
    Lbl'-LT-'T'-GT-'{}(
         Lbl'-LT-'k'-GT-'{}(dotk{}()),
         Lbl'-LT-'env'-GT-'{}(
             \left-assoc{}(
                 Lbl'Unds'Map'Unds'{}(
                      Lbl'UndsPipe'-'-GT-Unds'{}(inj{SortId{}, SortKItem{}}(\dv{SortId{}}("x")),inj{SortInt{}, SortKItem{}}(\dv{SortInt{}}("1"))))))),
    Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
```

Sorry, @dwightguth but where is the document about `\left-assoc`?

**Comment by amelieled** [comment]
I mean, the document is here: https://github.com/runtimeverification/haskell-backend/blob/master/docs/kore-syntax.md:

```
<pattern>
  ::= <variable-pattern>
    | <matching-logic-pattern>
    | <application-pattern>
    | <string-literal>

<patterns>
  ::= <[pattern]-sep-by-[","]>

<variable-pattern>
  ::= <element-variable>
    | <set-variable>

<element-variable>
  ::= <element-variable-identifier> ":" <sort>

<set-variable>
  ::= <set-variable-identifier> ":" <sort>

<application-pattern> ::=
    <symbol-identifier> "{" <sorts> "}" "(" <patterns> ")"

<multi-or> ::=
    "\or" "{" <sort> "}" "(" <patterns> ")"

<matching-logic-pattern>
  ::=
    // Connectives
      "\top" "{" <sort> "}" "(" ")"
    | ...
    // Syntax sugar
    | "\left-assoc" "{" "}" "(" <application-pattern> ")"
    | "\left-assoc" "{" "}" "(" <multi-or> ")"
    | "\right-assoc" "{" "}" "(" <application-pattern> ")"
    | "\right-assoc" "{" "}" "(" <multi-or> ")"

```
But what is the semantics of a `\or` with only one argument?
And how it is possible to generate one symbol with many different types?

Btw, which attribute generates this `\left-assoc` thing? It's because the `Map` is the K standard library is `assoc`?

**Comment by dwightguth** [comment]
The syntax is documented here: https://github.com/runtimeverification/haskell-backend/blob/master/docs/kore-syntax.md

I'm a little surprised this document doesn't have more details about the meaning of each type of pattern it declares though. @ana-pantilie are these documented elsewhere? If not, we should create a task to add some text to that file, and then link to that file from the k user manual.

**Comment by dwightguth** [comment]
Fwiw this is not a symbol; it's a parser directive.

**Comment by amelieled** [comment]
OK, but according to the grammar, it's ML pattern. So, I'm confused.

**Comment by dwightguth** [comment]
It's a grammar. It defines the syntax of an intermediate language. It doesn't define the semantic concepts of the language that are referred to by the syntactic constructs. Many programming languages have multiple ways of referring to the same piece of code. It's not the responsibility of a grammar to explain what the ast used by the application that parses the grammar looks like.

**Comment by amelieled** [comment]
I don't understand: `\left_assoc` is a ML pattern, but which one?
If it's just a parser indicator, the grammar seems to be incorrect.

**Comment by dwightguth** [comment]
You seem fundamentally confused. It's not my responsibility to explain to you what a grammar. As I said, \left-assoc is not a symbol and it's not part of matching logic, it's a parser directive. Please don't tell me that confuses you because I can't make it any clearer than that. If you're still confused, just wait until we get the documentation written and then read it.
