### ISSUE TITLE
Refactor new pattern matcher and unifier

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3251]
The new pattern matching code is fast, but should be cleaned up. The team has added several suggestions to https://github.com/runtimeverification/haskell-backend/pull/3206, many of which aren't trivial to do. We need to address these concerns.

**Comment by ana-pantilie** [comment]
@dwightguth are you currently doing more work on the pattern matcher? Asking because we want to pick this one up and we don't want to create any conflicts with any work you're currently doing.

**Comment by dwightguth** [comment]
All that's left for me to do is fix the conflict in the GitHub workflow and merge it; I intend to get both those steps done today. Refactor away! Let's just make sure to be careful not to introduce too severe of overhead unless it makes the code significantly easier to understand.
