### ISSUE TITLE
`--bug-report` option does not handle directories for some arguments

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3263]
Blocking: https://github.com/runtimeverification/haskell-backend/issues/3221

I have the following example K definition in file `test.k` (the definition itself doesn't matter):

```
module TEST
    imports INT
    imports BOOL

    configuration <k> $PGM:Contract </k>

    rule <k> Coo(_I) => Boo ... </k>

    syntax Contract ::= Coo ( Int ) | "Boo"

    syntax Bool ::= foo ( Int ) [function, functional, no-evaluators]

endmodule

module TEST-SPEC
    imports TEST

    claim <k> Coo(X) => Boo ... </k> ensures foo(X) andBool notBool foo(X)
endmodule
```

I run the following commands:

```
+ mkdir foo
+ kompile --backend haskell test.k --output-definition test-kompiled
+ export 'KORE_EXEC_OPTS=--log foo/bar.log --log-entries DebugTransition --bug-report test'
+ KORE_EXEC_OPTS='--log foo/bar.log --log-entries DebugTransition --bug-report test'
+ kprove --definition test-kompiled test.k --spec-module TEST-SPEC
```

Note the `mkdir foo` on the first line, and the `--log foo/bar.log` on the `export` line (3rd line).

The resulting `test.tar.gz` bug report has a file `kore-exec.sh` that looks like this:

```
#!/bin/sh
exec kore-exec \
    vdefinition.kore \
    --output result.kore \
    --module TEST \
    --strategy all \
    --max-counterexamples 1 \
    --smt-timeout 40 \
    --smt-retry-limit 1 \
    --smt-reset-interval 100 \
    --smt z3 \
    --log \
    foo/bar.log \
    --log-level \
    warning \
    --enable-log-timestamps \
    --log-entries \
    DebugTransition \
    --prove spec.kore \
    --spec-module TEST-SPEC \
    --graph-search breadth-first \
     \
     \
     \
     \
    "$@"
```

In particular, it contains `--log foo/bar.log`, which means when it's run on someone else's machine, we'll get the following error (because directory `foo` does not exist):

```
+ kprove --definition test-kompiled test.k --spec-module TEST-SPEC                                                                                                                                                   
foo/bar.log: openFile: does not exist (No such file or directory)
```

### Proposed Solution 1

The `--bug-report` option should be aware of which arguments are paths (like the `--log` argument), and should insert `mkdir -p $(dirname ARGUMENT)` before calling `kore-exec` to make sure those directories are existing. In this example, it would insert:

```
mkdir -p $(dirname foo/bar.log)
```

### Proposed Solution 2

The `--log` option should make sure that the directory it's logging to exists, by making that directory and all parent directories.

**Comment by jberthold** [comment]
An additional aspect of this is to keep things safe. Someone could craft a bug report tarball whose command script writes a log to important system files owned by the user (like `--log $HOME/.ssh/config`), or a user could just be stupid and damage his/her own system by accident.
OTOH, tweaking the `--bug-report` option does not mitigate the potential attack.
There might not be a good solution except to just refuse overwriting any existing files (we could suffix the name instead in that case, or stop with an error).

For the `--bug-report` specifically, we can maybe just force all paths to relative and ensure they are contained within the current directory (and create them as outlined above, solution 1)

**Comment by ana-pantilie** [comment]
Change the behavior of `--log filename.log`:
if `filename` == `/path/to/file...`, and the directory doesn't exist or if the file already exists
    then emit a warning, and default to logging everything to `exec-name-timestamp.log`
    else ...

If no `--log` option is given, then don't log to any file.
