### ISSUE TITLE
Unexpectedly marking term with NotSimplified children as simplified

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3285]
I get this error when the program in the attached bug report is run. I'm not entirely sure why this error is occurring. I'd be happy to try to fix it if someone could give me some feedback on what the appropriate steps to debug and fix it are.
[kore-exec.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9667097/kore-exec.tar.gz)

**Comment by ana-pantilie** [comment]
This is the callstack:
```
    CallStack (from HasCallStack):
      error, called at src/Kore/Internal/Predicate.hs:1097:5 in kore-0.60.0.0-ZY6w1dzxVhGc9Fy2XxLI:Kore.Internal.Predicate
      cannotSimplifyNotSimplifiedError, called at src/Kore/Internal/Predicate.hs:1126:36 in kore-0.60.0.0-ZY6w1dzxVhGc9Fy2XxLI:Kore.Internal.Predicate
      checkedSimplifiedFromChildren, called at src/Kore/Internal/Predicate.hs:1136:14 in kore-0.60.0.0-ZY6w1dzxVhGc9Fy2XxLI:Kore.Internal.Predicate
      markSimplified, called at src/Kore/Simplify/Not.hs:150:17 in kore-0.60.0.0-ZY6w1dzxVhGc9Fy2XxLI:Kore.Simplify.Not
```

Notice that it's failing at that line in the `Not` simplifier, you'll need to look at the children of the `Not` and figure out why they're not being marked simplified. Which simplifier do the children come from? That's what should have marked them as simplified in some way or another.

Hope this helps, let me know if you have any questions.
