### ISSUE TITLE
Improvements to the JSON RPC server

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3287]
From the first user experience and bug report related to the RPC server, we could make some small improvements:

- [x] The server should log requests in a compact human-readable format (like a web server logs requests in one line each). This log should probably include hints about the request data (but the full data will be too verbose for standard log level)
- [x] The output json object should have keys sorted for better readability. Currently the application objects (~90% of all terms that will appear in json encoding) have `args` before the rest, making it very hard to read. The `KoreJson` type has a function for pretty-printing json with a key sort order which could be used. https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Syntax/Json.hs#L75..L94
- [x] We should make a test/demo which shows a sequence of executions (each with depth 1), feeding the output state back as input in the next request
- [x] Integration tests should not use the `initGeneratedTopCell` as the start state in exec tests, to be more instructive.

**Comment by goodlyrottenapple** [comment]
I started working on the logging, but because the RPC server is threaded, the logs look like this:

```
kkoorree--rrppcc::  [[66113399339895]]  EDrerbourg  ((LLooggJJssoonnRRppccSSeerrvveerr))::

        [[EDrerbourg##jjssoonn--rrppcc]]  elrirsotre npianrgs ifnogr  ian cnoemwi nrge qmueesssta g@e( j@s(ojns-ornp-cr-p1c.-01..30-.13L-c1RL2c2Rq2C2wq5Cmw25qmC2eqwCAe0wTAi0aTli:aNle:tNweotrwko.rJkS.OJNSROPNCR.PICn.tIenrtfearcfea cser cs/rNce/tNweotrwko/rJkS/OJNSROPNCR/PICn/tIenrtfearcfea.ches.:h2s8:71:0133:)9
)
```

I will have to re-do the logger to run in a separate thread

**Comment by goodlyrottenapple** [comment]
turns out this was already an issue in kore-repl and there is code which wraps any logger into an MVar, which gives us thread safety...
