### ISSUE TITLE
Hook: implement IO.write

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3296]
We need to implement https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#write-to-file. We will probably need to do something a bit hacky to implement this one, as it requires doing IO, so a bit of investigation is required.

**Comment by ehildenb** [comment]
Do we already support the system hooks already: https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#shell-access

If so, then IO.write should be implementable using that directly, though there is probably a more efficient way.

**Comment by ana-pantilie** [comment]
Not that I know of, so this will probably be more involved.
