### ISSUE TITLE
Debugging tool for simplification

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3297]
We can run the prover itself incrementally, by running one rewrite step at a time.

We should architect the new simplifier to be able to do something similar. This will make it much easier for both developers and users to debug the backend/their semantics.

**Comment by ana-pantilie** [comment]
@goodlyrottenapple and @jberthold please add any ideas you have to this issue.

**Comment by jberthold** [comment]
(Summarising points I remember from brainstorming during stand-up:)
* The simplifier iterations are currently not observable , and it is hard to observe the simplifier _alone_ at all.
* As a _debugging tool_ we could think about logging the term during simplifier iterations (where applicable) to a file, similar to the recent change #3284  to log rewrite rule applications to a yaml file.
* A stand-alone tool could consume such a simplificaiton log to display a `diff`-like view of a pretty-printed term
* Both logs (rewriting and simplification) should probably write a combined yaml log file, in order for the tool to identify the execution steps.
