### ISSUE TITLE
Implement the `simplify` endpoint for `kore-rpc`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/haskell-backend#3298]

**Comment by ana-pantilie** [comment]
This should just call the pattern simplifier and return the result.

**Comment by ana-pantilie** [comment]
Blocked on https://github.com/runtimeverification/haskell-backend/issues/3324

**Comment by ana-pantilie** [comment]
Fixed by https://github.com/runtimeverification/haskell-backend/pull/3307
