### ISSUE TITLE
KEVM proof finds terms not function-like after adding simplification rules

### ISSUE THREAD

**Issue by jinxinglim** [runtimeverification/haskell-backend#3302]
[kevm-bug-requires01-a0gt0.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9720697/kevm-bug-requires01-a0gt0.tar.gz)

After adding the following two rules to debug `ecreoverloop00-sig1-invalid-spec`:
```k
// to debug ecreoverloop00-sig1-invalid-spec
rule A  <Int B => #Not ( { true #Equals B <=Int A } ) [simplification]
rule A <=Int B => #Not ( { true #Equals B  <Int A } ) [simplification]
```
one other proof of the KEVM suite, `requires01-a0gt0-spec` fails with the following error:
```
kore-exec: [50075716] Error (ErrorException):
    The check implication step expects the configuration term to be function-like.
      Configuration term:
        /* Sfa */
        Lbl'-LT-'generatedTop'-GT-'{}(
            /* Sfa */
            Lbl'-LT-'kevm'-GT-'{}(
                /* Fl Fn D Sfa */
                Lbl'-LT-'k'-GT-'{}(
                    /* Fl Fn D Sfa */
                    kseq{}(
...
```

When going through the printed configuration, we found a term `\top{SortBool{}}()` which does not have the `Fl Fn D Sfa` attributes, it only has `D Sfa`. 

May I check if `#Not ( ... )` and `\top{SortBool{}}()` are function-like? Based on https://github.com/runtimeverification/haskell-backend/blob/master/docs/glossary.md, "function-like" is defined as "(adjective) A function-like pattern can have at most one value, i.e. it satisfies (∃x . x=φ) ∨ ¬⌈φ⌉.".

**Comment by ana-pantilie** [comment]
There are two problems here:
1. why is `\\top` not function-like?
2. why is `\\top` appearing inside the term? is there a `A  <Int B` inside the term which is getting rewritten to that predicate? shouldn't predicates like this be pushed to the top and moved to the condition part of the configuration?

**Comment by virgil-serbanuta** [comment]
1 - According to the glossary, a function-like pattern can have at most one value. \top{SortBool{}} has two values, true and false.
2 - `<=Int` and `<Int` are `function` and `functional`, which means that the following rules are invalid, since the RHS evaluates to either top or bottom, none of which has exactly one element (top is not function-like, bottom is not functional-like):
```
rule A  <Int B => #Not ( { true #Equals B <=Int A } ) [simplification]
rule A <=Int B => #Not ( { true #Equals B  <Int A } ) [simplification]
```
