### ISSUE TITLE
[Haskell-Performance] Testing for issue 3286 (please ignore)

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3303]
Running a performance test for #3286 

EDITED This is now [the first test tarball (with-conditions)](https://github.com/runtimeverification/haskell-backend/files/9670919/kevm-bug-storagevar03-with-conditions.tar.gz) from #3286

**Comment by jberthold** [comment]
And this is the [first file, kevm-bug-storagevar03-with-conditions.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9670919/kevm-bug-storagevar03-with-conditions.tar.gz)

**Comment by ana-pantilie** [comment]
Retrying automatic profiling: [first file, kevm-bug-storagevar03-with-conditions.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9670919/kevm-bug-storagevar03-with-conditions.tar.gz)

**Comment by jberthold** [comment]
Trying automatic profiling again: [first file, kevm-bug-storagevar03-with-conditions.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9670919/kevm-bug-storagevar03-with-conditions.tar.gz)

**Comment by F-WRunTime** [comment]
[kevm-bug-storagevar03-with-conditions.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9768082/kevm-bug-storagevar03-with-conditions.tar.gz)
