### ISSUE TITLE
Kore.Unification.NewUnifier takes a long time to build

### ISSUE THREAD

**Issue by treeowl** [runtimeverification/haskell-backend#3305]
I find it takes multiple minutes, even with `-O0`. Is there something to be done about that? I haven't dug into whether it takes a long time to typecheck or if something else is going on, but it's not wonderful.

**Comment by jberthold** [comment]
Seriously _minutes_ ? (I am compiling the entire project in <3min) However, this module is a noticeable bottleneck.

**Comment by treeowl** [comment]
Yes. My computer isn't very speedy.

**Comment by ehildenb** [comment]
What perccentage of the overall time is it?

May be worth investigating further what's taking time, Haskell backend compile times are a frequent complaint among K devs.

Also, make sure that new issues get added to the K development project board.

**Comment by treeowl** [comment]
I don't know about the percentage. Is there an easy way to get Cabal or Stack to tell me that? I just know it takes a long time, and seems to take many times as long as any other module. I haven't learned how to use the development board yet.

**Comment by ana-pantilie** [comment]
We probably would need to do https://github.com/runtimeverification/haskell-backend/pull/3304 first before we can think about how to split this module up to improve build performance times
