### ISSUE TITLE
Audit \\ceil simplification

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3309]
Several experiments have shown that the backend relies on "ceil magic" internally. This is the list of experiments we ran so far, and they either result in the backend looping or the backend returning very wrong results:
- https://github.com/runtimeverification/haskell-backend/pull/3304
- disabling `\\ceil` simplification from inside the code (which means making `\\ceil` simplify to `\\top`)
- adding `rule #Ceil(_:K) => #Top [simplification(20)]`

In order to make progress on https://github.com/runtimeverification/k/issues/2943 or on other attempts to do `\\ceil` evaluation ahead of time, we need to audit internal calls to the `\\ceil` simplifier and replace them with more appropriate procedure calls, or user-defined rules.

Call sites of the `\\ceil` simplifier and of `\\ceil` builders:

- [x] [The Predicate simplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Simplify/Predicate.hs#L465): this is ok, it's when we traverse the predicate and apply each connective simplifier
- [x] [The Floor simplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Simplify/Predicate.hs#L489): why do we need `\\floor` simplification? we need to see where else this one is called
- [ ] [The In simplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Simplify/In.hs#L33): `\\in` is essentially one of the ways of encoding unification in ML, so we could try to just call the unification procedure directly here; equation application and `checkImplication` are two places which heavily rely on `\\in` simplification, so if anything breaks there's a chance it's related to these uses
- [x] [Kore.Rewrite.Remainder](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Rewrite/Remainder.hs#L136): is this actually used anywhere? it might be dead code?
- [ ] [The unification procedure](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Unification/Procedure.hs#L70): not sure I understand the logic behind this one, why are we doing `\\ceil(t1 /\ t2)` (which is basically unification all over again)? we've already unified the two terms, right?
- [ ] [The Equals simplifier](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Simplify/Equals.hs): this one makes extensive use of both `makeEvaluateCeil` and `makeEvaluateTermCeil`, we need to understand why and how we can get rid of these calls
- [ ] [Kore.Simplify.AndTerms](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Simplify/AndTerms.hs): contains calls to `makeEvaluateTermCeil`, I think this code is the "old unifier" that @dwightguth was unable to replace the usage of when he made the new implementation; not sure what to do about this one
- [ ] [Kore.Builtin.Map](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/Map.hs#L756): this is related to map unification, it's probably necessary to ensure definedness here, we might want to replace this one with `makeCeilPredicate` to allow the `Predicate` simplifier to simplify it?
- [x] [Kore.Builtin.AssocComm.CeilSimplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs#L35): this one is fine because it's part of the `\\ceil` simplifier
- [x] [Int evaluator](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/Int.hs#L390): this one is fine
- [ ] [KEqual evaluator](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/KEqual.hs#L277): hmm, this one is dubious because it calls `\\ceil(\\and(...))`, so it might actually rely on unification
- [x] [Map evaluator](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/Map.hs#L367): this one is fine
- [x] [Kore.Reachability.Claim](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Reachability/Claim.hs#L109): probably ok
- [x] [Kore.Rewrite.AntiLeft](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Rewrite/AntiLeft.hs#L388): is this dead code?
- [x] [The matcher](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Rewrite/Axiom/Matcher.hs#L477): this one is fine
- [x] [Pattern simplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Simplify/Pattern.hs#L84): this one is fine
- [ ] [The new unifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Unification/NewUnifier.hs#L770): again, this is encoding unification, why is this needed?
- [x] [Kore.Builtin.AssocComm.CeilSimplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs#L24): this one is fine
- [x] [Predicate simplifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Simplify/Predicate.hs#L533): I believe this one is alright

Possible solutions to some of the problems above:
- detect whether there are any `\\ceil(\\and(term1, term2))` inside the pattern and simplify them by calling the unification procedure directly

**Comment by ana-pantilie** [comment]
> As per the docs in the module, the in simplifier only performs the following:

I don't think that's right, the `\\in` simplifier does this: https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Simplify/In.hs#L96

Might be worth trying to replace it with the unification procedure maybe?

**Comment by goodlyrottenapple** [comment]
ah you are right. i was thinking i migth open a new branch and make commits for each of the changes, e.g removing the dead code, replacing the ceil simplifier with the unifier above, etc. then running the kevm profile after each change for correctness and performance stats. we could then cherry pick which commits to keep?

**Comment by goodlyrottenapple** [comment]
should this maybeTermEquals be in Kore.Simplify.Equals?

**Comment by goodlyrottenapple** [comment]
- [KEqual evaluator](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Builtin/KEqual.hs#L277): hmm, this one is dubious because it calls `\\ceil(\\and(...))`, so it might actually rely on unification
- [The new unifier](https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Unification/NewUnifier.hs#L770): again, this is encoding unification, why is this needed?

**these are the exact same code, namely, checking the condition in an `#if_#then_#else` evaluates to true or false. Not sure how to remove other than the suggested change:**

https://github.com/runtimeverification/haskell-backend/blob/9cb95b15504016b858bf586a4a773b494d0342fd/kore/src/Kore/Unification/NewUnifier.hs#L637-L640

**Comment by ana-pantilie** [comment]
One other thing is that we need to replace the old unifier with the new one everywhere.

**Comment by dwightguth** [comment]
As far as the old unification algorithm goes, the same basic principle applies; I would be ecstatic if it could be replaced with the new unifier, but I spent a huge amount of time on it and was unable to get a version that passed tests, so eventually I gave up. You might have more success, hopefully.

**Comment by ana-pantilie** [comment]
Thanks for the response @dwightguth !
