### ISSUE TITLE
Remove Jenkins jobs

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3324]
We already run the integration tests in GitHub workflows, and we also run the unit tests using both Stack and Cabal in separate workflows as well. We should remove the jobs which do the same things on Jenkins.

Also take a look at:
- [x] rename workflows to be more descriptive
- [x] we shouldn't be building twice in the Stack unit test workflow
- [x] ~what does the documentation stage in the Jenkins pipeline do? do we need to add a new workflow which does the same thing?~ add Haddock pass in parallel
- [ ] check if the K release upgrade is defined in the same Jenkinsfile, if yes we need to migrate that as well

**Comment by goodlyrottenapple** [comment]
Still need to migrate some jobs from Jenkins
