### ISSUE TITLE
Serokell: nested `UnifierT`s

### ISSUE THREAD

**Issue by breakerzirconia** [runtimeverification/haskell-backend#3362]
The analysis was conducted by @treeowl and @breakerzirconia, in the branch called [nested-unifiers](https://github.com/runtimeverification/haskell-backend/tree/nested-unifiers), which serves a purely investigative purpose.

Here are the steps we took during the investigation of the source of the `UnifierT` nesting:
1. We created a closed type family `NotUnifierT`. It is defined in `Kore.Unification.NotUnifierT`. It accepts a type parameter `m` and returns a custom `TypeError` if `m` is `UnifierT`; otherwise, returns the always satisfiable trivial constraint `()`. The type error says 
`Should not be UnifierT \n <actual_type>`.
2. We modified the `MonadUnify (UnifierT m)` instance as follows: 
`instance (MonadSimplify m, NotUnifierT m) => MonadUnify (UnifierT m)` (we added a `NotUnifierT m` constraint). 
This means if `m` is `UnifierT`, then the type we're working in is `UnifierT (UnifierT m)`, which exactly represents the situation we're trying to catch (i.e. at least one level of nesting), and we get our custom type error.
3. The `NotUnifierT` constraint needed to be propagated to a subset of the functions in the `Kore.Simplify.*` modules due to the presence of that constraint in the `MonadUnify (UnifierT m)` instance.
4. The imports of `NotUnifierT` created circular dependencies in certain modules, so we isolated the relevant declarations/definitions in the `hs-boot`-files both for `Kore.Unification.UnifierT` and `Kore.Unification.NotUnifierT`, breaking circular dependencies in relevant places by `{-# SOURCE #-}`-importing these modules.

Fortunately, after inserting the constraint in the appropriate type signatures we came across our first occurrence of the custom type error in `Kore.Simplify.Not`:
![image](https://user-images.githubusercontent.com/40356589/201369350-8b342220-0a24-4e5d-bd31-c9ce605fbb4a.png)

`Kore.Simplify.Not.notSimplifier` is defined as follows:
```
notSimplifier :: (MonadSimplify simplifier, NotUnifierT simplifier) => NotSimplifier simplifier
notSimplifier = NotSimplifier simplify -- this 'simplify' is the one defined in Kore.Simplify.Not and represents the simplification of a 'Not' pattern
```
`mkMultiAndPattern` invokes `Kore.Simplify.And.makeEvaluate`, whose type signature is
```
makeEvaluate ::
    forall simplifier.
    (HasCallStack, MonadSimplify simplifier, NotUnifierT simplifier) =>
    Sort ->
    NotSimplifier (UnifierT simplifier) -> -- !
    SideCondition RewritingVariableName ->
    MultiAnd (Pattern RewritingVariableName) ->
    LogicT simplifier (Pattern RewritingVariableName)
```
As you can see in this example, `makeEvaluate` accepts a `NotSimplifier (UnifierT simplifier)`, supposedly introducing an extra `UnifierT` layer.

So far, the following `Should not be UnifierT` type errors can be observed in the `nested-unifiers` branch:
* `Kore.Simplify.Not.mkMultiAndPattern:205:60`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Simplify.And.makeEvaluate`.
* `Kore.Simplify.Implies.distributeEvaluateImplies:132:24`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Simplify.And.simplify`.
* `Kore.Simplify.Iff.simplifyEvaluated:100:32`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Simplify.And.simplify`.
* `Kore.Simplify.In.makeEvaluateIn:98:36`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Simplify.And.makeEvaluate`.
* `Kore.Simplify.Equals.termEqualsAnd.run:433:22`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Unification.UnifierT.runUnifierT`.
* `Kore.Simplify.Equals.makeEvaluate:310:36`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Simplify.And.simplify`.
* `Kore.Simplify.Equals.makeEvaluateFunctionalOr:242:28`
  * in `Kore.Simplify.Not.notSimplifier`, which is passed to `Kore.Simplify.And.simplify`.

**Comment by ana-pantilie** [comment]
Remove `UnifierT` from https://github.com/runtimeverification/haskell-backend/blob/874ca3461c907d23471f5d1b18d031a63f76d4be/kore/src/Kore/Simplify/And.hs#L224 and see what breaks, so that we understand why we need this type there.

From @ehildenb : let's see where we're at regarding the performance issues
