### ISSUE TITLE
Remove circular imports when possible

### ISSUE THREAD

**Issue by treeowl** [runtimeverification/haskell-backend#3379]
Circular imports can seriously limit compiler optimizations. They also complicate code maintenance. If feasible, it would be best to remove them all. If not, the exact locations of cycle-breaking `{-# SOURCE #-}` imports should be considered very carefully.

**Comment by ana-pantilie** [comment]
I believe getting rid of the old unifier (`UnifierT`) will remove many of these cyclic imports.

**Comment by ana-pantilie** [comment]
Related: we added `NotSimplifier` in the past to remove some cyclic dependency the `And` simplifier and the `Not` simplifier. Maybe we can do something similar to remove other circular imports? That might have performance benefits.

**Comment by ana-pantilie** [comment]
https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Simplify/Predicate.hs-boot

**Comment by treeowl** [comment]
I've looked into this some, and ... it really is a mess. There's just the one `SOURCE` import, but there seem to be multiple "reasons" for cycling, i.e., multiple import paths that all cycle through that point. We might be able to do something like the `NotSimplifier` trick for other things too (e.g., add an `AndSimplifier`). If we make them all classes, then hopefully GHC will specialize them eventually. That specialization can only happen where the (orphan) instances are visible, of course. If we choose do go down that path, it would probably make sense to have a single module that all the weird stuff funnels through, which can define all the orphan instances. Then modules can import that to provide the public API, hopefully specialized. But ... I can definitely see why @ana-pantilie is skeptical now.

**Comment by ana-pantilie** [comment]
We will first do https://github.com/runtimeverification/haskell-backend/issues/3422 and re-evaluate how hard this issue is to do afterwards.
