### ISSUE TITLE
Weird return sort from RPC server

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3383]
I'm about to write some (not-pretty) pyk code to deal with `JSONSortVariable`, introduced here: https://github.com/runtimeverification/haskell-backend/blob/bc49fae4aef4c16534636313381a587126e82d84/kore/src/Kore/Syntax/Json.hs#L133

It seems to me that this should be `SortGeneratedTopCell` instead, because this substitution is a conjunct of equalities that would be added to the side-condition of a given term.

Anyway, do we know that this name won't be used by anything? I guess it should be distinct from any other sort names because the sort names get prefixed with `Sort` before going to the backend. But it still seems like not-great practice.

**Comment by ana-pantilie** [comment]
@jberthold suggests we use the sort of the adjacent term.
