### ISSUE TITLE
Validate user options

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3410]
Suggested by @radumereuta
Radu: This started from an error Alexey ran into: https://runtimeverification.slack.com/archives/C03ER623BS4/p1671002632034109
By using `KORE_EXEC_OPTS='--debug-equation ToDebug'` he didn't get the expected behavior.
It turned out that labels needed the module name prefixed.

The haskell tools should validate all the input given by the user and fail with a descriptive error message.

It saves users a lot of time in the long run and it boosts confidence in the tool.

**Comment by treeowl** [comment]
@ana-pantilie I can look at the code, but I don't have access to the linked Slack thread. Could the relevant portions be copied to the ticket?

**Comment by radumereuta** [comment]
You should see the message from Alexey from Dec 14, 2022 in the #serokel-rv channel.
But the issue has a broad scope. Everything that can be specified by the user as a command line option or through environment variables should be validated.

Here are some options I added for the front-end: https://github.com/runtimeverification/k/pull/2834
