### ISSUE TITLE
Warn users when the LHS of a claim is undefined

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3411]
- [ ] Add an `--allow-vacuous` flag to `kore-exec` and `kore-repl`
- [ ] Add a new case in https://github.com/runtimeverification/haskell-backend/blob/bb2de5009a218b54a0efc668357854c10d3f05cb/kore/src/Kore/Log/WarnStuckClaimState.hs#L27 called `BottomLHS`. Its `Pretty` instance should print out the source location and some text indicating that the left hand side of the claim has been simplified to `\\bottom`
- [ ] In https://github.com/runtimeverification/haskell-backend/blob/bb2de5009a218b54a0efc668357854c10d3f05cb/kore/src/Kore/Reachability/Claim.hs#L341, implement the following logic:
```
Transition.ifte
    (simplify ...)
     ...
     (
          if --allow-vacuous is turned on
              then pure Proven
              else warnStuckClaimStateBottomLHS claim >> pure Stuck
    )
```

See also draft branch https://github.com/runtimeverification/haskell-backend/pull/3412

This can be tested on `KEVM Foundry` (from @ehildenb ):
- repository https://github.com/runtimeverification/evm-semantics
- `AddrTest.test_addr_true` seemed to reach `#Bottom` about 269 steps in when invoking this rule: https://github.com/runtimeverification/evm-semantics/blob/master/include/kframework/foundry.md#addr---computes-the-address-for-a-given-private-key
- You can invoke it probably by doing something like: make test-foundry on KEVM, killing it once it's reached past the kompile phase, and then running kevm foundry-prove tests/foundry/out --test AddrTest.test_addr_true,
- Or by using this doit script:
```
set -euxo pipefail

# you made changes to KEVM and want to restart
clean() {
    rm -rf ${foundry_out}
    (   cd $(dirname ${foundry_out})
        forge build
    )
}   

# You made changes to on-disk pyk and are using that
update_pyk() {
    # cd kevm-pyk
    # poetry update
    # git add poetry.lock
    # git commit -m '!!! kevm-pyk/poetry.lock: update'
    # cd ..
    make venv -B
}

build() {
    kevm kompile --backend foundry                        \
        .build/usr/lib/kevm/include/kframework/foundry.md \
        --main-module FOUNDRY                             \
        --syntax-module FOUNDRY                           \
        --pyk --verbose --profile
}

foundry_kompile() {
    kevm foundry-kompile ${foundry_out} --verbose   \
        ${rekompile} ${regen} "$@"
}

foundry_prove() {
    kevm foundry-prove ${foundry_out}      \
        --profile --verbose ${debug}       \
        --test ${test}                     \
        ${simplify_init}                   \
        ${reinit}                          \
       --max-depth ${max_depth}            \
       --max-iterations ${max_iterations}  \
        ${break_every_step}                \
        ${implication_every_block}         \
        ${auto_abstract}                   \
        "$@"
}

foundry_show() {
    kevm foundry-show ${foundry_out} ${test} "$@"
}

foundry_out=tests/foundry/out

test=OptimismPortal.depositTransaction
test=AssumeTest.testAssume
test=DynamicTypes.test_dynamic_byte_read
test=StoreTest.testGasLoadWarmUp
test=AccountParamsTest.testNonceSymbolic
test=StoreTest.testGasLoadWarmUp
test=EmitContractTest.testExpectEmit
test=AssertTest.test_assert_true_branch
test=AddrTest.test_addr_true
test=subdir/AssertTest.test_assert_true_subdir
test=LoopsTest.testSumToN
test=AddrTest.test_addr_true

regen=
regen=--regen

rekompile=
rekompile=--rekompile

# switch order to resume instead of restarting
reinit=--reinit
reinit=

# probably mostly leave alone
simplify_init=
simplify_init=--no-simplify-init

max_depth=300
max_iterations=100

debug=--debug
debug=

auto_abstract=--auto-abstract
auto_abstract=

break_every_step=--break-every-step
break_every_step=

implication_every_block=--implication-every-block
implication_every_block=

. .build/venv/bin/activate
export PATH=$(pwd)/.build/usr/bin:$PATH

# Uncomment these lines as needed
# pkill kore-rpc || true
# clean
# update_pyk
# foundry_kompile

foundry_prove

foundry_show
```

**Comment by ehildenb** [comment]
The prover is checking implication by doing `current_term - target_term`, and trying to show that this goes to `#Bottom`. This has the benefit of removing intermediate states that have already reached the target (so they do not continue symbolic execution).

Unfortunately, this also means that if simplification results in a `#Bottom` term, then the proof is discharged. This is _usually_ not what the user intends with the proof they write, where they expect that at least some path of execution reaches the target.

But sometimes this is needed (@virgil-serbanuta has some uses), so we need a flag.

New behavior:

- By default, if simplification results in `#Bottom`, return `#Bottom` to the user, not `#Top`.
- Add a flag `--allow-vacuous` which enables discharging `#Bottom` paths as `#Top` at implication checking time instead.

**Comment by ana-pantilie** [comment]
See https://github.com/runtimeverification/haskell-backend/pull/3438
