### ISSUE TITLE
Warn the user if a rewrite step takes longer than average

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3417]
This warning should contain as much information as possible about the state the backend was in and what it used to take the specific step. We need to figure out how to measure this inside the execution monad and make sure that we have enough context to show to the user. **High priority**

**Comment by jberthold** [comment]
Ideas:
* Easiest solution would be a user-defined threshold duration, and measuring how long each step takes (the operation runs in `IO` anyway). A warning can be emitted if the measured duration is longer than the threshold.
* More complicated, compute the average of "rewrite step" executions so far and report outliers.
* The total duration of the rewrite step could be broken down into different sub-steps if the total exceeds the threshold.
* Additional information should be added to the warning to hint at what exactly is slowing things down (the configuration should be included, possibly at a different log level or into a dedicated file -> see rewrite logging into a yaml file)

**Comment by ana-pantilie** [comment]
First prototype: in the kore-repl, when stepping (with `step n` or `stepf n`) if any rewrite step takes longer than a user-provided threshold (both as CL option and as repl command), stop the execution at that particular step and warn the user.

Next, as @Sereja313 suggested we could try to measure and dump rewrite step lengths for kore-exec and run this on the KEVM benchmarking suite we have. This could give us some statistics on how long rewrite steps usually take.

**Comment by ana-pantilie** [comment]
@Sereja313 One feature which was just requested by our users is adding a repl command/option which switches on printing the timing information for each step. Could you look into adding this as well?

**Comment by goodlyrottenapple** [comment]
we should use moving/rolling average for the threshold. this will mean adding a state/mvar to hold the previous value.

**Comment by ana-pantilie** [comment]
Fixed by #3471
