### ISSUE TITLE
[Optimism/KEVM] ByteArray concat simplification breaks back-end

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3429]
In the context of the Optimism engagement, the following simplification
```
rule 
  { BA1:ByteArray #Equals BA2:ByteArray } =>
    { concatHead(BA1):ByteArray #Equals concatHead(BA2):ByteArray } #And 
    { concatTail(BA1):ByteArray #Equals concatTail(BA2):ByteArray }
  requires 
    #sizeByteArray(concatHead(BA1)) =/=K #sizeByteArray(BA1) 
    orBool #sizeByteArray(concatHead(BA2)) =/=K #sizeByteArray(BA2)
  [simplification]
```
breaks the backend with the message
```
    kore-exec: [5500634] Error (ErrorException):
    Could not make sort
        SortBool{}
    match sort
        SortBytes{}
    This is a program bug!
```

The two functions that it uses, `concatHead` and `concatTail`, operate on KEVM ByteArrays and are defined as follows:
```
                         // Leftmost operand in a concat
    syntax ByteArray ::= concatHead(ByteArray) [function, total]
                         // Rest of concat
                       | concatTail(ByteArray) [function, total]

    rule concatHead(BA1 ++ _) => concatHead(BA1) [simplification(40)]
    rule concatHead(BA)       => BA              [simplification    ]

    rule concatTail(BA1 ++ BA2) => concatTail(BA1) ++ BA2 [simplification(40)]
    rule concatTail(_)          => .ByteArray             [simplification    ]
```

The problem should be reproducible by checking out the `foundry-tests-calldata-petar` branch of the [Optimism audit repo](https://github.com/runtimeverification/_audits_Ethereum-optimism_optimism), uncommenting the above simplification in the [lemma file](https://github.com/runtimeverification/_audits_Ethereum-optimism_optimism/blob/foundry-tests-calldata-petar/optimism_foundry/optimism-lemmas.k) and then executing:
```
cd optimism_foundry
forge b
./run-prove-lemmas.sh
```

**Comment by ana-pantilie** [comment]
@PetarMax please also generate a bug report and attach here.

**Comment by PetarMax** [comment]
Yes, here it is.
[kore-exec.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10373765/kore-exec.tar.gz)
