### ISSUE TITLE
[Optimism/KEVM] `#range` simplification does not get applied

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3432]
The simplification 
```
    // Starting position zero, width less than length of head of concat
    rule [range-includes-concathead]:
         #range(M, 0, WIDTH:Int) => #range(concatHead(M), 0, WIDTH)
         requires #sizeByteArray(concatHead(M)) =/=Int #sizeByteArray(M)
          andBool WIDTH <Int #sizeByteArray(concatHead(M))
         [simplification]
```
does not get applied when proving a claim, but should. The bug report is here: [bug-report.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10383631/bug-report.tar.gz)

To reproduce the issue, check out the `foundry-tests-calldata-petar` branch of the [Optimism audit repo](https://github.com/runtimeverification/_audits_Ethereum-optimism_optimism) and then execute the following:
```
cd optimism_foundry
forge b
kevm foundry-kompile out --require "../../optimism-lemmas.k" --module-import OPTIMISM-LEMMAS --rekompile --verbose --regen 2>&1 | tee kompile.log
kevm foundry-prove out --test CalldataSpec.test_depositTransaction_emit_creationTrue_sender_Equals_origin --no-simplify-init --no-minimize --verbose    
```
stopping the execution when the `kprove` command is written out on the screen, and then taking the first invariant from [this file](https://github.com/runtimeverification/_audits_Ethereum-optimism_optimism/blob/foundry-tests-calldata-petar/optimism_foundry/test/simplified/calldata/invariants.k), removing the `trusted` modifier, and adding it to `out/specs/calldataspec-test-deposittransaction-emit-creationfalse-sender-notequals-origin-spec.k` (possibly deleting the claim already there or marking it as trusted), and running
```
kprove out/specs/calldataspec-test-deposittransaction-emit-creationfalse-sender-notequals-origin-spec.k --definition out/kompiled --spec-module CALLDATASPEC-TEST-DEPOSITTRANSACTION-EMIT-CREATIONFALSE-SENDER-NOTEQUALS-ORIGIN-SPEC --output json --debugger --debug-script kscript
```
where the `kscript` and `print` files are attached and should be pasted into the `optimism_foundry` folder after removing the `.txt` extension (added because the files couldn't otherwise be attached to the issue).

[kscript.txt](https://github.com/runtimeverification/haskell-backend/files/10383689/kscript.txt)
[print.txt](https://github.com/runtimeverification/haskell-backend/files/10383694/print.txt)

**Comment by ana-pantilie** [comment]
@jberthold please run the KEVM performance tests on https://github.com/runtimeverification/haskell-backend/pull/3439
