### ISSUE TITLE
kore-repl config pretty printer should be configurable

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/haskell-backend#3434]
kore-repl config should be able to pretty print K and avoid certain parts or include other parts

When you explore a proof with kore-repl the `config` option should allow you to somehow specify what parts of the configuration you what to show, or what parts you want to hide.
Just a suggestion would be to have two optional parameters `include` and `exclude` that can take a list of klabels, or cell names
```
config include k,mem,env exclude stack,threads
```

Another useful thing would be to have a way to diff the previous printed configuration:
```
config diff
```
This should show only the parts that changed from the previous call to `config`. That would mean we need to store the full output of the previous call to `config`.

For debugging purposes, you could also add a `konfig` option to print the kore format. Or `config kore`...

The first implementation shouldn't be perfect, just add the functionality in the quickest way possible just so we can test it and see what works and how we can improve it.

**Comment by goodlyrottenapple** [comment]
@radumereuta Does kore-print have this option already? The best place to implement this filtering would be in the pretty-printer, so as to avoid the hacky approach of trying to truncate kore, whilst keeping the input to the pretty-printer valid.

**Comment by radumereuta** [comment]
I'm not sure, but I agree it might be the best place to do this filtering.

**Comment by ana-pantilie** [comment]
Does it even make sense to work on this if we're planning on deprecating the kore-repl? If an auditor asks for this feature directly then we can prioritize, otherwise we should leave this feature to the new tooling.
