### ISSUE TITLE
Add new modules on the fly to rpc-server

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3444]
WIP issue:

- Add a new module with new rules via rpc call `add-module`. New module must only import modules already loaded in the backend.
- Change the existing RPC calls to take a `module` parameter, which always defaults to the main module, but can be set to any module they added on the fly.

Needed for:

- Circularities.
- Speeding up proofs with sub-executions.

**Comment by ana-pantilie** [comment]
Discussed with @ehildenb:
- modules will only contain rewrite rules or simplification rules
- pyk will be using this functionality _internally_, and it is relying on the modularity and immutability of modules

Now, regarding implementation, https://github.com/runtimeverification/haskell-backend/blob/c3a2614e132efe1abe85b806791c2dd27f65329c/kore/src/Kore/IndexedModule/IndexedModule.hs#L140 forms a tree of `IndexedModule`s, and I think that the top one is the main module. So we would need to properly insert the new module inside this tree, and switching to a different main module means looking at the subtree with the new main module at the top. Does this make sense or am I misinterpreting the code? @jberthold @goodlyrottenapple

**Comment by ana-pantilie** [comment]
We will be receiving Kore in textual format in order to not have to come up with a JSON encoding for modules yet. So the endpoint will need to parse those.

We also need to come up with some integration tests.
