### ISSUE TITLE
RPC server: better documentation of `implies`

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/haskell-backend#3445]
The documentation of `implies` [here](https://github.com/runtimeverification/haskell-backend/blob/2550e47d97c87f9b2354164b885a57af64fee3ee/docs/2022-07-18-JSON-RPC-Server-API.md) talks about substitution:
> The endpoint simplifies antecedent and consequent terms and checks whether the implication holds. The simplified implication is returned (as a KORE term) in field implication.
> If the implication holds, satisfiable is true and condition contains a unifying condition for the simplified antecedent and consequent (as provided in implication).
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "implication":  {"format": "KORE", "version": 1, "term": {}},
    "satisfiable": true,
    "condition": {
      "substitution": {"format": "KORE", "version": 1, "term": {}},
      "predicate": {"format": "KORE", "version": 1, "term": {}}
    }
  }
}
```
But what does the substitution mean? As witnessed by [this test-case](https://github.com/runtimeverification/haskell-backend/blob/2550e47d97c87f9b2354164b885a57af64fee3ee/test/rpc-server/implies/implied-substitution/README.md),
the consequent can be existentially quantified. But substitution has no effect on quantified-enough formulas. Clearly, from the test-case, the meaning of the 'substitution' field is something like: "if you instantiate the quantifiers in the consequent with these values, then the implication holds". But the documentation does not say that aloud. It also does not hint the user that he can existentially quantify the RHS. Furthermore, the term 'substitution' has a different meaning than 'stuff we use to instantiate existential quantifiers'. For the second, maybe the term 'witness' can be used?

If this sounds confusing, that is because I am confused :) . What I want to say is that I would like to have a better documentation for the `implies` request.

**Comment by goodlyrottenapple** [comment]
We discussed this and you are right that the naming could be better and use witness instead of substitution. The term substitution comes from a field in the internal data-structures. The `substitution` field appears in other end-points like execute within slightly different context (probably not for a very good reason either) .
