### ISSUE TITLE
KEVM performance comparison job is broken

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3450]
I am trying to run the `/KEVM-perf-run` job on https://github.com/runtimeverification/haskell-backend/pull/3439 and it keeps breaking (it happens on other PRs as well). The reason why it breaks seems to change and most of the time the error given back is very opaque. There is also the issue that once the job fails it does not return partial results, and I think it should because it's a pretty long-running job and partial results can be helpful.

**Comment by ana-pantilie** [comment]
@jberthold has found that some KEVM tests have recently started failing with newer versions of the Haskell backend: https://github.com/runtimeverification/haskell-backend/pull/3439#issuecomment-1400923982

This might be the reason why the job is failing.

**Comment by ana-pantilie** [comment]
@jberthold has also observed that the latest master is slower than before, so we suggest that this check should be done weekly to quickly spot regressions.

**Comment by F-WRunTime** [comment]
This is in the devops backlog. I propose we close it. It appears outdated and maybe other solutions have already addressed this? @ana-pantilie

**Comment by jberthold** [comment]
OK by me to close this issue as "won't fix".
That setups like this one keep breaking is unfortunate but probably unavoidable given our current development workflows and repository interactions.
