### ISSUE TITLE
Slowdown in KEVM due to program size

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3454]
The symbolic execution in the backend slows down depending only on the size of the supplied EVM program. As the EVM program, represented by a `ByteArray`, is always concrete and the only operation done on appears to be extraction of sub-arrays, this behaviour is unexpected.

[report-large.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10480923/report-large.tar.gz)
[report-small.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10480924/report-small.tar.gz)

**Comment by ehildenb** [comment]
@PetarMax does this slowdown manifest deep into execution or just on the first execution step?

**Comment by PetarMax** [comment]
Immediately and severely, from the first step.

**Comment by ehildenb** [comment]
And it's slower every step after that as well? Or just slower in that first step?

**Comment by PetarMax** [comment]
It's slower in the first ten steps, run manually.

**Comment by ehildenb** [comment]
Right, but what I'm asking is:

- Is it just step 1 that is slower, and the rest of the steps are the same (step 2 is the same speed on both setups), or
- Is _every_ step also slower.

Eg, total times:

n | small | big
1 | 5s    | 20s
2 | 7s    | 22s
3 | 9s    | 24s

...

If it's only slowing down the first step, it's just initial configuration simplification. You can find out by running to `--depth N` for each one, and posting a table like the above.

If it's _even_ slower every subsequent step as well, then it's somethig we should investigate.

**Comment by PetarMax** [comment]
Step 1 is slower than the other steps of the same setup, for both setups.
These are the initial simplifications.

The steps after seem to have similar speeds of execution per setup. I can
check when back with laptop.

Every step of the small setup is substantially faster than its
corresponding step of the big setup. This is the slowdown that I was hoping
to investigate right now.

I don't know for sure if there would be additional slowdown per setup as
the execution continues. My intuition is yes due to running the small
example to completion over 50K+ steps. The gas cell gets extremely
complicated, for example, but I have ways of simplifying it, now that I
know what it is.
