### ISSUE TITLE
Potential unsoundness when concatenating a cell into a MapCell whith a duplicate key

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/haskell-backend#3464]
This is a minimized example from [avm-semantics](https://github.com/runtimeverification/avm-semantics).

As I understand, my proof reaches `#Bottom` and the becomes proven when trying to *concatenate* (not insert) a cell into a `multiplicity="*" type="Map"` cell collection with the key that is already in the map. The cell is created beforehand and stored in a `List`, see the `prepareTransaction` rule. The problem manifests when the cell is transferred from the list into the map cell by concatenation, see the `submitTransaction` rule. 

This behavior may be correct form the Matching Logic theory point of view (see this [slack threrad](https://runtimeverification.slack.com/archives/CC360GUTG/p1670962272230079)), but it is not something I'd expect as a user. Instead, I'd want the prover to get stuck or at least emit a warning. Is this a soundness bug or is my understanding flawed?

To reproduce:

Versions
------------

kompile:
```
K version:    v5.5.68
Build date:   Thu Jan 26 09:17:31 CET 2023
```

kore-exec:
```
Kore version 0.60.0.0
Git:
  revision:     5b972c3bde441694e10a150d2eb5fc1a029274bb
  branch:       HEAD
  last commit:  Mon Jan 9 08:46:23 2023 -0700
```

Files
------

map-collection.k
```
module MAP-COLLECTION
  imports INT
  imports STRING
  imports LIST

  configuration
    <k> $PGM:Pgm </k>
    <innerTransactions> .List </innerTransactions>
    <transactions>
      <transaction multiplicity="*" type="Map">
        <txID> 0:Int </txID>
        <txBody> "":String </txBody>
      </transaction>
    </transactions>
    <nextTxID> 0:Int </nextTxID>

  syntax Pgm ::= prepareTransaction(String)
               | submitTransaction()
               | Pgm ";" Pgm [left]

  rule <k> X:Pgm ; Y:Pgm => X ~> Y ... </k>

  rule <k> prepareTransaction(V) => .K ... </k>
       <innerTransactions>
         OTHER_TXNS
         =>
         OTHER_TXNS
         ListItem(
           <transaction>
             <txID> 0 </txID>
             <txBody> V </txBody>
           </transaction>
         )
       </innerTransactions>

  rule <k> submitTransaction() => .K ... </k>
       <innerTransactions>
         OTHER_TXNS
         ListItem(
           <transaction>
             <txID> 0 </txID>
             <txBody> V </txBody>
           </transaction>
         )
         =>
         OTHER_TXNS
       </innerTransactions>
       <transactions>
         (.Bag =>
         <transaction>
           <txID> TXN_ID </txID>
           <txBody> V </txBody>
         </transaction>)
         _TXNS
       </transactions>
       <nextTxID> TXN_ID => TXN_ID +Int 1 </nextTxID>

endmodule
```

map-collection-spec.k
```
module MAP-COLLECTION-SPEC
  imports MAP-COLLECTION

  claim <k> prepareTransaction("b"); submitTransaction() => .K </k>
        <innerTransactions>
          .List
        </innerTransactions>
        <transactions>
          <transaction>
            <txID>
              0
            </txID>
            <txBody>
              "a"
            </txBody>
          </transaction>
        </transactions>
        <nextTxID>
          0
        </nextTxID>

endmodule
```

Running
-----------

Command line:
```
kompile --backend haskell map-collection.k
kprove map-collection-spec.k --definition map-collection-kompiled/ --spec-module MAP-COLLECTION-SPEC --output pretty --debugger --debug-script konfig
```

repl:
```
alias konfig = config | kast -i kore -o pretty --definition ./map-collection-kompiled /dev/stdin
step 10
konfig
```

Results
----------

```
Kore (0)> step 10
Stopped after 2 step(s) due to reaching end of proof on current branch.

Kore (2)> konfig
Config at node 2 is:

<generatedTop>
  <k>
    submitTransaction ( ) ~> .
  </k>
  <innerTransactions>
    ListItem ( <transaction>
      <txID>
        0
      </txID>
      <txBody>
        "b"
      </txBody>
    </transaction> )
  </innerTransactions>
  <transactions>
    <transaction>
      <txID>
        0
      </txID>
      <txBody>
        "a"
      </txBody>
    </transaction>
  </transactions>
  <nextTxID>
    0
  </nextTxID>
</generatedTop>
Kore (2)> stepf
Kore (3)> konfig
Config at node 3 is:

Proven.

Kore (3)> exit
#Top
```

**Comment by geo2a** [comment]
I now understand that my intuition is based on this sentence from [domains.md](https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#map-concatenation):
> You can construct a new Map consisting of key/value pairs of two Maps. The
result is `#False` if the maps have keys in common (in particular, this will
yield an exception during concrete execution).

**Comment by geo2a** [comment]
Looking at the [Kore.Builtin.AssociativeCommutative](https://github.com/runtimeverification/haskell-backend/blob/1424663331c0542a40f936f706a72a4e8e7c96c0/kore/src/Kore/Builtin/AssociativeCommutative.hs#L5) module, I see that this seems to be the intended behavior:
> Module      : Kore.Builtin.AssociativeCommutative
Description : Handles built-in operations which are associative, commutative,
              with neutral elements, key-based, with unique keys, and which
              return bottom when applied to unique keys.

@ana-pantilie it seems to me like the description should say "... and which return bottom when applied to *non-unique* keys." Could you confirm?

**Comment by geo2a** [comment]
Am I right to conclude that it's the `submitTransaction()` rule effectively assumes False in this case, and that is what makes the definition unsound? And it's the user's responsibility (i.e. mine) to not introduce such unsound rules that try to concatenate maps with duplicate keys?

**Comment by ana-pantilie** [comment]
What version of the Haskell backend are you using? We have recently added a check warning users that the backend has reached a vacuous state, I think that should trigger in your case.

**Comment by geo2a** [comment]
Indeed, I was using the revision `5b972c3bde441694e10a150d2eb5fc1a029274bb` from 2 weeks ago. Switching to `1424663331c0542a40f936f706a72a4e8e7c96c0` --- current master fails the proof and emits the error:

```
kprove map-collection-spec.k --definition map-collection-kompiled/ --spec-module MAP-COLLECTION-SPEC --output pretty
kore-exec: [354184] Warning (WarnStuckClaimState):
    The left-hand side of the claim has been simplified to bottom. Location: /home/geo2a/Workspace/RV/k-testing/map-collection-spec.k:4:9-20:20
Context:
    (InfoReachability) while simplifying the claim
<generatedTop>
  <k>
    .
  </k>
  <innerTransactions>
    .List
  </innerTransactions>
  <transactions>
    <transaction>
      <txID>
        0
      </txID>
      <txBody>
        "a"
      </txBody>
    </transaction> <transaction>
      <txID>
        0
      </txID>
      <txBody>
        "b"
      </txBody>
    </transaction>
  </transactions>
  <nextTxID>
    0 +Int 1
  </nextTxID>
</generatedTop>
[Error] Prover: backend terminated because the configuration cannot be
rewritten further. See output for more details.
```

Thanks @ana-pantilie! Closing now.
