### ISSUE TITLE
`implies` endpoint of RPC server returns unsimplified implication

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3466]
Currently, when I call the `implies` endpoint, it returns three things:

- Substitution (if the implication holds, witnessing substitution).
- Predicate (if the implication holds, witnessing predicate).
- Implication (as far as I can tell, just `antecedent #Implies consequent`).

The last one seems fairly useless as is to me, because it just returns literally `antecedent #Implies consequent`, which I can construct myself if I want. It would be more useful if it returned the minimized/simplified implication, which would be `#Top` when the implication holds, `#Bottom` when it doesn't, and some simplified value otherwise.

Right now pyk emits a bunch of warnings because of this non-trivial implication being passed back. Not sure what we should be doing with it? Should we just drop it completely?

**Comment by ana-pantilie** [comment]
Can you provide an example for testing purposes? We can probably process that implication in several different ways and I'd like to know what you're looking for exactly.

**Comment by ehildenb** [comment]
Discussed this with Jost, and the pyk library will just ignore that third parameter that is passed back more than it is (turn it from warning to info/debug output).
