### ISSUE TITLE
`check_implication` endpoint of RPC server does not check instantiated consequent

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3469]
From this thread on Slack: https://runtimeverification.slack.com/archives/C045G8HCK99/p1674730840244839

And I have worked around this issue in the pyk library here (and added a test using the IMP definition there): https://github.com/runtimeverification/pyk/pull/173

If I have two constrained terms `T1 #And C1` and `T2 #And C2`, and I call `check_implication (T1 #And C1) and (T2 #And C2)`, suppose that it returns to me a substitution `S` and a predicate `P`. The backend is not actually checking, before returning these, that `S(T2 #And C2) #And P` is not `#Bottom`.

In the above linked PR, I [setup a test with IMP where](https://github.com/runtimeverification/pyk/pull/173/files#diff-8b432b93f5cd9fed28048639b96622f8b0c8838de9108cb7617fcefd4893e55fR77):

```
T1 == <k> int $n , $s , .Ids ; $n = 3 </k> <state> .Map </state>
C1 == #Top
T2 == <k> int $n , $s , .Ids ; $n = X </k> <state> .Map </state>
C2 == { true #Equals X <Int 3 }
```

The `check_implication` endpoint gives back `S == X |-> 3` and `P == #Top`.

Indeed, the [added check I have in pyk](https://github.com/runtimeverification/pyk/pull/173/files#diff-6c924e837929a3c2ac3f64cd281dbf78a290c9deb1fc2980b46864f34408be86R147), just calls the `simplify` endpoint with `S(T2 #And C2 #And P)`, and checks if the result is `#Bottom`.

Either the `check_implication` endpoint should be giving back a failed implication check, or I guess this should be documented that the user is expected to make this extra check.

**Comment by ana-pantilie** [comment]
@ehildenb I'm unable to reproduce this behavior by writing a unit test in the backend. Can you provide a bug report?

**Comment by ehildenb** [comment]
I added a test here: https://github.com/runtimeverification/pyk/pull/173/files

So if you uncomment this line in pyk: https://github.com/runtimeverification/pyk/blob/befb7a840b7a5a5963d149bec449a44c8f3937d4/src/tests/integration/utils.py#L52 by applying this patch:

```
diff --git a/src/tests/integration/utils.py b/src/tests/integration/utils.py
index 9ff8c8d..c632f76 100644
--- a/src/tests/integration/utils.py
+++ b/src/tests/integration/utils.py
@@ -50,9 +50,9 @@ class KompiledTest:
 
     @pytest.fixture(scope='class')
     def bug_report(self) -> Optional[BugReport]:
-        return None
+        # return None
         # Use the following line instead to generate bug reports for tests
-        # return BugReport(Path('bug_report'))
+        return BugReport(Path('bug_report'))
 
     @pytest.fixture(scope='class')
     def definition_dir(self, kompile: Kompiler) -> Path:
```

And you run that test:

```
make test-integration TEST_ARGS='-k consequent-constraint --log-file log --log-file-level=info'
```

It will produce the bug report, and a file `log` with the following warning (enabled in that PR linked above):

```
INFO     pyk.ktool.kompile:cli_utils.py:105 Running: kompile k-files/imp-verification.k --output-definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --backend haskell --emit-json
INFO     pyk.ktool.kompile:cli_utils.py:119 Completed: kompile k-files/imp-verification.k --output-definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --backend haskell --emit-json
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:kompiled/000_defn: /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0
INFO     pyk.ktool.kprint:cli_utils.py:105 Running: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression int $n , $s ; $n = 3 ; --sort Pgm
INFO     pyk.ktool.kprint:cli_utils.py:119 Completed: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression int $n , $s ; $n = 3 ; --sort Pgm
INFO     pyk.ktool.kprint:cli_utils.py:105 Running: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression .Map --sort Map
INFO     pyk.ktool.kprint:cli_utils.py:119 Completed: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression .Map --sort Map
INFO     pyk.ktool.kprint:cli_utils.py:105 Running: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression int $n , $s ; $n = X ; --sort Pgm
INFO     pyk.ktool.kprint:cli_utils.py:119 Completed: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression int $n , $s ; $n = X ; --sort Pgm
INFO     pyk.ktool.kprint:cli_utils.py:105 Running: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression .Map --sort Map
INFO     pyk.ktool.kprint:cli_utils.py:119 Completed: kast --definition /tmp/pytest-of-dev/pytest-541/popen-gw0/kompiled0 --input rule --output json --expression .Map --sort Map
INFO     pyk.kcfg.explore:explore.py:143 Binding variables in consequent: ['X']
INFO     pyk.kore.rpc:rpc.py:450 Starting KoreServer: port=39885
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:commands/000.sh: /tmp/tmpr1jqx9r0
INFO     pyk.kore.rpc:rpc.py:455 KoreServer started: port=39885, pid=2949379
INFO     pyk.kore.rpc:rpc.py:75 Connecting to host: localhost:39885
INFO     pyk.kore.rpc:rpc.py:82 Connected to host: localhost:39885
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:rpc/001_request.json: /tmp/tmphpbwjrn5
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:commands/001.sh: /tmp/tmpm9_acj_v
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:rpc/001_response.json: /tmp/tmpt_fqwi5z
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:commands/002.sh: /tmp/tmp2io0fyek
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:rpc/002_request.json: /tmp/tmpgvbq52kl
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:commands/003.sh: /tmp/tmpt49u9li0
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:rpc/002_response.json: /tmp/tmp4g2x48ud
INFO     pyk.cli_utils:cli_utils.py:147 Added file to bug report bug_report.tar:commands/004.sh: /tmp/tmpm6btr_1p
WARNING  pyk.kcfg.explore:explore.py:167 Simplifying instantiated consquent resulted in #Bottom: CTerm(config=KApply(label=KLabel(name='<generatedTop>', params=()), args=(KApply(label=KLabel(name='<T>', params=())
INFO     pyk.kore.rpc:rpc.py:466 KoreServer stopped: port=39885, pid=2949379
```

Note the `WARNING` as second to last line in the log, where pyk is saying "I had to simplify the instantiated consequent myself, instead of the backend doing it". Would prefer if the backend could do that, so we can avoid the extra call to the simplifier.

Attached is the bug report: [bug_report.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10745168/bug_report.tar.gz)

**Comment by ehildenb** [comment]
So you can run the same test again with `kup` installed `kore-rpc` from your branch, and make sure the warning does not show up. Then we can remove the extra check from pyk.

**Comment by ana-pantilie** [comment]
Thanks!

**Comment by ana-pantilie** [comment]
@ehildenb the bug report contains the correct response for your request, that the implication is `false`. I get the same response when trying this out locally. The `condition` in the response does indeed contain the substitution and predicate you pointed out, but that doesn't mean that the implication is satisfied. Recall that the `condition` is the unification result of the two terms, and the `satisfiable` field tells you if the implication holds or not.
