### ISSUE TITLE
What to return if implication is trivially satisfied?

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3484]
Attached is a bug report: [bug_report.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10582307/bug_report.tar.gz). Where I'm adding tests for this in pyk: https://github.com/runtimeverification/pyk/pull/184

I have a simple IMP definition, and I am feeding the following term into the Haskell backend simplify endpoint:

```
CT1 = <k> int $n ; $n = X ; </k> <state> .Map </state> #And X <Int 3 #And 3 <Int X
CT2 = <k> int $n ; $n = Y ; </k> <state> .Map </state>
```

The first RPC call in the bug report is `simplify: CT1`, which returns basically the same thing as `CT1`, but I expect it to return `#Bottom`. The second call in the bug report is `implies: CT1 => CT2`, which as expected returns `#Top` (because the antecedent is bottom), with empty substitution and empty predicate. Some differences I would expect:

- The first call to `simplify` should return `#Bottom`, because the implication endpoint is able to detect that the antecedent is bottom.
- The second call to `implies` should not return `#Top` for the predicate, but `#Bottom`. It should be that if implication endpoint returns `condition { "substitution": SUBST, "predicate": PRED }`, then I can construct `SUBST(CT2) #And PRED` and have that be equal to `CT1`. But right now, `Subst(CT2) == CT2` (empty substitution), and `PRED == #Top`, so `SUBST(CT2) #And PRED == CT2`, and we _do not_ have that `CT1 == SUBST(CT2) #And PRED` (because `CT1` is bottom).

There is no way I can find for me to work around this, and it's blocking progress on pyk RPC prover. An immediate fix to the `simplifies` endpoint (so it returns `#Bottom` correctly) would fix this. So would a separate fix to the `implies` endpoint.

**Comment by ehildenb** [comment]
This does not appear to be fixed:

```
[dev@dev-ubuntu pyk]% kup list
┌───────────┬──────────────────────────────────────────┬──────────────┐
│ Package   │ Installed version                        │ Status       │
├───────────┼──────────────────────────────────────────┼──────────────┤
│ kup       │ 04f0c0033ada3aa001458bfa7ebe413d7d9f50b0 │ 🟢 installed │
│ kore-rpc  │ b74e9f8d5b88f4550145abf90d7fb3e69e072963 │ 🟢 installed │
│ k         │ 0465cd2d61bee8ce4bfb7be1bc5b8ed51e8fa271 │ 🟢 installed │
│ kavm      │                                          │ 🔵 available │
│ kevm      │                                          │ 🔵 available │
│ kplutus   │                                          │ 🔵 available │
│ kore-exec │                                          │ 🔵 available │
│ pyk       │                                          │ 🔵 available │
└───────────┴──────────────────────────────────────────┴──────────────┘
```

Attached is a bug report: 
[bug_report.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10716515/bug_report.tar.gz)


Now, it's returning:

- Implication is `satifiable: true`
- Substitution is `None`
- Predicate is `None`

It should really be returning:

- Implication is `satisfiable: true`
- Substitution is `#Top`
- Predicate is `#Bottom`

**Comment by ehildenb** [comment]
Basically, I should not need to make this extra check here: https://github.com/runtimeverification/pyk/pull/184/files#diff-6c924e837929a3c2ac3f64cd281dbf78a290c9deb1fc2980b46864f34408be86R127

It's OK if I have to make that extra check, because current design of implication endpoint does not allow the above specification, but it's more expensive to make the extra call into the RPC server.

**Comment by ana-pantilie** [comment]
[From meeting](https://github.com/runtimeverification/haskell-backend/blob/b74e9f8d5b88f4550145abf90d7fb3e69e072963/kore/src/Kore/JsonRpc.hs#L486)

**Comment by ana-pantilie** [comment]
Please see https://github.com/runtimeverification/haskell-backend/pull/3497/files for the updated specification, it should make it possible for users to distinguish between several cases.
