### ISSUE TITLE
Rename functional into total

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3493]
The frontend currently transforms K's `total` attribute into Kore's `functional` attribute. We should also look into renaming our internal attribute to `Total` and start parsing `total` instead of `functional` (will need to be accompanied with a change to the frontend).

**Comment by dwightguth** [comment]
If the generated kore gets altered there will also need to be an accompanying change to the llvm backend.

**Comment by radumereuta** [comment]
Can't the backends accept both versions for a while?
Just to maintain functionality during the change.

**Comment by ana-pantilie** [comment]
> Can't the backends accept both versions for a while?
That's what I was thinking, modify backends first to accept both changes then modify the frontend.

**Comment by radumereuta** [comment]
> That's what I was thinking, modify backends first to accept both changes then modify the frontend.

I'm only mentioning it because it wasn't clear from your wording.

**Comment by dwightguth** [comment]
Sure, the backends can support both temporarily, but I was simply pointing out that a change to the llvm backend is also required here.
