### ISSUE TITLE
Simplify the translation of K in Kore 

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/haskell-backend#3501]
If I understand correctly, the rule `rule false andThenBool _ => false` becomes
 ```
 // rule `_andThenBool_`(#token("false","Bool") #as _Gen1,_Gen0)=>_Gen1 
```
in KAST format, and
```
  axiom{R} \implies{R} (
    \and{R}(
      \top{R}(),
      \and{R} (
          \in{SortBool{}, R} (
            X0:SortBool{},
            \and{SortBool{}}(\dv{SortBool{}}("false"),Var'Unds'Gen1:SortBool{})
          ),\and{R} (
          \in{SortBool{}, R} (
            X1:SortBool{},
            Var'Unds'Gen0:SortBool{}
          ),
          \top{R} ()
        ))),
    \equals{SortBool{},R} (
      Lbl'Unds'andThenBool'Unds'{}(X0:SortBool{},X1:SortBool{}),
     \and{SortBool{}} (
       Var'Unds'Gen1:SortBool{},
        \top{SortBool{}}())))
 ```
in Kore format.
 
 
I don't know if it's an issue or not, but it's easiest to generate:
 ```
 // rule `_andThenBool_`(#token("false","Bool"), X1)=>#token("false","Bool") 
```
in KAST format, and
```
  axiom{R} \implies{R} (
    \top{R} (),
    \equals{SortBool{},R} (
      Lbl'Unds'andThenBool'Unds'{}(\dv{SortBool{}}("false"),X1:SortBool{}),
     \and{SortBool{}} (
       \dv{SortBool{}}("false"),
        \top{SortBool{}}())))
 ```

**Comment by ana-pantilie** [comment]
Function rules are encoded this way for a reason, please see https://github.com/runtimeverification/haskell-backend/blob/master/design-decisions/2020-05-02-function-rules.md

**Comment by amelieled** [comment]
Thanks @ana-pantilie ! Wonderful document! :) 
In the above case, I don't understand why do you need: `X1 \in Gen0`.
Same for `X0 \in (false /\ Gen1)`.
Indeed, we know nothing about `Gen0` and `Gen1`.

**Comment by ana-pantilie** [comment]
In theory I believe that yes there are certain cases where the `\in` can be simplified away, but it's easier for the frontend to not worry about such simplifications and to provide a consistent format of these kinds of equations for the backend(s).

**Comment by amelieled** [comment]
OK but how `Gen0` and `Gen1` are instanciated?

**Comment by amelieled** [comment]
For instance, if the backend instanciates `Gen0` by `false` but the user would like to use the rule with `true`, the rewriting rule doesn't apply.

**Comment by amelieled** [comment]
In fact, `Gen0` and `Gen1` haven't no meaning (related to the initial rewriting rule).

**Comment by ana-pantilie** [comment]
> OK but how Gen0 and Gen1 are instanciated?

Those variables are instantiated by matching with the term to which that rule applies to.

> For instance, if the backend instanciates Gen0 by false but the user would like to use the rule with true, the rewriting rule doesn't apply.

I don't really understand why you think that. It will always be instantiated as I pointed out above.

`(X0 in (false and Gen1)) and (X1 in Gen0) => andThenBool(X0, X1) = Gen1` is basically saying exactly: `andThenBool(false and Gen1, Gen0) = Gen1`. The reasoning behind this is that in ML `in` encodes unification (recall that `X in t <=> ceil(X and t)`).

Does this make sense?

**Comment by goodlyrottenapple** [comment]
@ana-pantilie is `\in` commutative? based on the definition above it would seem `X \in t` and `t \in X` are the same?

**Comment by amelieled** [comment]
In fact, the definition in paper is `x in phi == ceil(x and phi)`, so implicitly, `x` is a variable and `phi` is any pattern. So, `phi in x <> ceil(phi and x)`.
