### ISSUE TITLE
`Invalid params` RPC response from `implies` endpoint

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/haskell-backend#3502]
I am making a call via Pyk to the `implies` endpoint, but it seems to hit some kind of internal error (`-32602`, "Invalid Params") when doing so; my suspicion is perhaps that the terms I'm checking are too large for the underlying library? The implication in question is just sanity-checking whether a large concrete term unifies with itself (i.e. `client.implies(term, term)` in Pyk).

I'm running `kore-rpc` as:
```console
$ kore-rpc /home/bruce/code/c-semantics/.build/dist/lib/kcc/haskell/c-kompiled/definition.kore --server-port 5766 --module C
```
Version info:
```console
$ kore-rpc --version
Kore version 0.60.0.0
Git:
  revision:	b74e9f8d5b88f4550145abf90d7fb3e69e072963
  branch:	HEAD
  last commit:	Thu Feb 9 16:26:54 2023 -0700
```

Reproduction files:
* [C semantics definition](https://drive.google.com/file/d/12tzsmK2pvUNNXKJFBij17YBLdStn1byF/view?usp=share_link)
* [Pyk bug report](https://drive.google.com/file/d/1p0cS_jhBA0dxsppNKGRWB5dMWmiBCo7e/view?usp=share_link) - contains the actual JSON blobs that get sent to the RPC server, as well as the response I'm seeing

Let me know if there is any more context I can provide.

**Comment by ana-pantilie** [comment]
@jberthold:
- this error doesn't come from our code, it comes from the json-rpc library (or somewhere underneath that one, rpc -> conduit)
- try to remove the json-rpc library and try something like https://gist.github.com/coopernurse/9732158
- test parseParams in isolation: https://github.com/runtimeverification/haskell-backend/blob/42cd7c42fd0d4645562283d334a0e040f9bbbc29/kore/src/Kore/JsonRpc.hs#L172

@goodlyrottenapple:
- this is where the error comes from https://github.com/jprupp/json-rpc/blob/e08a4435300c8c7d43d2054a7970a1ed08be3e4e/src/Network/JSONRPC/Data.hs#L94
- we're a custom request parser: https://github.com/runtimeverification/haskell-backend/blob/42cd7c42fd0d4645562283d334a0e040f9bbbc29/kore/src/Kore/JsonRpc.hs#L172
- make a copy of the library so that I can modify the code to trace more info

**Comment by ana-pantilie** [comment]
@Baltoli is this blocking you?

**Comment by Baltoli** [comment]
Low priority for the time being!

**Comment by ana-pantilie** [comment]
I have identified the parse error:
```
"Error in $.antecedent.term.args[1].args[6].args[11].args[0].tag: parsing Kore.Syntax.Json.Internal.KorePattern failed, expected tag field to be one of [\"EVar\",\"SVar\",\"App\",\"String\",\"Top\",\"Bottom\",\"Not\",\"And\",\"Or\",\"Implies\",\"Iff\",\"Forall\",\"Exists\",\"Mu\",\"Nu\",\"Ceil\",\"Floor\",\"Equals\",\"In\",\"Next\",\"Rewrites\",\"DV\",\"MultiOr\",\"MultiApp\"], but found tag \"LeftAssoc\""
"Error in $.antecedent.term.args[1].args[6].args[11].args[0].tag: parsing Kore.Syntax.Json.Internal.KorePattern failed, expected tag field to be one of [\"EVar\",\"SVar\",\"App\",\"String\",\"Top\",\"Bottom\",\"Not\",\"And\",\"Or\",\"Implies\",\"Iff\",\"Forall\",\"Exists\",\"Mu\",\"Nu\",\"Ceil\",\"Floor\",\"Equals\",\"In\",\"Next\",\"Rewrites\",\"DV\",\"MultiOr\",\"MultiApp\"], but found tag \"LeftAssoc\""
```

It looks like the JSON representation doesn't support left-assoc.

**Comment by Baltoli** [comment]
I guess this needs Pyk support @tothtamas28? Or is there a way I can make this transformation already?

**Comment by ana-pantilie** [comment]
I realized I'm not entirely sure that is the correct format. @jberthold or @goodlyrottenapple do you recall how we would handle symbols with left-assoc at the top? In particular, this is one usage example inside the request that fails here:

```
{"tag": "LeftAssoc", "app": {"tag": "App", "name": "Lbl'Unds'List'Unds'", "sorts": [], "args": [{"tag": "App", "name": "LblListItem", "sorts": [], "args": [{"tag": "App", "name": "LblfstackFrame'LParUndsCommUndsCommUndsCommUndsCommUndsCommUndsCommUndsRParUnds'C-POSTFIX-EXP-SYNTAX'Unds'KItem'Unds'K'Unds'Scope'Unds'List'Unds'Map'Unds'List'Unds'Map'Unds'Location", "sorts": [], "args": [{"tag": "App", "name": "kseq", "sorts": [], "args": [{"tag": "App", "name": "Lbltermination'Unds'C-EXECUTION'Unds'KItem", "sorts": [], "args": []}, {"tag": "App", "name": "dotk", "sorts": [], "args": []}]}, {"tag": "App", "name": "LblFileScope'LParRParUnds'C-SCOPE'Unds'Scope", "sorts": [], "args": []}, {"tag": "App", "name": "Lbl'Stop'List", "sorts": [], "args": []}, {"tag": "App", "name": "Lbl'Stop'Map", "sorts": [], "args": []}, {"tag": "App", "name": "Lbl'Stop'List", "sorts": [], "args": []}, {"tag": "App", "name": "Lbl'Stop'Map", "sorts": [], "args": []}, {"tag": "App", "name": "LblLocation'LParUndsCommUndsCommUndsCommUndsCommUndsRParUnds'C-LOCATION-SYNTAX'Unds'Location'Unds'String'Unds'Int'Unds'Int'Unds'Int'Unds'Int", "sorts": [], "args": [{"tag": "DV", "sort": {"tag": "SortApp", "name": "SortString", "args": []}, "value": "<unknown>"}, {"tag": "DV", "sort": {"tag": "SortApp", "name": "SortInt", "args": []}, "value": "0"}, {"tag": "DV", "sort": {"tag": "SortApp", "name": "SortInt", "args": []}, "value": "0"}, {"tag": "DV", "sort": {"tag": "SortApp", "name": "SortInt", "args": []}, "value": "0"}, {"tag": "DV", "sort": {"tag": "SortApp", "name": "SortInt", "args": []}, "value": "0"}]}]}]}]}}
```

**Comment by jberthold** [comment]
Correct, the syntax for the textual `\left-assoc` is not just `"tag": "LeftAssoc"`, but rather `"tag": "MultiApp", "assoc": "Left"` together, and omits the `App` construct which is in the textual representation.
Also, we distinguish a multi-"OR" (function symbol fixed to `\or`) from a more general multi-"app" to disambiguate.

The correct form for the term above would be:
```json
{ "tag": "MultiApp",
  "assoc": "Left", 
  "symbol": "Lbl'Unds'List'Unds'", 
  "sorts": [],
  "args": [
    {
      "tag": "App",
      "name": "LblListItem",
      "sorts": [],
      "args": [
        {
          "tag": "App",
          "name": "LblfstackFrame'LParUndsCommUndsCommUndsCommUndsCommUndsCommUndsCommUndsRParUnds'C-POSTFIX-EXP-SYNTAX'Unds'KItem'Unds'K'Unds'Scope'Unds'List'Unds'Map'Unds'List'Unds'Map'Unds'Location",
          "sorts": [],
          "args": [ ...(omitted)...]
        }
      ]
    }
  ]
}
```

These constructs are desugared when the input is converted to the internal representation (`ParsedPattern`).

We can of course change this to `LeftAssoc` and `RightAssoc`  tags instead, and could also collapse `or` and `app` into one, but it felt superfluous at the time.

NB that the RPC server will never _generate_ those left- or right-associative constructs in the output (the converter would need annotations or some other help to decide whether the conversion would be sound, and it is anyway better to have a single correct output conversion for a single internal term).

**Comment by tothtamas28** [comment]
`pyk` indeed serializes this term as `{"tag": "LeftAssoc", "app":{"tag":"App",...}}`.

The reason for the discrepancy I think is that when we designed the schema, we decided not to deal with syntactic sugar until it becomes an issue.

**Comment by ana-pantilie** [comment]
We need to decide on whether we change this on the backend or on the pyk side. @tothtamas28 how hard would it be to change pyk?

**Comment by tothtamas28** [comment]
> how hard would it be to change pyk?

Inlining the `App` would be a simple. Modifying the tag would require some additional code.

But I think the tag `MultiApp` also breaks symmetry: all other tags correspond to some symbol name in [kore-syntax.md](https://github.com/runtimeverification/haskell-backend/blob/master/docs/kore-syntax.md).

So my suggestion is:

```json
{ 
    "tag": "LeftAssoc",
    "symbol": ...,
    "sorts" : ...,
    "argss": ...
}
```

which is analogous to

```json
{ 
    "tag": "Mu",
    "var": ...,
    "varSort": ...,
    "arg": ...
}
```

where we have tags for both `Mu` and `Nu`, and the fix-point variable is inlined.
