### ISSUE TITLE
`kore-rpc` does not send response on solver crash

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/haskell-backend#3520]
## Reproduction

Kompile definition:

[definition.txt](https://github.com/runtimeverification/haskell-backend/files/10831782/definition.txt)

The definition can be produced by cloning https://github.com/runtimeverification/evm-semantics/commit/c9b14f64be620c2ce7cb12b466ba972ac822f990, then building the Foundry test definition:

```
$ make tests/foundry/out/kompiled/timestamp
```

Start `kore-rpc`:

```
$ kore-rpc tests/foundry/out/kompiled/definition.kore --module FOUNDRY-MAIN --server-port 3000 --smt-timeout 1 --smt-retry-limit 1
```

Send request:

[request.txt](https://github.com/runtimeverification/haskell-backend/files/10831187/request.txt)

```
$ netcat localhost 3000 < request.txt
```

Server log:

```
kore-rpc: user error (Unexpected result from the SMT solver:
  Command: (push 1 )
  Expected: success
  Result: (error "line 2038 column 8: canceled" )
)
```

## Actual behavior

`kore-rpc` does not send response, which makes the client hang indefinitely.

## Expected behavior

`kore-rpc` should send error response with an application defined error code.

**Comment by ehildenb** [comment]
@tothtamas28 if you can make this via the `--bug-report` option instead for pyk (which should be threaded through the foundry prover), I think the backend team has a way to automatically load up those files. But this should work OK too, just doesn't package up the definition as nicely for them.

So, for example, you could do:

```
export KORE_RPC_OPTS='--smt-timeout 1 --smt-retry-limit 1'
make tests/specs/benchmarks/address00-spec.k.prove KPROVE_OPTS='--pyk --bug-report'
```

And it should create a `bug-report.tar` file which can be uploaded here.

I haven't tested these instructions.
