### ISSUE TITLE
Refuse RPC input that uses symbols with `macro` or `alias` attribute

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3533]
In https://github.com/runtimeverification/pyk/issues/248 , an input term was sent for `check-implication` which contained `#rangeUInt`, a symbol that the K definition marks as an `alias` (i.e., resolved and inlined by the front-end).
These symbols (also the ones tagged as `macro`) are present in `definition.kore` but do not have any associated rules or equations - the back-end cannot use them at all. As a result, the implication check erroneously failed.

* When internalising RPC input terms, refuse to use symbols tagged as `alias` or `macro`
* If such a symbol is found, report it in an input error to the RPC caller

**Comment by ana-pantilie** [comment]
`symbolValidator` should error if a symbol has the `alias` or `macro` attribute.

**Comment by ana-pantilie** [comment]
@alexd1971 https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Validate/PatternVerifier.hs is the module which should contain the code we want to modify. The idea is, when verifying symbols we need to look at the attributes and see if there is a `macro` or an `alias'Kywd'` attribute.
