### ISSUE TITLE
Add parser support for multiary `\and` and `\or`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/haskell-backend#3542]
Implement the following changes in the KORE parser:

```diff
< "\and" "{" <sort> "}" "(" <pattern> "," <pattern> ")"
> "\and" "{" <sort> "}" "(" <patterns> ")"
```

```diff
< "\or" "{" <sort> "}" "(" <pattern> "," <pattern> ")"
> "\or" "{" <sort> "}" "(" <patterns> ")"
```

As long as output only uses the previous format (i.e. binary connectives), the change is backward compatible.

### Flat representation for constrained terms

This simplifies

```
\and{SortGeneratedTopCell{}}(
    configuration,
    \and{SortGeneratedTopCell{}}(
        constraint1,
        constraint2
    )
)
```

to

```
\and{SortGeneratedTopCell{}}(configuration, constraint1, constraint2)
```

### Prepare removal of syntax sugar

Textual KORE currently has syntax sugar

```
"\left-assoc" "{" "}" "(" <multi-or> ")"
"\right-assoc" "{" "}" "(" <multi-or> ")"
```

which have limited use:

* Syntax `"\left-assoc" "{" "}" "(" <multi-or> ")"` is used in the LLVM backend to output the result of `--search`. The Haskell backend supports this syntax to be compatible with that output.
* Syntax `"\right-assoc" "{" "}" "(" <multi-or> ")"` has no uses.

With support for multiary `\or`,  the syntactic sugar for `\or` could be dropped altogether:

* Changing the LLVM backends output for `--search` is straightforward.
*  No need to adjust the LLVM backend's parser as the backend doesn't support ML connectives in the first place.

(@Baltoli, please check if my understanding is correct.)

**Comment by ana-pantilie** [comment]
@tothtamas28 what is the priority of this? Doing it properly would mean changes in both the frontend and the backends. Is there a compelling reason that would require this change?

**Comment by tothtamas28** [comment]
Priority for this is moderate / low.

> Is there a compelling reason that would require this change?

Outlined above.

> changes in both the frontend and the backends

Changes can be introduced gradually:

1. Add parser support without using the new constructs in the output. This is not a breaking change.
2. Start using new syntax in the output.
3. Drop syntax sugar.

**Comment by tothtamas28** [comment]
> I think such a change needs discussing with

I agree.

> Did you discuss this at last week's K dev meeting?

No, let's discuss it this week.

**Comment by ehildenb** [comment]
We need to make sure that axioms emitted by the frontend are still inspectable by the haskell backend, because it relies on the order that sub-conjuncts show up in the rules to determine which is the term and which are constraints.

**Comment by ehildenb** [comment]
Codebases that need to be addressed here:

- LLVM backend.
- Haskell backend.
- Booster?
- Frontend scala?
- pyk.

We should really strive for consistent representation, which likely means we need to update the document _first_ and do a small audit of the parsers (whoever is touching those parsers). We can use Tamas's delta above as a template for this.

Suggestions:

- `\and` and `\or` can have multiple children.
- `\left-assoc` and `\right-assoc` only apply to application patterns (not ML patterns in general).

Another lower priority suggestion:

- Potentially have a dedicated test-suite for Kore patterns, passes those patterns to each tool and makes sure they all give back the same parser and same text representation back.

**Comment by tothtamas28** [comment]
Should we also accept zero or one operand? We don't necessarily have to produce such output from the backends, but in my opinion it doesn't hurt to accept such input, as semantically it can make sense.

**Comment by dwightguth** [comment]
With that being said, I don't think the ASTs should support one or zero arguments; I think the parser should desugar these cases automatically.

**Comment by dwightguth** [comment]
It is at implementation detail, but it's still important because and \and with zero or one arguments is technically not a conjunction logically. If you don't do this, you would have to make sure to check for multiple equivalent representations of the same pattern literally everywhere.

**Comment by dwightguth** [comment]
For example, `\and()` is just `\top` and `\and(\or(x, y))` is actually an `\or` and not an `\and`. So anything that needs to know whether a term is top or a disjunction would have to consider these cases, which is very ugly.

**Comment by tothtamas28** [comment]
I agree, these are all valid reasons for having the more restrictive representation. But my point is not `"ASTs should allow zero or one argument"`, but `"ASTs may allow zero or one argument"`. Whether it makes sense or not can be decided in the given context. I don't see how the more general representation would cause issues in `pyk` at this point (especially if the backends do not emit such terms), but I'll check.

**Comment by dwightguth** [comment]
I mean, does pyk ever traverse a kore term and perform an if on whether or not a term has a particular algebraic type? If the answer is yes, it matters.

**Comment by dwightguth** [comment]
I also want to point out that it's by no means guaranteed that the backends will never emit such terms. That may be true now, but I see a number of scenarios where that might change in the future without someone considering that it might break such an arcane assumption on the part of pyk.

**Comment by dwightguth** [comment]
Here is the sequence of changes that still need to be made in order to complete the change in the haskell and llvm backends and the k frontend:

1. [ ] Merge https://github.com/runtimeverification/haskell-backend/pull/3666
2. [ ] Merge https://github.com/runtimeverification/hs-backend-booster/pull/324 and update version of haskell backend booster depends on
3. [ ] Merge https://github.com/runtimeverification/llvm-backend/pull/844
4. [ ] Update version of haskell-backend, booster, and llvm-backend used by frontend
5. [ ] Merge https://github.com/runtimeverification/k/pull/3679
6. [ ] Update parser of llvm, haskell, and booster backends to remove parsing of \left-assoc and \right-assoc of \and and \or
7. [ ] update version of haskell-backend, booster, and llvm-backend used by frontend

It has to be done in exactly this order.
