### ISSUE TITLE
`kore-rpc` support logging options directly

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3561]
- [ ] Add a new switch to the RPC requests which turns on this logging. Add 3 new optional response fields: `rewrite-rules`, `function-definition-rules`, `simplification-rules` which contain lists of strings. The strings are, for each applied rule, in this order of priority: the label/the source location/the unique id. This change needs to be done in the `kore-rpc-types` package in the Haskell backend repo.
- [ ] Collect the required data in the Haskell backend.
- [ ] Collect the required data in the booster.

----

@geo2a is working on https://github.com/runtimeverification/pyk/issues/300, which is to be able to audit lemma coverage of proofs in a semantics, to determine which simplification rules are actually needed or not.

Currently, we have to launch the RPC server on the side with the correct options, and the scrape the log entries on the side as well.

Can we make each RPC call has an extra optional argument `logs: ["LOG_ID_1", ..., "LOG_ID_N"]`, and the responses come back with the log entries for that given call? That way we can get back exactly the log entries for each call, instead of having to rescrape file logs between calls.

**Comment by ehildenb** [comment]
First log entries that we care to support:

- `rules`: rule names that are used to do rewriting.
- `equations`: rule names that are used from semantics axioms.
- `simplifications`: rule names that are used from simplification axioms.

We could make it more specific too, by having a boolean flag: `log-rules`, `log-equations`, `log-simplifications`.

**Comment by jberthold** [comment]
From discussion in the team:
* It would be good to pin-point exactly what information should be included in the log. That way we will have more flexibility in how we implement it (the information needs to be consistent in both `hs-booster-proxy` and old backend `kore-rpc`). We would then add this information as structured data in the rpc response types.
* Some rules do not have names, do we use the location in this case? (worse than that, some equations do not have location information)
* Experience shows that it often matters more which rules or equations did _not_ apply and why. `kore-rpc` can log this, for specific named equations. Maybe it would be even better to focus on particular _terms_, too (unclear how to specify those).

**Comment by ehildenb** [comment]
The tool in question here is for auditing existing proof-suites and removing lemmas that do not do any work anymore. That usually happens because in PR #NNN, you introduce some `simplification` rules, and then in `#NNN+3`, you introduce more more general rules which make the original rules redundant. So we want a tool that tells us which rules are actually applied, for quickly pruning uneeded simplification rules.

We also want a way to tell which rules are needed for which tests, so that when we upstream lemmas (and tests for lemmas) from client engagements, we can do so in a systematic way by using this to audit the rules used for each test.

So, yes, people have asked for "why doesn't this rule apply", but that isn't what this is for. It's for "I want the log of all the rules that did apply".
