### ISSUE TITLE
Implement `KRYPTO.ecdsaPubKey` hook

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3573]
We're running Foundry property tests which use `ECDSAPubKey` (defined in https://github.com/runtimeverification/blockchain-k-plugin/blob/master/plugin/krypto.md#ecdsa-functions). We're running this on concrete inputs, so we expect it to return public keys correctly for us, but instead the backend gives back:

```
kore-exec: [10365800] Error (ErrorException):
    Error: missing hook
    Symbol
        LblECDSAPubKey'LParUndsRParUnds'KRYPTO'Unds'String'Unds'String{}
    declared with attribute
        hook{}("KRYPTO.ecdsaPubKey")
    We don't recognize that hook and it was not given any rules.
    Please open a feature request at
        https://github.com/runtimeverification/haskell-backend/issues
    and include the text of this message.
    Workaround: Give rules for LblECDSAPubKey'LParUndsRParUnds'KRYPTO'Unds'String'Unds'String{}
    CallStack (from HasCallStack):
      error, called at src/Kore/Rewrite/Function/Evaluator.hs:371:6 in kore-0.60.0.0-J3wx87sugwq89e8bV2p6uj:Kore.Rewrite.Function.Evaluator
Created bug report: kore-exec.tar.gz
```

I've attached the kore-exec bug report that is generated (note that the given proof is bogus and shouldn't pass, but it also shouldn't crash).

[kore-exec.tar.gz](https://github.com/runtimeverification/haskell-backend/files/11298943/kore-exec.tar.gz)

For now, I think we will hardcode the few cases we need this for with simplification rules, but that will get annoying very quickly for users of the Foundry integration. It's a common pattern to supply some random bytes as a "private key" for testing, and then use that to derive a valid address, and use that private-key/address combination for testing on-chain cryptographic solutions.

For example, it's not uncommon to supply a random private key in a property test, then use `vm.addr(...)` cheatcode to turn said private key into an Ethereum address that can be used. This pattern is especially used with contracts where signatures are checked onchain. To get around this with `ECDSAPubKey` not being implemented on concrete inputs for the Haskell backend, https://github.com/runtimeverification/evm-semantics/pull/1766 allows us to write lemmas directly for the addresses needed in the tests. Given a private key KEY (encoded in hex, for example: `0x2b8ba85ff7f2c7fa62cddb20ae40ef2553b9fdbff086f60d1647ecaab15af867`), and the associated Ethereum address ADDR (encoded as a decimal integer, for example: `1204788665628904891128108629487072145087352593841`), you can add the following K lemma to your `lemmas.k` for a project to help the Haskell backend reason about that case:
```
rule #addrFromPrivateKey(KEY) => ADDR [priority(40)]
```
So, given `KEY`, how do you figure out the correct `ADDR`?

First, install `ganache-cli`:
```
npm install -g ganache-cli
```
Then run, in one terminal, `ganache-cli`:
```
ganache-cli
```
Wait for it to start up, then in a file called `ganache.in`, put the following contents:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "personal_importRawKey",
  "params": ["KEY", "0x"]
}
```
Then, in another terminal, run the following command to send this request to `ganache-cli`:
```
curl -s -X POST 'http://127.0.0.1:8545' --data @ganache.in -H "Content-Type: application/json"
```
It will output a response that looks like this:
```
{"id":1,"jsonrpc":"2.0","result":"HEX_ADDR"}
```
Take the `HEX_ADDR`, and put it in this website to convert it to decimal: https://www.rapidtables.com/convert/number/hex-to-decimal.html, which gives you `ADDR`, so that you can make your lemma!

**Comment by jberthold** [comment]
@palinatolmach is this still high priority?

**Comment by palinatolmach** [comment]
@jberthold relatively high, as it's useful for verification of Foundry projects and we want that to be as feature complete as possible, but it's not blocking (I downgraded the priority to medium).
