### ISSUE TITLE
Unique IDs for rules

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3578]
- [ ] both backends should expect all rules to have a unique id attribute
- [ ] old backend: currently parses them as `Maybe Text`, should be `Text`
- [x] new backend: need to add support for this attribute, WIP: https://github.com/runtimeverification/hs-backend-booster/pull/175
- [x] the frontend should always generate unique ids for rule: https://github.com/runtimeverification/k/pull/3371
- [ ] the `add-module` endpoint should also expect that all the rules have unique ids

The main work to do here is to check uniqueness of rule IDs while internalising.

**Comment by jberthold** [comment]
The team decided to keep unique IDs  _optional_  in the backend for better flexibility.
