### ISSUE TITLE
Remove support for old antileft rewrite format

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/haskell-backend#3582]
Per https://github.com/runtimeverification/k/issues/3035, we can remove support for the old "antileft" style of rewrite rule for KORE backends[^1].

@dwightguth is doing so for the LLVM backend, and the Haskell backend may want to consider doing so as well.

[^1]: The frontend will retain the ability to generate the antileft priority predicates for proof object generation, but we don't need execution backends to understand it. This divergence in KORE was discussed in the K dev meeting and we were collectively happy with it.

**Comment by dwightguth** [comment]
Note that this issue is actually blocked on https://github.com/runtimeverification/k/issues/3398
