### ISSUE TITLE
Add `get-model` endpoint to `kore-rpc`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3598]
There are now two use cases that would benefit from being able to get a model from a given configuration + constraints directly from the backend. Z3 already supports this functionality via its get-model call.

In particular, when we are:

- Trying to measure symbolic coverage of a given property test-suite, and want to [give back a  concrete example that is not covered](https://github.com/runtimeverification/evm-semantics/pull/1862), the easiest way would be to have a `get-model` endpoint to invoke.
- Trying to prove a property test has passed, but it _failed_, we want to [provide a specific input to the user that it fails on](https://github.com/runtimeverification/evm-semantics/issues/1700), because then they can add that as a unit test directly to their  test-suite. This would enable much faster turn-around for users on the same problem in the future.

To achieve this, I think the path forward is:

- Separate out `kore-types` into its own repository.
- Separate out `kore-2-smt` into its own repository.
- Expose a `get-model` endpoint in the old backend which can use `kore-2-smt` to encode the current definition and a user-supplied configuration + constraints to SMT, and ask it for a model. It needs to then translate the model back to a substitution which can be passed back as a kore term (as a bunch of equalities in the form `{ V1 #Equals ... } #And { V2 #Equals ... } #And ...`, or gives back "no-model".
- Separate out `kore-2-types` into its own repo, and make translating from `kore-2-types => kore-types` possible in that repository.
- Expose `get-model` endpoint in new booster backend as well, via the translation path above.

**Comment by ehildenb** [comment]
The priority will be to expose `get-model` endpoint in the old backend, not in the booster backend. The booster backend can just invoke the old backend in the proxy for this endpoint, so that we don't have to worry about encoding new datastructures to SMT.

**Comment by geo2a** [comment]
I think this functionality will be very useful for node refutations subproofs too, because we are interested in satisfiability of a particular path condition + configuration when we consider these. Essentially, to prove a node unreachable we need to prove that it's path condition is unsatisfiable.

**Comment by jberthold** [comment]
`get-model` endpoint is implemented now, further plans should be on a new issue
