### ISSUE TITLE
Change `satisfiable` to `valid` in implication endpoint response

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/haskell-backend#3601]
Technically we should return valid rather than satisfiable here:

https://github.com/runtimeverification/haskell-backend/blob/740a60ee231ad63b811f0ca023cbf747ae0aa82d/kore-rpc-types/src/Kore/JsonRpc/Types.hs#L142

**Comment by geo2a** [comment]
Closed by https://github.com/runtimeverification/haskell-backend/pull/3846
