### ISSUE TITLE
Misinterpretation of stuck result for #assume(false) as depth-bound(0)

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3633]
Related to #3630 and https://github.com/runtimeverification/evm-semantics/issues/1944

It appears as though haskell-backend's `kore-rpc` returns `depth-bound` with `depth: 0` in case an `assume(false)` is found in a foundry execution.
The expected result would be `stuck`, not `depth-bound`.

**Comment by ehildenb** [comment]
We want a separate type of response though specifically, the `vacuous` response. See #3630.

**Comment by jberthold** [comment]
The original problem is fixed in #3634 . If we want to add a new stop reason, we should discuss it on #3630  separately.
