### ISSUE TITLE
add-module should allow the same module multiple times 

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3640]
If kore-rpc is started and then multiple identical "add-module" requests are sent, this should be allowed with idempotent behavior. The idea is to not report an error if a module already exists (and just do nothing instead) if the two modules have the same digest attribute.

This is blocking my integration of the maude backend so it's pretty high priority for me. I can do it myself if someone wants to give me an overview of what needs to be changed and how though.

**Comment by goodlyrottenapple** [comment]
I belive kore-rpc already allows this. It's only the booster that throws an error as far as i can see
