### ISSUE TITLE
Use tags instead of `Bool` fields for log settings in RPC requests

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3655]
To simplify future extensions and changes, we should use a list of textual "tags" instead of many boolean-valued optional fields to configure what is being logged and returned in RPC responses.

Previously:
```
"log-xxx-rewrites": true, 
"log-yyy-simplifications": true, 
.,..
```
Now:
```
"log-tags": [ "log-xxx-rewrites", "log-yyy-simplifications" ]
```

This needs to be prepared in `pyk` before starting to implement the changed format.

**Comment by geo2a** [comment]
We have made the decision to remove the logging feature form the KORE RPC protocol. See [docs/logging.md](https://github.com/runtimeverification/haskell-backend/blob/master/docs/logging.md) for the new approach.
