### ISSUE TITLE
RPC request parameter to only log specific successful simplifications

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/haskell-backend#3672]
At the moment the only option to find out if a specific simplification has been applied is to sent `"log-successful-simplifications": true` which will return entries of this shape
```json
{ 
  "tag": "simplification",
  "original-term": ...,
  "result": {
    "tag": "success",
    "rewritten-term": ...,
    "rule-id": ...
  }
}
```
However, the resulting response will likely be massive (10s of GBs). 

Perhaps the easier thing would be to modify the `"log-successful-simplifications": true` parameter to either take a bool or a list of rule labels, i.e. `"log-successful-simplifications": ["keccak-eq-conc-false"]`.

**Comment by jberthold** [comment]
For logging simplifications, the new context-based logging should be used.
A log context `rule <UNIQUE-ID-7-CHAR>` for a rule with a certain unique ID can be used to track that particular rule.
