### ISSUE TITLE
`kore-rpc` produces a three-way branch for `JUMPI` in KEVM

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/haskell-backend#3690]
I've managed to isolate the request that makes `kore-rpc`  branch with 3 "next-states" at depth 0. I've tested with commits `811e94fbcaef8550a6a709a9ce793f7166457911` and `2a99e06e67fb408a1219459978177fbb7843dee0`.

Attached are the definition, request which branches at depth 0 and the pretty-printed response:
[request_three_way_branch.json](https://github.com/runtimeverification/kontrol/files/13216548/request_three_way_branch.json)
[definition.kore.txt](https://github.com/runtimeverification/kontrol/files/13216543/definition.kore.txt)
[response_three_way_branch_kore-rpc-dev.pretty.txt](https://github.com/runtimeverification/kontrol/files/13216550/response_three_way_branch_kore-rpc-dev.pretty.txt)

## Expected behavior

Only two branches are produced, i.e. next states 0 and 1 from the pretty-printed response.

**Comment by ehildenb** [comment]
In the first state, I see:

```
JUMPI 1147 bool2Word ( 1 <<Word bool2Word ( maxUInt128 <Int VV0_x_114b9705:Int ) <<Int 7 <=Int VV0_x_114b9705:Int )
...
#And #Not ( { 0 #Equals bool2Word ( maxUInt128 <Int VV0_x_114b9705:Int ) <<Int 7 } )
```

`bool2Word` always returns `0` or `1`. So if we have `#Not { 0 #Equals bool2Word(B) <<Int 7 }`, then we have `{ 1 #Equals bool2Word(B) }`, which means that we have `{ true #Equals B }`.

Can we add lemmas like this?

```
rule { 0 #Equals bool2Word(B) <<Int N } => { 0 #Equals bool2Word(B) } requires 0 <=Int N [simplification]
rule { 0 #Equals bool2Word(B) } => { false #Equals B } [simplification]
```

**Comment by geo2a** [comment]
The `<<Word` function does not have an `smtlib` attribute. Adding the attribute manually in `definition.kore`:
```
  symbol Lbl'Unds-LT--LT-'Word'UndsUnds'EVM-TYPES'Unds'Int'Unds'Int'Unds'Int{}(SortInt{}, SortInt{}) : SortInt{} [smtlib{}("shlWord"), format{}("%1 %c<<Word%r %2"), function{}(), functional{}(), left{}(), priorities{}(), right{}(), terminals{}("010"), total{}()]
```
makes the constraints simplify to `#Bottom`.

@ehildenb what do you think? Should we add `smtlib` attributes to all functions on `Word`, like we have them on functions on `Int` in [domains.md](https://kframework.org/k-distribution/include/kframework/builtin/domains/#integer-arithmetic)?
