### ISSUE TITLE
Change to `simplify` endpoint behavior w.r.t. generating ceil conditions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3730]
In pyk, we use the `simplify` endpoint to generate initial ceil conditions to feed to the backends on proofs (https://github.com/runtimeverification/pyk/blob/b970e0cbc6c0df6872e6552af76239478a831b9b/src/pyk/kcfg/explore.py#L276).

In th elatest K update to pyk (https://github.com/runtimeverification/pyk/pull/913), we have a test failing because the `cterm_assume_defined` ends up computing different definedness constraints on the old backend on the version before vs. version in that PR.

Attached are bug reports of th einteraction collect on `master` (`ceil-gen-simplify-good.tar.gz`), and on the update-deps branch (`ceil-gen-simplify-bad.tar.gz`). The first request/response pair is what differs, in the `master` version we have 2 `#Ceil` conditions generated for the initial state, and in the `update-deps` version we only have 1.

I've also made a PR which isolates a more specific test of this: https://github.com/runtimeverification/pyk/pull/914. The K spec in question is this one: https://github.com/runtimeverification/pyk/blob/master/src/tests/integration/k-files/mini-kevm-spec.k, against this definition: https://github.com/runtimeverification/pyk/blob/master/src/tests/integration/k-files/mini-kevm.k.

**Comment by tothtamas28** [comment]
The commit that breaks the `pyk` test in question: https://github.com/runtimeverification/haskell-backend/commit/fa0d3b2809154e4c01c0ab62660f757a8fc31dfb.

**Comment by geo2a** [comment]
I have discovered  something very interesting: if I *reorder* the element in the storage when formulating the claim:
```diff
         <account>
           <acctID> ACCT_ID </acctID>
           <storage>
-            #hashedLocation("Solidity", 4, .IntList)          |-> STOPPED
             #hashedLocation("Solidity", 1, FROM_ID)           |-> STOPPED
             #hashedLocation("Solidity", 2, FROM_ID CALLER_ID) |-> STOPPED
+            #hashedLocation("Solidity", 4, .IntList)          |-> STOPPED
             _:Map
           </storage>
           <origStorage>
-            #hashedLocation("Solidity", 4, .IntList)          |-> STOPPED
             #hashedLocation("Solidity", 1, FROM_ID)           |-> STOPPED
             #hashedLocation("Solidity", 2, FROM_ID CALLER_ID) |-> STOPPED
+            #hashedLocation("Solidity", 4, .IntList)          |-> STOPPED
             _:Map
           </origStorage>
```
the proof passes.
