### ISSUE TITLE
Adding `symbol(ite)` to `#if_#then_#else_#fi` causes regression

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/haskell-backend#3731]
Adding `symbol(ite)` to `#if_#then_#else_#fi` (in runtimeverification/k#4024, partially reverted since) caused regression in the following `pyk` test:

https://github.com/runtimeverification/pyk/blob/e1b9407afc8cce2be00ff83101e29b2dd16844eb/src/tests/integration/proof/test_mini_kevm.py#L51

Bug reports:
* Original behavior: [if_then_else_fi.zip](https://github.com/runtimeverification/haskell-backend/files/14403707/if_then_else_fi.zip)
* Faulty behavior: [ite.zip](https://github.com/runtimeverification/haskell-backend/files/14403708/ite.zip)

Setting the original symbol, i.e.

```
symbol(#if_#then_#else_#fi_K-EQUAL-SYNTAX_Sort_Bool_Sort_Sort)
```

does not produce the issue. This indicates that the symbol name might be hardcoded somewhere.

The issue is very similar to #3730.

**Comment by geo2a** [comment]
I tried looking for that symbol in the source code:
```
git grep -n "Lbl'Hash'if'UndsHash'then'UndsHash'else'UndsHash'fi'Unds'K-EQUAL-SYNTAX'Unds'Sort'Unds'Bool'Unds'Sort'Unds'Sort" kore
```
and got nothing.

**Comment by geo2a** [comment]
Could you elaborate on how this issue is similar to #3730?

**Comment by geo2a** [comment]
OK, so the similarity between this issue and #3730 is that the first response is wrong in the same way, i.e. one Ceil condition is missing. This is really strange because the two issues seems to have different causes.

**Comment by geo2a** [comment]
Using `kore-rpc` with the fix from https://github.com/runtimeverification/haskell-backend/pull/3732 makes the first request from both bug reports produce the same response: no more difference in ceil conditions anymore.

**Comment by tothtamas28** [comment]
I ran the `pyk` test with #3732, it indeed fixes the issue. :rocket:
