### ISSUE TITLE
Simplification rule involving List sort does not apply

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3749]
`test.k`:

```
module TEST
  imports INT
  imports BOOL
  imports LIST

  configuration <k> $PGM:Pgm </k>

  syntax Pgm ::= foo() | bar()

  rule foo() => bar() ensures size(ListItem(?A:Int) ListItem(?B:Int) ?L:List) >Int 0
  rule [simplify-size]: size(ListItem(_) WS) => size(WS) +Int 1 [simplification]

endmodule
```

```
kompile test.k --backend haskell
krun -cPGM="foo()"
```

I expect to see the simplification rule labeled "simplify-size" to apply, but it does not. This is blocking pi^2's ability to modify the KEVM configuration. This applies to the legacy haskell backend. We either need a fix or some kind of workaround.

**Comment by dwightguth** [comment]
Here is what I get with `--debug-attempted-equations`:

```
kore-exec: [173020] Debug (DebugAttemptEquation):
    applying equation (label:  TEST.simplify-size ) at /home/dwightguth/test/test.k:11:25-11:64 to term:
        /* T Fn D Spa */
        Lblsize'LParUndsRParUnds'LIST'Unds'Int'Unds'List{}(
            /* T Fn D Sfa */
            Lbl'Unds'List'Unds'{}(
                /* T Fn D Sfa */
                /* InternalList: */ Lbl'Unds'List'Unds'{}(
                    LblListItem{}(
                        /* T Fn D Sfa */
                        /* Inj: */ inj{SortInt{}, SortKItem{}}(
                            /* T Fn D Sfa */ RuleVar'Ques'A:SortInt{}
                        )
                    ),
                    LblListItem{}(
                        /* T Fn D Sfa */
                        /* Inj: */ inj{SortInt{}, SortKItem{}}(
                            /* T Fn D Sfa */ RuleVar'Ques'B:SortInt{}
                        )
                    )
                ),
                /* T Fn D Sfa */ RuleVar'Ques'L:SortList{}
            )
        )
Context:
    (DebugAttemptEquation) while applying equation (label:  TEST.simplify-size ) at /home/dwightguth/test/test.k:11:25-11:64
kore-exec: [178422] Debug (DebugAttemptEquation):
    equation is not applicable:
    equation did not match term:  list lengths are not equal
Context:
    (DebugAttemptEquation) while applying equation (label:  TEST.simplify-size ) at /home/dwightguth/test/test.k:11:25-11:64
 ```
 
 Seems to confirm it's a pattern matching but, but it doesn't have a lot to go on.

**Comment by geo2a** [comment]
This indeed seems to be a list matching bug. The error is produced in `patternMatch'` function, in the [case](https://github.com/runtimeverification/haskell-backend/blob/093af3153a5e07626d9b2e628d7ad4fc77c5a723/kore/src/Kore/Rewrite/Axiom/Matcher.hs#L453) for lists.

A simple workaround would be two have a specialized simplification for the double-headed list:

```
  rule [simplify-size-one]: size(ListItem(_) WS) => size(WS) +Int 1 [simplification]
  rule [simplify-size-two]: size(ListItem(_) ListItem(_) WS) => size(WS) +Int 2 [simplification]
```

Would such a workaround work for you @dwightguth?

In the meantime, we should fix the list matching code.

**Comment by dwightguth** [comment]
That depends: would having a two element rule handle the case where the subject has three elements and a variable? If not, it's not really a powerful enough workaround.

**Comment by geo2a** [comment]
I've tries this variation with three exsitentials:
```
module TEST
  imports INT
  imports BOOL
  imports LIST

  configuration <k> $PGM:Pgm </k>

  syntax Pgm ::= foo() | bar()

  rule foo() => bar() ensures size(ListItem(?A:Int) ListItem(?B:Int) ListItem(?C:Int) ?L:List) >Int 0

  rule [simplify-size]: size(L:List WS:List) => size(L) +Int size(WS) [simplification]

endmodule
```

And it works, producing the desired result:
```
  <k>
    bar ( ) ~> .K
  </k>
#And
  {
    true
  #Equals
    size ( ?L:List ) +Int 3 >Int 0
  }
```

**Comment by dwightguth** [comment]
Hi, this second variation was able to make progress, but it eventually ended up stuck on the exact same bug of needing to be able to match a list with an arbitrary number of elements plus a variable at the end against the pattern `ListItem(_) L:List`. In this latter example that I eventually ran into, the rule cannot be rewritten in the manner you describe.

**Comment by dwightguth** [comment]
Incidentally, I discovered another related bug:

The term `(ListItem ( A:Int ) ListItem ( B:Int ) WS:List) [ 0 ]` ought to reduce to `I:Int` but it does not. This one might better be solved via a `LIST-SYMBOLIC` module in the K prelude, however. We might want to discuss this in a meeting. Either way, the matching bug still needs either a workaround to handle subjects with arbitrary numbers of elements, or a fix.

**Comment by geo2a** [comment]
@dwightguth `git blame` shows that you have written the current pattern code. I have little experience implementing pattern matching algorithms, but I am very keen to learn. Could we meet next week to look at the code together and figure out a plan to modify it so that it supports your use-case?
