### ISSUE TITLE
Remove sort injections from terms, keep sort info in sort table

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3782]
This is a proposal (after discussing with @ehildenb) to remove sort injections from the internal representations of terms and reason about sorts using a pre-build sort table.

When unparsing, I believe it's reasonable to reinsert injections where appropriate using the sort table. @radumereuta points out that the frontend does something similar when generating injections:
- Here is how the front end calculates how to add injections: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/AddSortInjections.java
- A lot of corner cases that could be considered. These may be specific only to the front-end, but maybe could be valid for the backend as well.

From @ehildenb , implementation in Pyk:  https://github.com/runtimeverification/pyk/blob/master/src/pyk/ktool/kprint.py#L473

**Comment by ehildenb** [comment]
@jberthold can we close this one?

**Comment by ehildenb** [comment]
I'm going to close for now, I don't think this is planned anytime soon.
