### ISSUE TITLE
Design: separate signature from theory

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3784]
From @ehildenb:

> Having different theories for the same signature is a very reasonable thing to happen. We already do so in many cases in K, we use tangle-tags in KEVM for having a different theory we send to each backend with teh same siganture, and we use symbolic and concrete and kast and kore attributes on modules to change the theory that each backend sees (while maintaining the same signature). In C semantics (and algorand semantics), we have the language signature defined separately because there are different phases of execution (load-time, type-check-time, execution time, etc...). In this case, once again, same signature, different theories.
It's also very common in Maude world to do this.
Keeping around the signature as read-only state is going to be necessary long-term, regardless of how much info you put onto the terms themselves. I would still say we should emphasize minimal term size/representation, because we'll need the signature around anyway and hash-table lookups shouldn't be expensive. But it's also a change we can make later.

See also full discussion, starting: https://runtimeverification.slack.com/archives/CC360GUTG/p1669215985581069

We will eventually need to support multiple theories of the same signature, let's brainstorm ideas on how to represent something like this in an optimal way.

### Ideas: 
1. `Term` only contains info available in the signature (symbol names, connectives etc.), the definition contains any data about those symbols specific to the theory (function/constructor symbol, partiality etc.). One issue here is partial map lookups, e.g. the symbol might not exist in the theory, how can we tell the type system that the definition was checked beforehand and the symbol actually exists there?

**Comment by ehildenb** [comment]
We can re-open if it seems relevant again.
