### ISSUE TITLE
Rules applied in branching result not recorded in rewrite trace back to user

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3792]
[no-branch-log.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13992745/no-branch-log.tar.gz)

This bug report was generated with [this fix](https://github.com/runtimeverification/hs-backend-booster/pull/470) _included_, so it's a separate bug from that one.

Here, we have an example that branches at depth 0, with logs turned on, but returns no successful rewrite rules for the branching. The request/response in question is `rpc_test%ArithmeticCallTest.test_double_add(uint256,uint256):0/003_{request,response}.json`.

It would be nice if we could somehow get the branching rules back as well from the backend. But it would also be good to differentiate them from the straight-line execution results, so that if we get an execute result back with N steps and a branch, we can correctly report the N steps to the execution depth and not to the branching. It would also be nice to know _which_ rule applies on each branch, so if they were returned in the same order as the branches are returned in, then we can zip them up appropriately on the pyk side.

**Comment by jberthold** [comment]
This should have been fixed meanwhile, please re-open otherwise
