### ISSUE TITLE
Create a performance test suite

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/haskell-backend#3793]
Having had some recent regressions which weren't caught for over a week (as it currently takes a long time for the booster to reach downstream kevm/kontrol), it is clear we need a performance test suite to profile changes before we merge them.

Taking the same approach as the integration tests, we should collect a set of bug reports and build a lightweight set of test scripts which will automatically run a given feature branch and compare against master. These are the metrics we want to collect and compare:

data collection per proof
------------------------

* total running time
* time spent in booster/old kore - possibly also the time graph per step?
* memory usage
* number of aborts/fallbacks?

implementation
---------------
* modify rpc client to collect timing data and collate them into a final json file per tarball
* bash script for running all proofs

interpreting results
-------------------
jupyter notebook? @geo2a has a nice notebook interpreting data. perhaps a good starting point

**Comment by geo2a** [comment]
We now measure performance changes in the downstream projects using their integrations test suites, by means of the Nix-based performance scripts in `./scripts`.
