### ISSUE TITLE
`dlopen` the LLVM library for each session worker

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/haskell-backend#3795]
Now that we have multi-threaded runtime, @nwatson22 is reporting crashes when running with multiple threads. The LLVM backend is known not to be thread-safe, so we need to either put a lock on the loaded library or dynamically load multiple copies, one per worker thread.

**Comment by jberthold** [comment]
An experiment with this caused issues both because of platform differences and because other non-thread-safe libraries are used in the background, causing the same issues.
