### ISSUE TITLE
Spurious constraints returned by backend as part of branching conditions

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3836]
I am observing constraints that are entailed by the current state returned as part of the branching conditions and am attaching a relevant bug report. Specifically, I have is a single execution step resulting is a three-way branching on
```
1a) ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) <Int pow256
1b) ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) <=Int ( maxUInt256 -Int VV1_y_114b9705:Int )
1c) 0 <=Int ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int )
1d) VV2_z_114b9705:Int <=Int ( ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) +Int VV1_y_114b9705:Int )
```
and
```
2a) ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) <Int pow256
2b) ( ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) +Int VV1_y_114b9705:Int ) <Int VV2_z_114b9705:Int
2c) ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) <=Int ( maxUInt256 -Int VV1_y_114b9705:Int )
2d) 0 <=Int ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int )
```
and 
```
3a) ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int ) <Int pow256
3b) ( maxUInt256 -Int VV1_y_114b9705:Int ) <Int ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int )
3c) 0 <=Int ( ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int ) -Int VV2_z_114b9705:Int )
```

However, the state before the branching contains
```
#And ( { true #Equals 0 <=Int VV0_x_114b9705:Int } #And ( { true #Equals VV0_x_114b9705:Int <Int pow256 }
#And ( { true #Equals 0 <=Int VV1_y_114b9705:Int } #And ( { true #Equals VV1_y_114b9705:Int <Int pow256 }
#And ( { true #Equals 0 <=Int VV2_z_114b9705:Int } #And ( { true #Equals VV2_z_114b9705:Int <Int pow256 }
#And ( { true #Equals VV2_z_114b9705:Int <=Int ( VV0_x_114b9705:Int +Int VV1_y_114b9705:Int )
#And ( { true #Equals VV0_x_114b9705:Int <=Int ( maxUInt256 -Int VV1_y_114b9705:Int ) }
```
which means that constraints 1a), 1c), 2a), 2c), 3a), and 3c) are entailed by the pre-branching state and would ideally not be returned as branching constraints. I believe that understanding this, however, requires assistance from Z3, and cannot necessarily be done just using our simplifications.

Bug report:
[spurious-constraints.tar.gz](https://github.com/runtimeverification/haskell-backend/files/15149578/spurious-constraints.tar.gz)

**Comment by jberthold** [comment]
After discussion in the team, we agreed that 1.a), 1.c) and the respective other conditions mentioned are part of a _range check_  and are rightfully part of the rule requirements in all 3 cases.
The next question is whether and how these additional conditions could be pruned when they are implied by the existing path condition. There are probably cases where some identical rule predicate parts are _not_ entailed by the path condition.

**Comment by jberthold** [comment]
Should we still keep this open?

**Comment by PetarMax** [comment]
For the moment, yes, the associated PR hasn't been merged yet.
