### ISSUE TITLE
Log full domain values when the user needs it

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/haskell-backend#3847]
Logging partial domain values is usually great, but sometimes the entire value is needed in order to make sense of what's happening, and it should be available e.g. when something like `--full-domain-values` is specified.

**Comment by jberthold** [comment]
Thinking about solving this with a json mode for the (simplification) logs - which would necessarily provide the full values to be useful.

**Comment by geo2a** [comment]
Implemented in https://github.com/runtimeverification/haskell-backend/pull/3963
