### ISSUE TITLE
Remove code that collects and returns RPC simplification logs

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/haskell-backend#3871]
We have deprecated the `log-successful-simplifications` and `log-failed-simplifications` request parameters, and we have not been collecting these logs. We should clean-up the code.

I've confirmed with @tothtamas28 that the `pyk` prover does not use these request parameters.

**Comment by jberthold** [comment]
Draft code for the removal is in https://github.com/runtimeverification/haskell-backend/tree/jb/log-collection-fixes (but it changes the RPC response type, which should probably be reverted to make the roll-out easier).

**Comment by geo2a** [comment]
Oops, @jberthold I've accidentally repeated your work without looking the issue...
