### ISSUE TITLE
Return rule label even if rule id is not present

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3913]
Currently, in the `execute` response, when a rule is returned that is auto-generated, we get `UNKNOWN` as the rule-id that is returned. This is unfortunate, because these rules often do have unique labels (just not ids).

Can we add `rule-label` as another field to the response which includes the rules label? That can be pretty helpful for displaying the rule that was used for that step of execution in our visualizer.

**Comment by geo2a** [comment]
Discussing this, we suggest to use the rule label as the unique id (if the id is not present). If a rule has not unique id, we will use the rule label when internalising the rule. This will allow us to return the label in the `rule-id` field for these rules with minimal modification to the code.
