### ISSUE TITLE
Crash in SMT solver on input during execute request

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3934]
Related: https://github.com/runtimeverification/k/issues/4359

I'm working on getting the last few proofs in KEVM working on the booster RPC server instead of on the legacy `kprove` prover, so we can remove that entry point. I came across a proof that is causing a crash in the booster due to some SMT translation error. I've attached the bug report, it should be the last request/response pair.

For context, it's from this proof: https://github.com/runtimeverification/evm-semantics/blob/master/tests/specs/examples/sum-to-n-foundry-spec.k

[smt-crash.tar.gz](https://github.com/user-attachments/files/15793793/smt-crash.tar.gz)

**Comment by ehildenb** [comment]
Running the same proof without the booster also causes an SMT crash.

Additionally, running the proof without the cut-rule set there, allows it to execute past that point and pass. But I need a cut-point here for other reasons.

**Comment by jberthold** [comment]
From the error message, this looks like something I investigated about 2 weeks ago: https://github.com/runtimeverification/k/issues/4400
We can implement a deduplication of the `smtlib` symbols in booster to address this problem (the code already exists [in a commit](https://github.com/runtimeverification/haskell-backend/commit/279bfb71687ad6621827eb9b8f51eb6820fa8aae) on an open PR that I had to shelve for the time being).
