### ISSUE TITLE
Stabilise normalisation of `Int`comparison operators

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3938]
Currently, there is a back-and-forth happening in the backend which keeps transforming `notBool ==Int` into `=/=Int` and vice versa:
```
[proxy][abort][detail] Kore simplification: Diff (< before - > after)
383d382
<     notBool_(_==Int_(VarCALLER_ID:SortInt{}, "6453264744265472...truncated"))
392c391,392
<     notBool_(_==Int_(VarCONTRACT_ID:SortInt{}, "6453264744265472...truncated"))
---
>     _=/=Int_(VarCALLER_ID:SortInt{}, "6453264744265472...truncated")
>     _=/=Int_(VarCONTRACT_ID:SortInt{}, "6453264744265472...truncated")
395d394
<     notBool_(_==Int_(VarORIGIN_ID:SortInt{}, "6453264744265472...truncated"))
396a396
>     _=/=Int_(VarORIGIN_ID:SortInt{}, "6453264744265472...truncated")
```
Specifically, `notBool ==Int` is transformed into `=/=Int` when the booster performs internalisation [here](https://github.com/runtimeverification/haskell-backend/blob/e8a623fd106b785f9557ad617fe4ff7ea7bb438c/booster/library/Booster/Syntax/Json/Internalise.hs#L432), whereas `=/=Int` is transformed into `notBool ==Int` whenever [this simplification](https://github.com/runtimeverification/k/blob/f8eac69f8632e3254bf6f820c2262db5d6708bb1/k-distribution/include/kframework/builtin/domains.md?plain=1#L1438) from `domains.md` is applied. I think that this means that during analysis we are working with `notBool ==Int`.

I would suggest that we decide which format we prefer, together with choosing the level at which the format is established. It can be at the K-level, via simplifications, or at the backend-level, via internalisation.

I would also suggest that we normalise the other comparison operators, possibly favouring `<=Int` and `<Int`. This would mean that we do not see `>=Int`, `>Int`, or `notBool [<=Int/<Int/>=Int/>Int]`. We are already [doing that in KEVM](https://github.com/runtimeverification/evm-semantics/blob/af074c9a6f4c3942d0167e91ae357c4dbf8a3f93/kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/int-simplification.k#L207):
```
    // inequality sign normalization
    rule          A  >Int B  => B  <Int A [simplification]
    rule          A >=Int B  => B <=Int A [simplification]
    rule notBool (A  <Int B) => B <=Int A [simplification]
    rule notBool (A <=Int B) => B  <Int A [simplification]
```
but could bring this up to `K` and/or decide to move this into the backend.

**Comment by ehildenb** [comment]
I vote for K level with simplifications.

**Comment by geo2a** [comment]
As I understand, Booster basically has the following rule hard-coded:
```
rule #Not (I1:Int ==Int I2:Int) => I1 =/=Int I2
```
We have anecdotal evidence that Kore will sometimes produce `#Not`.

**Comment by geo2a** [comment]
Looking further at `domains.md`, we have some [rules](https://github.com/runtimeverification/k/blob/f8eac69f8632e3254bf6f820c2262db5d6708bb1/k-distribution/include/kframework/builtin/domains.md?plain=1#L1392) that look suspiciously like they'd introduce `#Not`: 
```
  rule {K1 ==Int K2 #Equals false} => #Not({K1 #Equals K2}) [simplification]
  rule {false #Equals K1 ==Int K2} => #Not({K1 #Equals K2}) [simplification]
  rule {K1 =/=Int K2 #Equals true} => #Not({K1 #Equals K2}) [simplification]
  rule {true #Equals K1 =/=Int K2} => #Not({K1 #Equals K2}) [simplification]
``` 
could that be that this is the magic that we think is introduced by Kore? One way to find out: we should add labels to these rules and see of they are actually used. I'll create an issue.

**Comment by PetarMax** [comment]
Sorry, @goodlyrottenapple, which specific behaviour?

**Comment by goodlyrottenapple** [comment]
The back and forth of not(==Int)... no worries tho, @geo2a pointed me to a bug report which exhibits this behaviour
