### ISSUE TITLE
Normalizing associative-commutative operators

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#826]
We will need to flatten (internally) certain associative arithmetic and logical operators, so that simplifications such as
```
(X + 1) + 2 = X + (1 + 2) = X + 3
```
happen automatically.

Candidate operators are:

- `+Int`
- `*Int`
- `andBool`
- `orBool`

We should also take make the integer operations aware of `-Int` and `/Int`.

See also: https://runtimeverification.slack.com/archives/CC360GUTG/p1564513723167600

CC: @yzhang90

**Comment by virgil-serbanuta** [comment]
FWIW, z3 has a `simplify` command which, as far as I can tell, does something similar to this.

**Comment by ttuegel** [comment]
We should also do something similar for associative operators like `concatList`.

**Comment by ana-pantilie** [comment]
This is done directly in K with simplification rules.
